[hls]
relative_roots=C:/pcam5
# Inferred from syn.compile.pipeline_loops=64
syn.directive.pipeline=zipperremoval/anonymous 
syn.directive.pipeline=zipperremoval/anonymous 
syn.directive.pipeline=zipperremoval/anonymous 
syn.directive.pipeline=zipperremoval/anonymous 


