// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* DowngradeIPIdentifiedWarnings="yes" *)
module pcam_v_demosaic_0_0_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        imgRB_dout,
        imgRB_empty_n,
        imgRB_read,
        imgRB_num_data_valid,
        imgRB_fifo_cap,
        imgRgb_din,
        imgRgb_full_n,
        imgRgb_write,
        imgRgb_num_data_valid,
        imgRgb_fifo_cap,
        p_0_0_01177_217691799_lcssa1835_i,
        p_0_0_01178_217671797_lcssa1833_i,
        p_0_0_01179_217651795_lcssa1831_i,
        p_0_2_0_0_011541792_lcssa1829_i,
        p_0_1_0_0_011531790_lcssa1827_i,
        p_0_0_0_0_011521788_lcssa1825_i,
        p_0_0_0116417751787_lcssa1823_i,
        p_0_0_0116517731785_lcssa1821_i,
        p_0_0_0116617711783_lcssa1819_i,
        p_0_2_0_0_011601699_lcssa1741_i,
        p_0_1_0_0_011591696_lcssa1739_i,
        p_0_0_0_0_011581693_lcssa1737_i,
        y,
        height_val4_load,
        loopWidth,
        empty,
        xor_ln1014_1,
        width_val8_load,
        p_0_0_01177_217691798_i_out,
        p_0_0_01177_217691798_i_out_ap_vld,
        p_0_0_01178_217671796_i_out,
        p_0_0_01178_217671796_i_out_ap_vld,
        p_0_0_01179_217651794_i_out,
        p_0_0_01179_217651794_i_out_ap_vld,
        right_2_out,
        right_2_out_ap_vld,
        right_1_out,
        right_1_out_ap_vld,
        right_out,
        right_out_ap_vld,
        p_0_0_0116417751786_i_out,
        p_0_0_0116417751786_i_out_ap_vld,
        p_0_0_0116517731784_i_out,
        p_0_0_0116517731784_i_out_ap_vld,
        p_0_0_0116617711782_i_out,
        p_0_0_0116617711782_i_out_ap_vld,
        p_0_2_0_0_011601701_i_out,
        p_0_2_0_0_011601701_i_out_ap_vld,
        p_0_1_0_0_011591698_i_out,
        p_0_1_0_0_011591698_i_out_ap_vld,
        p_0_0_0_0_011581695_i_out,
        p_0_0_0_0_011581695_i_out_ap_vld
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [23:0] imgRB_dout;
input   imgRB_empty_n;
output   imgRB_read;
input  [2:0] imgRB_num_data_valid;
input  [2:0] imgRB_fifo_cap;
output  [23:0] imgRgb_din;
input   imgRgb_full_n;
output   imgRgb_write;
input  [31:0] imgRgb_num_data_valid;
input  [31:0] imgRgb_fifo_cap;
input  [7:0] p_0_0_01177_217691799_lcssa1835_i;
input  [7:0] p_0_0_01178_217671797_lcssa1833_i;
input  [7:0] p_0_0_01179_217651795_lcssa1831_i;
input  [7:0] p_0_2_0_0_011541792_lcssa1829_i;
input  [7:0] p_0_1_0_0_011531790_lcssa1827_i;
input  [7:0] p_0_0_0_0_011521788_lcssa1825_i;
input  [7:0] p_0_0_0116417751787_lcssa1823_i;
input  [7:0] p_0_0_0116517731785_lcssa1821_i;
input  [7:0] p_0_0_0116617711783_lcssa1819_i;
input  [7:0] p_0_2_0_0_011601699_lcssa1741_i;
input  [7:0] p_0_1_0_0_011591696_lcssa1739_i;
input  [7:0] p_0_0_0_0_011581693_lcssa1737_i;
input  [10:0] y;
input  [10:0] height_val4_load;
input  [10:0] loopWidth;
input  [0:0] empty;
input  [14:0] xor_ln1014_1;
input  [10:0] width_val8_load;
output  [7:0] p_0_0_01177_217691798_i_out;
output   p_0_0_01177_217691798_i_out_ap_vld;
output  [7:0] p_0_0_01178_217671796_i_out;
output   p_0_0_01178_217671796_i_out_ap_vld;
output  [7:0] p_0_0_01179_217651794_i_out;
output   p_0_0_01179_217651794_i_out_ap_vld;
output  [7:0] right_2_out;
output   right_2_out_ap_vld;
output  [7:0] right_1_out;
output   right_1_out_ap_vld;
output  [7:0] right_out;
output   right_out_ap_vld;
output  [7:0] p_0_0_0116417751786_i_out;
output   p_0_0_0116417751786_i_out_ap_vld;
output  [7:0] p_0_0_0116517731784_i_out;
output   p_0_0_0116517731784_i_out_ap_vld;
output  [7:0] p_0_0_0116617711782_i_out;
output   p_0_0_0116617711782_i_out_ap_vld;
output  [7:0] p_0_2_0_0_011601701_i_out;
output   p_0_2_0_0_011601701_i_out_ap_vld;
output  [7:0] p_0_1_0_0_011591698_i_out;
output   p_0_1_0_0_011591698_i_out_ap_vld;
output  [7:0] p_0_0_0_0_011581695_i_out;
output   p_0_0_0_0_011581695_i_out_ap_vld;

reg ap_idle;
reg imgRB_read;
reg imgRgb_write;
reg p_0_0_01177_217691798_i_out_ap_vld;
reg p_0_0_01178_217671796_i_out_ap_vld;
reg p_0_0_01179_217651794_i_out_ap_vld;
reg right_2_out_ap_vld;
reg right_1_out_ap_vld;
reg right_out_ap_vld;
reg p_0_0_0116417751786_i_out_ap_vld;
reg p_0_0_0116517731784_i_out_ap_vld;
reg p_0_0_0116617711782_i_out_ap_vld;
reg p_0_2_0_0_011601701_i_out_ap_vld;
reg p_0_1_0_0_011591698_i_out_ap_vld;
reg p_0_0_0_0_011581695_i_out_ap_vld;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_idle_pp0;
reg   [0:0] icmp_ln881_reg_1908;
reg   [0:0] icmp_ln891_reg_1912;
reg   [0:0] icmp_ln911_reg_1897;
reg    ap_predicate_op105_read_state2;
reg    ap_block_state2_pp0_stage0_iter1;
reg   [0:0] and_ln1052_reg_1950;
reg   [0:0] and_ln1052_reg_1950_pp0_iter2_reg;
reg    ap_block_state4_pp0_stage0_iter3;
reg    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln881_fu_580_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    imgRB_blk_n;
wire    ap_block_pp0_stage0;
reg    imgRgb_blk_n;
reg   [7:0] pix_8_reg_389;
reg   [7:0] pix_8_reg_389_pp0_iter2_reg;
reg    ap_block_pp0_stage0_11001;
reg   [7:0] pix_7_reg_399;
reg   [7:0] pix_7_reg_399_pp0_iter2_reg;
reg   [7:0] pix_reg_409;
reg   [7:0] pix_reg_409_pp0_iter2_reg;
wire    ap_block_pp0_stage0_11001_grp0;
reg    ap_block_pp0_stage0_subdone_grp0_done_reg;
wire    ap_block_pp0_stage0_subdone_grp0;
wire   [0:0] icmp_ln911_fu_500_p2;
wire   [0:0] icmp_ln975_fu_506_p2;
reg   [0:0] icmp_ln975_reg_1901;
reg   [0:0] icmp_ln881_reg_1908_pp0_iter1_reg;
wire   [0:0] icmp_ln891_fu_602_p2;
reg   [10:0] lineBuffer_addr_reg_1916;
reg   [10:0] lineBuffer_2_addr_reg_1922;
wire   [0:0] icmp_ln957_fu_608_p2;
reg   [0:0] icmp_ln957_reg_1928;
wire   [0:0] icmp_ln1014_fu_630_p2;
reg   [0:0] icmp_ln1014_reg_1944;
reg   [0:0] icmp_ln1014_reg_1944_pp0_iter1_reg;
reg   [0:0] icmp_ln1014_reg_1944_pp0_iter2_reg;
wire   [0:0] and_ln1052_fu_642_p2;
reg   [0:0] and_ln1052_reg_1950_pp0_iter1_reg;
reg   [7:0] p_0_0_0116617711782_i_load_reg_1954;
reg   [7:0] p_0_0_0116517731784_i_load_reg_1960;
reg   [7:0] p_0_0_0116417751786_i_load_reg_1966;
reg   [7:0] right_3_reg_1972;
reg   [7:0] right_4_reg_1977;
reg   [7:0] right_5_reg_1982;
reg   [7:0] p_0_0_01179_217651794_i_load_reg_1987;
reg   [7:0] p_0_0_01178_217671796_i_load_reg_1993;
reg   [7:0] p_0_0_01177_217691798_i_load_reg_1999;
reg   [7:0] p_0_0_0_0_011581695_i_load_reg_2005;
reg   [7:0] p_0_1_0_0_011591698_i_load_reg_2011;
reg   [7:0] p_0_2_0_0_011601701_i_load_reg_2017;
wire   [7:0] select_ln957_3_fu_786_p3;
wire   [7:0] select_ln957_4_fu_793_p3;
wire   [7:0] select_ln957_5_fu_800_p3;
wire   [7:0] select_ln957_6_fu_807_p3;
wire   [7:0] select_ln957_7_fu_814_p3;
wire   [7:0] select_ln957_8_fu_821_p3;
wire   [7:0] select_ln957_9_fu_828_p3;
wire   [7:0] select_ln957_10_fu_835_p3;
wire   [7:0] select_ln957_11_fu_842_p3;
wire  signed [9:0] r_0_in_i_fu_1580_p2;
reg  signed [9:0] r_0_in_i_reg_2068;
wire  signed [9:0] b_0_in_i_fu_1598_p2;
reg  signed [9:0] b_0_in_i_reg_2074;
reg   [1:0] tmp_21_reg_2080;
reg   [1:0] tmp_23_reg_2085;
reg    ap_condition_exit_pp0_iter1_stage0;
wire   [10:0] lineBuffer_2_address0;
wire   [10:0] lineBuffer_2_address1;
wire   [23:0] lineBuffer_2_q1;
wire   [10:0] lineBuffer_address0;
wire   [10:0] lineBuffer_address1;
wire   [23:0] lineBuffer_q1;
reg   [7:0] ap_phi_mux_p_0_0_01177_21769_ph_i_phi_fu_365_p4;
wire   [7:0] ap_phi_reg_pp0_iter1_p_0_0_01177_21769_ph_i_reg_362;
wire   [7:0] tmp_1_i_fu_706_p3;
reg   [7:0] ap_phi_mux_p_0_0_01178_21767_ph_i_phi_fu_374_p4;
wire   [7:0] ap_phi_reg_pp0_iter1_p_0_0_01178_21767_ph_i_reg_371;
wire   [7:0] tmp_i_fu_697_p3;
reg   [7:0] ap_phi_mux_p_0_0_01179_21765_ph_i_phi_fu_383_p4;
wire   [7:0] trunc_ln913_fu_735_p1;
wire   [7:0] ap_phi_reg_pp0_iter1_p_0_0_01179_21765_ph_i_reg_380;
wire   [7:0] trunc_ln902_fu_692_p1;
reg   [7:0] ap_phi_mux_pix_8_phi_fu_392_p4;
wire   [7:0] select_ln957_2_fu_778_p3;
wire   [7:0] ap_phi_reg_pp0_iter1_pix_8_reg_389;
reg   [7:0] ap_phi_mux_pix_7_phi_fu_402_p4;
wire   [7:0] select_ln957_1_fu_770_p3;
wire   [7:0] ap_phi_reg_pp0_iter1_pix_7_reg_399;
reg   [7:0] ap_phi_mux_pix_phi_fu_412_p4;
wire   [7:0] select_ln957_fu_762_p3;
wire   [7:0] ap_phi_reg_pp0_iter1_pix_reg_409;
wire   [7:0] ap_phi_reg_pp0_iter0_down_2_reg_419;
reg   [7:0] ap_phi_reg_pp0_iter1_down_2_reg_419;
reg   [7:0] ap_phi_reg_pp0_iter2_down_2_reg_419;
wire   [7:0] ap_phi_reg_pp0_iter0_down_1_reg_428;
reg   [7:0] ap_phi_reg_pp0_iter1_down_1_reg_428;
reg   [7:0] ap_phi_reg_pp0_iter2_down_1_reg_428;
wire   [7:0] ap_phi_reg_pp0_iter0_down_reg_437;
reg   [7:0] ap_phi_reg_pp0_iter1_down_reg_437;
reg   [7:0] ap_phi_reg_pp0_iter2_down_reg_437;
wire   [7:0] ap_phi_reg_pp0_iter0_left_2_reg_446;
reg   [7:0] ap_phi_reg_pp0_iter1_left_2_reg_446;
reg   [7:0] ap_phi_reg_pp0_iter2_left_2_reg_446;
wire   [7:0] ap_phi_reg_pp0_iter0_left_1_reg_455;
reg   [7:0] ap_phi_reg_pp0_iter1_left_1_reg_455;
reg   [7:0] ap_phi_reg_pp0_iter2_left_1_reg_455;
wire   [7:0] ap_phi_reg_pp0_iter0_left_reg_464;
reg   [7:0] ap_phi_reg_pp0_iter1_left_reg_464;
reg   [7:0] ap_phi_reg_pp0_iter2_left_reg_464;
wire   [7:0] ap_phi_reg_pp0_iter0_up_2_reg_473;
reg   [7:0] ap_phi_reg_pp0_iter1_up_2_reg_473;
reg   [7:0] ap_phi_reg_pp0_iter2_up_2_reg_473;
wire   [7:0] ap_phi_reg_pp0_iter0_up_1_reg_482;
reg   [7:0] ap_phi_reg_pp0_iter1_up_1_reg_482;
reg   [7:0] ap_phi_reg_pp0_iter2_up_1_reg_482;
wire   [7:0] ap_phi_reg_pp0_iter0_up_reg_491;
reg   [7:0] ap_phi_reg_pp0_iter1_up_reg_491;
reg   [7:0] ap_phi_reg_pp0_iter2_up_reg_491;
wire   [63:0] zext_ln881_fu_596_p1;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
wire    ap_block_pp0_stage0_grp0;
reg   [10:0] x_fu_146;
wire   [10:0] x_8_fu_586_p2;
wire    ap_loop_init;
reg   [10:0] ap_sig_allocacmp_z;
reg   [7:0] p_0_0_0116617711782_i_fu_150;
wire   [7:0] trunc_ln902_1_fu_715_p1;
reg   [7:0] p_0_0_0116517731784_i_fu_154;
wire   [7:0] tmp_3_i_fu_719_p3;
reg   [7:0] p_0_0_0116417751786_i_fu_158;
wire   [7:0] tmp_4_i_fu_727_p3;
reg   [7:0] right_fu_162;
reg   [7:0] right_1_fu_166;
reg   [7:0] right_2_fu_170;
reg   [7:0] p_0_0_01179_217651794_i_fu_174;
reg   [7:0] p_0_0_01178_217671796_i_fu_178;
reg   [7:0] p_0_0_01177_217691798_i_fu_182;
reg   [7:0] p_0_0_0_0_011581695_i_fu_186;
reg   [7:0] p_0_1_0_0_011591698_i_fu_190;
reg   [7:0] p_0_2_0_0_011601701_i_fu_194;
reg    ap_block_pp0_stage0_01001;
reg    lineBuffer_ce1_local;
reg    lineBuffer_we0_local;
reg    lineBuffer_ce0_local;
reg    lineBuffer_2_ce1_local;
reg    lineBuffer_2_we0_local;
wire   [23:0] LineBufVal_4_fu_870_p4;
reg    lineBuffer_2_ce0_local;
wire   [0:0] trunc_ln881_fu_592_p1;
wire   [0:0] xor_ln1014_fu_614_p2;
wire   [0:0] xor_ln1014_2_fu_620_p2;
wire   [14:0] zext_ln1014_fu_626_p1;
wire   [0:0] icmp_ln1052_fu_636_p2;
wire   [7:0] select_ln975_2_fu_863_p3;
wire   [7:0] select_ln975_1_fu_856_p3;
wire   [7:0] select_ln975_fu_849_p3;
wire   [8:0] zext_ln1023_fu_950_p1;
wire   [8:0] zext_ln1023_1_fu_954_p1;
wire   [8:0] sub_ln1023_fu_958_p2;
wire   [7:0] trunc_ln61_fu_964_p1;
wire   [0:0] tmp_10_fu_968_p3;
wire   [7:0] sub_ln61_fu_976_p2;
wire   [8:0] zext_ln1024_fu_990_p1;
wire   [8:0] zext_ln1024_1_fu_994_p1;
wire   [8:0] sub_ln1024_fu_998_p2;
wire   [7:0] trunc_ln61_4_fu_1004_p1;
wire   [0:0] tmp_11_fu_1008_p3;
wire   [7:0] sub_ln61_4_fu_1016_p2;
wire   [8:0] zext_ln1025_fu_1030_p1;
wire   [8:0] zext_ln1025_1_fu_1034_p1;
wire   [8:0] sub_ln1025_fu_1038_p2;
wire   [7:0] trunc_ln61_5_fu_1044_p1;
wire   [0:0] tmp_12_fu_1048_p3;
wire   [7:0] sub_ln61_5_fu_1056_p2;
wire   [8:0] zext_ln1026_fu_1070_p1;
wire   [8:0] zext_ln1026_1_fu_1074_p1;
wire   [8:0] sub_ln1026_fu_1078_p2;
wire   [7:0] trunc_ln61_6_fu_1084_p1;
wire   [0:0] tmp_13_fu_1088_p3;
wire   [7:0] sub_ln61_6_fu_1096_p2;
wire   [8:0] zext_ln1027_fu_1110_p1;
wire   [8:0] zext_ln1027_1_fu_1114_p1;
wire   [8:0] sub_ln1027_fu_1118_p2;
wire   [7:0] trunc_ln61_7_fu_1124_p1;
wire   [0:0] tmp_14_fu_1128_p3;
wire   [7:0] sub_ln61_7_fu_1136_p2;
wire   [8:0] zext_ln1028_fu_1150_p1;
wire   [8:0] zext_ln1028_1_fu_1154_p1;
wire   [8:0] sub_ln1028_fu_1158_p2;
wire   [7:0] trunc_ln61_8_fu_1164_p1;
wire   [0:0] tmp_15_fu_1168_p3;
wire   [7:0] sub_ln61_8_fu_1176_p2;
wire   [7:0] DRh_fu_982_p3;
wire   [7:0] DGh_fu_1062_p3;
wire   [8:0] zext_ln1030_fu_1190_p1;
wire   [8:0] zext_ln1030_1_fu_1194_p1;
wire   [8:0] add_ln1030_fu_1198_p2;
wire   [7:0] DBh_fu_1142_p3;
wire   [9:0] zext_ln1030_2_fu_1204_p1;
wire   [9:0] zext_ln1030_3_fu_1208_p1;
wire   [7:0] DRv_fu_1022_p3;
wire   [7:0] DGv_fu_1102_p3;
wire   [8:0] zext_ln1030_4_fu_1218_p1;
wire   [8:0] zext_ln1030_5_fu_1222_p1;
wire   [8:0] add_ln1030_2_fu_1226_p2;
wire   [7:0] DBv_fu_1182_p3;
wire   [9:0] zext_ln1030_6_fu_1232_p1;
wire   [9:0] zext_ln1030_7_fu_1236_p1;
wire   [9:0] add_ln1030_1_fu_1212_p2;
wire   [9:0] add_ln1030_3_fu_1240_p2;
wire   [8:0] sub_ln1033_fu_1252_p2;
wire   [8:0] sub_ln1033_1_fu_1258_p2;
wire  signed [9:0] sext_ln1033_fu_1264_p1;
wire  signed [9:0] sext_ln1033_1_fu_1268_p1;
wire  signed [9:0] add_ln1033_fu_1272_p2;
wire  signed [10:0] sext_ln1033_2_fu_1278_p1;
wire   [10:0] sub_ln1033_2_fu_1290_p2;
wire   [8:0] lshr_ln1033_1_cast_fu_1296_p4;
wire   [0:0] tmp_16_fu_1282_p3;
wire   [8:0] sub_ln1033_3_fu_1306_p2;
wire   [8:0] zext_ln_fu_1312_p4;
wire   [8:0] sub_ln1034_fu_1334_p2;
wire   [8:0] sub_ln1034_1_fu_1340_p2;
wire  signed [9:0] sext_ln1034_fu_1346_p1;
wire  signed [9:0] sext_ln1034_1_fu_1350_p1;
wire  signed [9:0] add_ln1034_fu_1354_p2;
wire  signed [10:0] sext_ln1034_2_fu_1360_p1;
wire   [10:0] sub_ln1034_2_fu_1372_p2;
wire   [8:0] lshr_ln1034_1_cast_fu_1378_p4;
wire   [0:0] tmp_17_fu_1364_p3;
wire   [8:0] sub_ln1034_3_fu_1388_p2;
wire   [8:0] zext_ln1_fu_1394_p4;
wire   [8:0] sub_ln1039_fu_1412_p2;
wire   [8:0] sub_ln1039_1_fu_1418_p2;
wire  signed [9:0] sext_ln1039_fu_1424_p1;
wire  signed [9:0] sext_ln1039_1_fu_1428_p1;
wire  signed [9:0] add_ln1039_fu_1432_p2;
wire  signed [10:0] sext_ln1039_2_fu_1438_p1;
wire   [10:0] sub_ln1039_2_fu_1450_p2;
wire   [8:0] lshr_ln1039_1_cast_fu_1456_p4;
wire   [0:0] tmp_18_fu_1442_p3;
wire   [8:0] sub_ln1039_3_fu_1466_p2;
wire   [8:0] zext_ln2_fu_1472_p4;
wire   [8:0] sub_ln1040_fu_1490_p2;
wire   [8:0] sub_ln1040_1_fu_1496_p2;
wire  signed [9:0] sext_ln1040_fu_1502_p1;
wire  signed [9:0] sext_ln1040_1_fu_1506_p1;
wire  signed [9:0] add_ln1040_fu_1510_p2;
wire  signed [10:0] sext_ln1040_2_fu_1516_p1;
wire   [10:0] sub_ln1040_2_fu_1528_p2;
wire   [8:0] lshr_ln1040_1_cast_fu_1534_p4;
wire   [0:0] tmp_19_fu_1520_p3;
wire   [8:0] sub_ln1040_3_fu_1544_p2;
wire   [8:0] zext_ln3_fu_1550_p4;
wire   [0:0] icmp_ln1030_fu_1246_p2;
wire   [8:0] select_ln1033_fu_1322_p3;
wire   [8:0] select_ln1039_fu_1482_p3;
wire   [8:0] r_0_in_i_v_v_fu_1568_p3;
wire   [9:0] zext_ln1034_1_fu_1330_p1;
wire  signed [9:0] r_0_in_i_v_v_cast_fu_1576_p1;
wire   [8:0] select_ln1034_fu_1404_p3;
wire   [8:0] select_ln1040_fu_1560_p3;
wire   [8:0] b_0_in_i_v_v_fu_1586_p3;
wire  signed [9:0] b_0_in_i_v_v_cast_fu_1594_p1;
wire  signed [11:0] r_0_in_i_cast1_fu_1624_p1;
wire   [0:0] tmp_20_fu_1636_p3;
wire   [0:0] xor_ln1046_fu_1649_p2;
wire   [0:0] icmp_ln1042_fu_1644_p2;
wire   [0:0] or_ln1042_fu_1663_p2;
wire   [7:0] select_ln1042_fu_1655_p3;
wire   [7:0] trunc_ln1046_fu_1633_p1;
wire  signed [11:0] sext_ln1048_fu_1627_p1;
wire   [0:0] tmp_22_fu_1677_p3;
wire   [0:0] xor_ln1048_fu_1690_p2;
wire   [0:0] icmp_ln1043_fu_1685_p2;
wire   [0:0] or_ln1043_fu_1704_p2;
wire   [7:0] select_ln1043_fu_1696_p3;
wire   [7:0] trunc_ln1048_fu_1630_p1;
wire   [7:0] select_ln1046_fu_1669_p3;
wire   [7:0] select_ln1048_fu_1710_p3;
wire   [7:0] phi_ln1046_fu_1718_p3;
wire   [7:0] phi_ln1048_fu_1725_p3;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
reg    ap_block_pp0;
reg    ap_predicate_op69_load_state1;
reg    ap_enable_operation_69;
reg    ap_enable_state1_pp0_iter0_stage0;
reg    ap_predicate_op97_load_state2;
reg    ap_enable_operation_97;
reg    ap_enable_state2_pp0_iter1_stage0;
reg    ap_predicate_op109_store_state2;
reg    ap_enable_operation_109;
reg    ap_predicate_op71_load_state1;
reg    ap_enable_operation_71;
reg    ap_predicate_op101_load_state2;
reg    ap_enable_operation_101;
reg    ap_predicate_op129_store_state2;
reg    ap_enable_operation_129;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
reg    ap_condition_228;
reg    ap_condition_1208;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_block_pp0_stage0_subdone_grp0_done_reg = 1'b0;
#0 x_fu_146 = 11'd0;
#0 p_0_0_0116617711782_i_fu_150 = 8'd0;
#0 p_0_0_0116517731784_i_fu_154 = 8'd0;
#0 p_0_0_0116417751786_i_fu_158 = 8'd0;
#0 right_fu_162 = 8'd0;
#0 right_1_fu_166 = 8'd0;
#0 right_2_fu_170 = 8'd0;
#0 p_0_0_01179_217651794_i_fu_174 = 8'd0;
#0 p_0_0_01178_217671796_i_fu_178 = 8'd0;
#0 p_0_0_01177_217691798_i_fu_182 = 8'd0;
#0 p_0_0_0_0_011581695_i_fu_186 = 8'd0;
#0 p_0_1_0_0_011591698_i_fu_190 = 8'd0;
#0 p_0_2_0_0_011601701_i_fu_194 = 8'd0;
#0 ap_done_reg = 1'b0;
end

pcam_v_demosaic_0_0_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_lineBuffer_1_RAM_AUTO_1R1W #(
    .DataWidth( 24 ),
    .AddressRange( 1921 ),
    .AddressWidth( 11 ))
lineBuffer_2_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(lineBuffer_2_address0),
    .ce0(lineBuffer_2_ce0_local),
    .we0(lineBuffer_2_we0_local),
    .d0(LineBufVal_4_fu_870_p4),
    .address1(lineBuffer_2_address1),
    .ce1(lineBuffer_2_ce1_local),
    .q1(lineBuffer_2_q1)
);

pcam_v_demosaic_0_0_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_lineBuffer_1_RAM_AUTO_1R1W #(
    .DataWidth( 24 ),
    .AddressRange( 1921 ),
    .AddressWidth( 11 ))
lineBuffer_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(lineBuffer_address0),
    .ce0(lineBuffer_ce0_local),
    .we0(lineBuffer_we0_local),
    .d0(imgRB_dout),
    .address1(lineBuffer_address1),
    .ce1(lineBuffer_ce1_local),
    .q1(lineBuffer_q1)
);

pcam_v_demosaic_0_0_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_block_pp0_stage0_subdone_grp0_done_reg <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_block_pp0_stage0_subdone_grp0_done_reg <= 1'b0;
        end else if ((1'b0 == ap_block_pp0_stage0_subdone_grp0)) begin
            ap_block_pp0_stage0_subdone_grp0_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter2_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter1_stage0)) begin
            ap_enable_reg_pp0_iter2 <= 1'b0;
        end else if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_228)) begin
        if (((icmp_ln891_reg_1912 == 1'd0) & (icmp_ln881_reg_1908 == 1'd0))) begin
            ap_phi_reg_pp0_iter2_down_1_reg_428 <= p_0_0_01178_217671796_i_fu_178;
        end else if (((icmp_ln891_reg_1912 == 1'd1) & (icmp_ln881_reg_1908 == 1'd0))) begin
            ap_phi_reg_pp0_iter2_down_1_reg_428 <= select_ln957_10_fu_835_p3;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter2_down_1_reg_428 <= ap_phi_reg_pp0_iter1_down_1_reg_428;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_228)) begin
        if (((icmp_ln891_reg_1912 == 1'd0) & (icmp_ln881_reg_1908 == 1'd0))) begin
            ap_phi_reg_pp0_iter2_down_2_reg_419 <= p_0_0_01177_217691798_i_fu_182;
        end else if (((icmp_ln891_reg_1912 == 1'd1) & (icmp_ln881_reg_1908 == 1'd0))) begin
            ap_phi_reg_pp0_iter2_down_2_reg_419 <= select_ln957_9_fu_828_p3;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter2_down_2_reg_419 <= ap_phi_reg_pp0_iter1_down_2_reg_419;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_228)) begin
        if (((icmp_ln891_reg_1912 == 1'd0) & (icmp_ln881_reg_1908 == 1'd0))) begin
            ap_phi_reg_pp0_iter2_down_reg_437 <= p_0_0_01179_217651794_i_fu_174;
        end else if (((icmp_ln891_reg_1912 == 1'd1) & (icmp_ln881_reg_1908 == 1'd0))) begin
            ap_phi_reg_pp0_iter2_down_reg_437 <= select_ln957_11_fu_842_p3;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter2_down_reg_437 <= ap_phi_reg_pp0_iter1_down_reg_437;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_228)) begin
        if (((icmp_ln891_reg_1912 == 1'd0) & (icmp_ln881_reg_1908 == 1'd0))) begin
            ap_phi_reg_pp0_iter2_left_1_reg_455 <= p_0_1_0_0_011591698_i_fu_190;
        end else if (((icmp_ln891_reg_1912 == 1'd1) & (icmp_ln881_reg_1908 == 1'd0))) begin
            ap_phi_reg_pp0_iter2_left_1_reg_455 <= select_ln957_4_fu_793_p3;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter2_left_1_reg_455 <= ap_phi_reg_pp0_iter1_left_1_reg_455;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_228)) begin
        if (((icmp_ln891_reg_1912 == 1'd0) & (icmp_ln881_reg_1908 == 1'd0))) begin
            ap_phi_reg_pp0_iter2_left_2_reg_446 <= p_0_2_0_0_011601701_i_fu_194;
        end else if (((icmp_ln891_reg_1912 == 1'd1) & (icmp_ln881_reg_1908 == 1'd0))) begin
            ap_phi_reg_pp0_iter2_left_2_reg_446 <= select_ln957_5_fu_800_p3;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter2_left_2_reg_446 <= ap_phi_reg_pp0_iter1_left_2_reg_446;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_228)) begin
        if (((icmp_ln891_reg_1912 == 1'd0) & (icmp_ln881_reg_1908 == 1'd0))) begin
            ap_phi_reg_pp0_iter2_left_reg_464 <= p_0_0_0_0_011581695_i_fu_186;
        end else if (((icmp_ln891_reg_1912 == 1'd1) & (icmp_ln881_reg_1908 == 1'd0))) begin
            ap_phi_reg_pp0_iter2_left_reg_464 <= select_ln957_3_fu_786_p3;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter2_left_reg_464 <= ap_phi_reg_pp0_iter1_left_reg_464;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_228)) begin
        if (((icmp_ln891_reg_1912 == 1'd0) & (icmp_ln881_reg_1908 == 1'd0))) begin
            ap_phi_reg_pp0_iter2_up_1_reg_482 <= p_0_0_0116517731784_i_fu_154;
        end else if (((icmp_ln891_reg_1912 == 1'd1) & (icmp_ln881_reg_1908 == 1'd0))) begin
            ap_phi_reg_pp0_iter2_up_1_reg_482 <= select_ln957_7_fu_814_p3;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter2_up_1_reg_482 <= ap_phi_reg_pp0_iter1_up_1_reg_482;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_228)) begin
        if (((icmp_ln891_reg_1912 == 1'd0) & (icmp_ln881_reg_1908 == 1'd0))) begin
            ap_phi_reg_pp0_iter2_up_2_reg_473 <= p_0_0_0116417751786_i_fu_158;
        end else if (((icmp_ln891_reg_1912 == 1'd1) & (icmp_ln881_reg_1908 == 1'd0))) begin
            ap_phi_reg_pp0_iter2_up_2_reg_473 <= select_ln957_6_fu_807_p3;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter2_up_2_reg_473 <= ap_phi_reg_pp0_iter1_up_2_reg_473;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_228)) begin
        if (((icmp_ln891_reg_1912 == 1'd0) & (icmp_ln881_reg_1908 == 1'd0))) begin
            ap_phi_reg_pp0_iter2_up_reg_491 <= p_0_0_0116617711782_i_fu_150;
        end else if (((icmp_ln891_reg_1912 == 1'd1) & (icmp_ln881_reg_1908 == 1'd0))) begin
            ap_phi_reg_pp0_iter2_up_reg_491 <= select_ln957_8_fu_821_p3;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter2_up_reg_491 <= ap_phi_reg_pp0_iter1_up_reg_491;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            p_0_0_0116417751786_i_fu_158 <= p_0_0_0116417751787_lcssa1823_i;
        end else if ((1'b1 == ap_condition_1208)) begin
            p_0_0_0116417751786_i_fu_158 <= {{lineBuffer_2_q1[23:16]}};
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            p_0_0_0116517731784_i_fu_154 <= p_0_0_0116517731785_lcssa1821_i;
        end else if ((1'b1 == ap_condition_1208)) begin
            p_0_0_0116517731784_i_fu_154 <= {{lineBuffer_2_q1[15:8]}};
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            p_0_0_0116617711782_i_fu_150 <= p_0_0_0116617711783_lcssa1819_i;
        end else if ((1'b1 == ap_condition_1208)) begin
            p_0_0_0116617711782_i_fu_150 <= trunc_ln902_1_fu_715_p1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            p_0_0_01177_217691798_i_fu_182 <= p_0_0_01177_217691799_lcssa1835_i;
        end else if ((1'b1 == ap_condition_1208)) begin
            p_0_0_01177_217691798_i_fu_182 <= ap_phi_mux_p_0_0_01177_21769_ph_i_phi_fu_365_p4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            p_0_0_01178_217671796_i_fu_178 <= p_0_0_01178_217671797_lcssa1833_i;
        end else if ((1'b1 == ap_condition_1208)) begin
            p_0_0_01178_217671796_i_fu_178 <= ap_phi_mux_p_0_0_01178_21767_ph_i_phi_fu_374_p4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            p_0_0_01179_217651794_i_fu_174 <= p_0_0_01179_217651795_lcssa1831_i;
        end else if ((1'b1 == ap_condition_1208)) begin
            p_0_0_01179_217651794_i_fu_174 <= ap_phi_mux_p_0_0_01179_21765_ph_i_phi_fu_383_p4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            p_0_0_0_0_011581695_i_fu_186 <= p_0_0_0_0_011581693_lcssa1737_i;
        end else if (((icmp_ln881_reg_1908 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            p_0_0_0_0_011581695_i_fu_186 <= ap_phi_mux_pix_phi_fu_412_p4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            p_0_1_0_0_011591698_i_fu_190 <= p_0_1_0_0_011591696_lcssa1739_i;
        end else if (((icmp_ln881_reg_1908 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            p_0_1_0_0_011591698_i_fu_190 <= ap_phi_mux_pix_7_phi_fu_402_p4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            p_0_2_0_0_011601701_i_fu_194 <= p_0_2_0_0_011601699_lcssa1741_i;
        end else if (((icmp_ln881_reg_1908 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            p_0_2_0_0_011601701_i_fu_194 <= ap_phi_mux_pix_8_phi_fu_392_p4;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_228)) begin
        if (((icmp_ln891_reg_1912 == 1'd0) & (icmp_ln881_reg_1908 == 1'd0))) begin
            pix_7_reg_399 <= right_1_fu_166;
        end else if (((icmp_ln891_reg_1912 == 1'd1) & (icmp_ln881_reg_1908 == 1'd0))) begin
            pix_7_reg_399 <= select_ln957_1_fu_770_p3;
        end else if (~(icmp_ln881_reg_1908 == 1'd1)) begin
            pix_7_reg_399 <= ap_phi_reg_pp0_iter1_pix_7_reg_399;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_228)) begin
        if (((icmp_ln891_reg_1912 == 1'd0) & (icmp_ln881_reg_1908 == 1'd0))) begin
            pix_8_reg_389 <= right_2_fu_170;
        end else if (((icmp_ln891_reg_1912 == 1'd1) & (icmp_ln881_reg_1908 == 1'd0))) begin
            pix_8_reg_389 <= select_ln957_2_fu_778_p3;
        end else if (~(icmp_ln881_reg_1908 == 1'd1)) begin
            pix_8_reg_389 <= ap_phi_reg_pp0_iter1_pix_8_reg_389;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_228)) begin
        if (((icmp_ln891_reg_1912 == 1'd0) & (icmp_ln881_reg_1908 == 1'd0))) begin
            pix_reg_409 <= right_fu_162;
        end else if (((icmp_ln891_reg_1912 == 1'd1) & (icmp_ln881_reg_1908 == 1'd0))) begin
            pix_reg_409 <= select_ln957_fu_762_p3;
        end else if (~(icmp_ln881_reg_1908 == 1'd1)) begin
            pix_reg_409 <= ap_phi_reg_pp0_iter1_pix_reg_409;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            right_1_fu_166 <= p_0_1_0_0_011531790_lcssa1827_i;
        end else if ((1'b1 == ap_condition_1208)) begin
            right_1_fu_166 <= {{lineBuffer_q1[15:8]}};
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            right_2_fu_170 <= p_0_2_0_0_011541792_lcssa1829_i;
        end else if ((1'b1 == ap_condition_1208)) begin
            right_2_fu_170 <= {{lineBuffer_q1[23:16]}};
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            right_fu_162 <= p_0_0_0_0_011521788_lcssa1825_i;
        end else if ((1'b1 == ap_condition_1208)) begin
            right_fu_162 <= trunc_ln902_fu_692_p1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln881_fu_580_p2 == 1'd0) & (ap_start_int == 1'b1))) begin
            x_fu_146 <= x_8_fu_586_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            x_fu_146 <= 11'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        and_ln1052_reg_1950 <= and_ln1052_fu_642_p2;
        and_ln1052_reg_1950_pp0_iter1_reg <= and_ln1052_reg_1950;
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        icmp_ln1014_reg_1944 <= icmp_ln1014_fu_630_p2;
        icmp_ln1014_reg_1944_pp0_iter1_reg <= icmp_ln1014_reg_1944;
        icmp_ln881_reg_1908 <= icmp_ln881_fu_580_p2;
        icmp_ln881_reg_1908_pp0_iter1_reg <= icmp_ln881_reg_1908;
        icmp_ln891_reg_1912 <= icmp_ln891_fu_602_p2;
        icmp_ln911_reg_1897 <= icmp_ln911_fu_500_p2;
        icmp_ln957_reg_1928 <= icmp_ln957_fu_608_p2;
        icmp_ln975_reg_1901 <= icmp_ln975_fu_506_p2;
        lineBuffer_2_addr_reg_1922 <= zext_ln881_fu_596_p1;
        lineBuffer_addr_reg_1916 <= zext_ln881_fu_596_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        and_ln1052_reg_1950_pp0_iter2_reg <= and_ln1052_reg_1950_pp0_iter1_reg;
        b_0_in_i_reg_2074 <= b_0_in_i_fu_1598_p2;
        icmp_ln1014_reg_1944_pp0_iter2_reg <= icmp_ln1014_reg_1944_pp0_iter1_reg;
        pix_7_reg_399_pp0_iter2_reg <= pix_7_reg_399;
        pix_8_reg_389_pp0_iter2_reg <= pix_8_reg_389;
        pix_reg_409_pp0_iter2_reg <= pix_reg_409;
        r_0_in_i_reg_2068 <= r_0_in_i_fu_1580_p2;
        tmp_21_reg_2080 <= {{r_0_in_i_fu_1580_p2[9:8]}};
        tmp_23_reg_2085 <= {{b_0_in_i_fu_1598_p2[9:8]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_phi_reg_pp0_iter1_down_1_reg_428 <= ap_phi_reg_pp0_iter0_down_1_reg_428;
        ap_phi_reg_pp0_iter1_down_2_reg_419 <= ap_phi_reg_pp0_iter0_down_2_reg_419;
        ap_phi_reg_pp0_iter1_down_reg_437 <= ap_phi_reg_pp0_iter0_down_reg_437;
        ap_phi_reg_pp0_iter1_left_1_reg_455 <= ap_phi_reg_pp0_iter0_left_1_reg_455;
        ap_phi_reg_pp0_iter1_left_2_reg_446 <= ap_phi_reg_pp0_iter0_left_2_reg_446;
        ap_phi_reg_pp0_iter1_left_reg_464 <= ap_phi_reg_pp0_iter0_left_reg_464;
        ap_phi_reg_pp0_iter1_up_1_reg_482 <= ap_phi_reg_pp0_iter0_up_1_reg_482;
        ap_phi_reg_pp0_iter1_up_2_reg_473 <= ap_phi_reg_pp0_iter0_up_2_reg_473;
        ap_phi_reg_pp0_iter1_up_reg_491 <= ap_phi_reg_pp0_iter0_up_reg_491;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_0_0_0116417751786_i_load_reg_1966 <= p_0_0_0116417751786_i_fu_158;
        p_0_0_0116517731784_i_load_reg_1960 <= p_0_0_0116517731784_i_fu_154;
        p_0_0_0116617711782_i_load_reg_1954 <= p_0_0_0116617711782_i_fu_150;
        p_0_0_01177_217691798_i_load_reg_1999 <= p_0_0_01177_217691798_i_fu_182;
        p_0_0_01178_217671796_i_load_reg_1993 <= p_0_0_01178_217671796_i_fu_178;
        p_0_0_01179_217651794_i_load_reg_1987 <= p_0_0_01179_217651794_i_fu_174;
        p_0_0_0_0_011581695_i_load_reg_2005 <= p_0_0_0_0_011581695_i_fu_186;
        p_0_1_0_0_011591698_i_load_reg_2011 <= p_0_1_0_0_011591698_i_fu_190;
        p_0_2_0_0_011601701_i_load_reg_2017 <= p_0_2_0_0_011601701_i_fu_194;
        right_3_reg_1972 <= right_fu_162;
        right_4_reg_1977 <= right_1_fu_166;
        right_5_reg_1982 <= right_2_fu_170;
    end
end

always @ (*) begin
    if (((icmp_ln881_fu_580_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (icmp_ln881_reg_1908 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter2_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_start_int == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln891_reg_1912 == 1'd1) & (icmp_ln881_reg_1908 == 1'd0))) begin
        if ((icmp_ln911_reg_1897 == 1'd0)) begin
            ap_phi_mux_p_0_0_01177_21769_ph_i_phi_fu_365_p4 = {{lineBuffer_q1[23:16]}};
        end else if ((icmp_ln911_reg_1897 == 1'd1)) begin
            ap_phi_mux_p_0_0_01177_21769_ph_i_phi_fu_365_p4 = {{imgRB_dout[23:16]}};
        end else begin
            ap_phi_mux_p_0_0_01177_21769_ph_i_phi_fu_365_p4 = ap_phi_reg_pp0_iter1_p_0_0_01177_21769_ph_i_reg_362;
        end
    end else begin
        ap_phi_mux_p_0_0_01177_21769_ph_i_phi_fu_365_p4 = ap_phi_reg_pp0_iter1_p_0_0_01177_21769_ph_i_reg_362;
    end
end

always @ (*) begin
    if (((icmp_ln891_reg_1912 == 1'd1) & (icmp_ln881_reg_1908 == 1'd0))) begin
        if ((icmp_ln911_reg_1897 == 1'd0)) begin
            ap_phi_mux_p_0_0_01178_21767_ph_i_phi_fu_374_p4 = {{lineBuffer_q1[15:8]}};
        end else if ((icmp_ln911_reg_1897 == 1'd1)) begin
            ap_phi_mux_p_0_0_01178_21767_ph_i_phi_fu_374_p4 = {{imgRB_dout[15:8]}};
        end else begin
            ap_phi_mux_p_0_0_01178_21767_ph_i_phi_fu_374_p4 = ap_phi_reg_pp0_iter1_p_0_0_01178_21767_ph_i_reg_371;
        end
    end else begin
        ap_phi_mux_p_0_0_01178_21767_ph_i_phi_fu_374_p4 = ap_phi_reg_pp0_iter1_p_0_0_01178_21767_ph_i_reg_371;
    end
end

always @ (*) begin
    if (((icmp_ln891_reg_1912 == 1'd1) & (icmp_ln881_reg_1908 == 1'd0))) begin
        if ((icmp_ln911_reg_1897 == 1'd0)) begin
            ap_phi_mux_p_0_0_01179_21765_ph_i_phi_fu_383_p4 = trunc_ln902_fu_692_p1;
        end else if ((icmp_ln911_reg_1897 == 1'd1)) begin
            ap_phi_mux_p_0_0_01179_21765_ph_i_phi_fu_383_p4 = trunc_ln913_fu_735_p1;
        end else begin
            ap_phi_mux_p_0_0_01179_21765_ph_i_phi_fu_383_p4 = ap_phi_reg_pp0_iter1_p_0_0_01179_21765_ph_i_reg_380;
        end
    end else begin
        ap_phi_mux_p_0_0_01179_21765_ph_i_phi_fu_383_p4 = ap_phi_reg_pp0_iter1_p_0_0_01179_21765_ph_i_reg_380;
    end
end

always @ (*) begin
    if ((icmp_ln881_reg_1908 == 1'd0)) begin
        if ((icmp_ln891_reg_1912 == 1'd0)) begin
            ap_phi_mux_pix_7_phi_fu_402_p4 = right_1_fu_166;
        end else if ((icmp_ln891_reg_1912 == 1'd1)) begin
            ap_phi_mux_pix_7_phi_fu_402_p4 = select_ln957_1_fu_770_p3;
        end else begin
            ap_phi_mux_pix_7_phi_fu_402_p4 = ap_phi_reg_pp0_iter1_pix_7_reg_399;
        end
    end else begin
        ap_phi_mux_pix_7_phi_fu_402_p4 = ap_phi_reg_pp0_iter1_pix_7_reg_399;
    end
end

always @ (*) begin
    if ((icmp_ln881_reg_1908 == 1'd0)) begin
        if ((icmp_ln891_reg_1912 == 1'd0)) begin
            ap_phi_mux_pix_8_phi_fu_392_p4 = right_2_fu_170;
        end else if ((icmp_ln891_reg_1912 == 1'd1)) begin
            ap_phi_mux_pix_8_phi_fu_392_p4 = select_ln957_2_fu_778_p3;
        end else begin
            ap_phi_mux_pix_8_phi_fu_392_p4 = ap_phi_reg_pp0_iter1_pix_8_reg_389;
        end
    end else begin
        ap_phi_mux_pix_8_phi_fu_392_p4 = ap_phi_reg_pp0_iter1_pix_8_reg_389;
    end
end

always @ (*) begin
    if ((icmp_ln881_reg_1908 == 1'd0)) begin
        if ((icmp_ln891_reg_1912 == 1'd0)) begin
            ap_phi_mux_pix_phi_fu_412_p4 = right_fu_162;
        end else if ((icmp_ln891_reg_1912 == 1'd1)) begin
            ap_phi_mux_pix_phi_fu_412_p4 = select_ln957_fu_762_p3;
        end else begin
            ap_phi_mux_pix_phi_fu_412_p4 = ap_phi_reg_pp0_iter1_pix_reg_409;
        end
    end else begin
        ap_phi_mux_pix_phi_fu_412_p4 = ap_phi_reg_pp0_iter1_pix_reg_409;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_z = 11'd0;
    end else begin
        ap_sig_allocacmp_z = x_fu_146;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_predicate_op105_read_state2 == 1'b1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        imgRB_blk_n = imgRB_empty_n;
    end else begin
        imgRB_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_predicate_op105_read_state2 == 1'b1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        imgRB_read = 1'b1;
    end else begin
        imgRB_read = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'd1 == and_ln1052_reg_1950_pp0_iter2_reg) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        imgRgb_blk_n = imgRgb_full_n;
    end else begin
        imgRgb_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'd1 == and_ln1052_reg_1950_pp0_iter2_reg) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        imgRgb_write = 1'b1;
    end else begin
        imgRgb_write = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        lineBuffer_2_ce0_local = 1'b1;
    end else begin
        lineBuffer_2_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        lineBuffer_2_ce1_local = 1'b1;
    end else begin
        lineBuffer_2_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln891_reg_1912 == 1'd1) & (icmp_ln881_reg_1908 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        lineBuffer_2_we0_local = 1'b1;
    end else begin
        lineBuffer_2_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        lineBuffer_ce0_local = 1'b1;
    end else begin
        lineBuffer_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        lineBuffer_ce1_local = 1'b1;
    end else begin
        lineBuffer_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln911_reg_1897 == 1'd1) & (icmp_ln891_reg_1912 == 1'd1) & (icmp_ln881_reg_1908 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        lineBuffer_we0_local = 1'b1;
    end else begin
        lineBuffer_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (ap_loop_exit_ready_pp0_iter2_reg == 1'b1) & (icmp_ln881_reg_1908_pp0_iter1_reg == 1'd1))) begin
        p_0_0_0116417751786_i_out_ap_vld = 1'b1;
    end else begin
        p_0_0_0116417751786_i_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (ap_loop_exit_ready_pp0_iter2_reg == 1'b1) & (icmp_ln881_reg_1908_pp0_iter1_reg == 1'd1))) begin
        p_0_0_0116517731784_i_out_ap_vld = 1'b1;
    end else begin
        p_0_0_0116517731784_i_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (ap_loop_exit_ready_pp0_iter2_reg == 1'b1) & (icmp_ln881_reg_1908_pp0_iter1_reg == 1'd1))) begin
        p_0_0_0116617711782_i_out_ap_vld = 1'b1;
    end else begin
        p_0_0_0116617711782_i_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (ap_loop_exit_ready_pp0_iter2_reg == 1'b1) & (icmp_ln881_reg_1908_pp0_iter1_reg == 1'd1))) begin
        p_0_0_01177_217691798_i_out_ap_vld = 1'b1;
    end else begin
        p_0_0_01177_217691798_i_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (ap_loop_exit_ready_pp0_iter2_reg == 1'b1) & (icmp_ln881_reg_1908_pp0_iter1_reg == 1'd1))) begin
        p_0_0_01178_217671796_i_out_ap_vld = 1'b1;
    end else begin
        p_0_0_01178_217671796_i_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (ap_loop_exit_ready_pp0_iter2_reg == 1'b1) & (icmp_ln881_reg_1908_pp0_iter1_reg == 1'd1))) begin
        p_0_0_01179_217651794_i_out_ap_vld = 1'b1;
    end else begin
        p_0_0_01179_217651794_i_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (ap_loop_exit_ready_pp0_iter2_reg == 1'b1) & (icmp_ln881_reg_1908_pp0_iter1_reg == 1'd1))) begin
        p_0_0_0_0_011581695_i_out_ap_vld = 1'b1;
    end else begin
        p_0_0_0_0_011581695_i_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (ap_loop_exit_ready_pp0_iter2_reg == 1'b1) & (icmp_ln881_reg_1908_pp0_iter1_reg == 1'd1))) begin
        p_0_1_0_0_011591698_i_out_ap_vld = 1'b1;
    end else begin
        p_0_1_0_0_011591698_i_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (ap_loop_exit_ready_pp0_iter2_reg == 1'b1) & (icmp_ln881_reg_1908_pp0_iter1_reg == 1'd1))) begin
        p_0_2_0_0_011601701_i_out_ap_vld = 1'b1;
    end else begin
        p_0_2_0_0_011601701_i_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (ap_loop_exit_ready_pp0_iter2_reg == 1'b1) & (icmp_ln881_reg_1908_pp0_iter1_reg == 1'd1))) begin
        right_1_out_ap_vld = 1'b1;
    end else begin
        right_1_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (ap_loop_exit_ready_pp0_iter2_reg == 1'b1) & (icmp_ln881_reg_1908_pp0_iter1_reg == 1'd1))) begin
        right_2_out_ap_vld = 1'b1;
    end else begin
        right_2_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (ap_loop_exit_ready_pp0_iter2_reg == 1'b1) & (icmp_ln881_reg_1908_pp0_iter1_reg == 1'd1))) begin
        right_out_ap_vld = 1'b1;
    end else begin
        right_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign DBh_fu_1142_p3 = ((tmp_14_fu_1128_p3[0:0] == 1'b1) ? sub_ln61_7_fu_1136_p2 : trunc_ln61_7_fu_1124_p1);

assign DBv_fu_1182_p3 = ((tmp_15_fu_1168_p3[0:0] == 1'b1) ? sub_ln61_8_fu_1176_p2 : trunc_ln61_8_fu_1164_p1);

assign DGh_fu_1062_p3 = ((tmp_12_fu_1048_p3[0:0] == 1'b1) ? sub_ln61_5_fu_1056_p2 : trunc_ln61_5_fu_1044_p1);

assign DGv_fu_1102_p3 = ((tmp_13_fu_1088_p3[0:0] == 1'b1) ? sub_ln61_6_fu_1096_p2 : trunc_ln61_6_fu_1084_p1);

assign DRh_fu_982_p3 = ((tmp_10_fu_968_p3[0:0] == 1'b1) ? sub_ln61_fu_976_p2 : trunc_ln61_fu_964_p1);

assign DRv_fu_1022_p3 = ((tmp_11_fu_1008_p3[0:0] == 1'b1) ? sub_ln61_4_fu_1016_p2 : trunc_ln61_4_fu_1004_p1);

assign LineBufVal_4_fu_870_p4 = {{{select_ln975_2_fu_863_p3}, {select_ln975_1_fu_856_p3}}, {select_ln975_fu_849_p3}};

assign add_ln1030_1_fu_1212_p2 = (zext_ln1030_2_fu_1204_p1 + zext_ln1030_3_fu_1208_p1);

assign add_ln1030_2_fu_1226_p2 = (zext_ln1030_4_fu_1218_p1 + zext_ln1030_5_fu_1222_p1);

assign add_ln1030_3_fu_1240_p2 = (zext_ln1030_6_fu_1232_p1 + zext_ln1030_7_fu_1236_p1);

assign add_ln1030_fu_1198_p2 = (zext_ln1030_fu_1190_p1 + zext_ln1030_1_fu_1194_p1);

assign add_ln1033_fu_1272_p2 = ($signed(sext_ln1033_fu_1264_p1) + $signed(sext_ln1033_1_fu_1268_p1));

assign add_ln1034_fu_1354_p2 = ($signed(sext_ln1034_fu_1346_p1) + $signed(sext_ln1034_1_fu_1350_p1));

assign add_ln1039_fu_1432_p2 = ($signed(sext_ln1039_fu_1424_p1) + $signed(sext_ln1039_1_fu_1428_p1));

assign add_ln1040_fu_1510_p2 = ($signed(sext_ln1040_fu_1502_p1) + $signed(sext_ln1040_1_fu_1506_p1));

assign and_ln1052_fu_642_p2 = (icmp_ln975_fu_506_p2 & icmp_ln1052_fu_636_p2);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

always @ (*) begin
    ap_block_pp0 = ((ap_ST_fsm_pp0_stage0 == ap_CS_fsm) & (1'b1 == ap_block_pp0_stage0_subdone));
end

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = (((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_block_state4_pp0_stage0_iter3)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state2_pp0_stage0_iter1)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = (((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_block_state4_pp0_stage0_iter3)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state2_pp0_stage0_iter1)));
end

assign ap_block_pp0_stage0_11001_grp0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_grp0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_subdone = (((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_block_state4_pp0_stage0_iter3)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state2_pp0_stage0_iter1)));
end

assign ap_block_pp0_stage0_subdone_grp0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state2_pp0_stage0_iter1 = ((ap_predicate_op105_read_state2 == 1'b1) & (imgRB_empty_n == 1'b0));
end

always @ (*) begin
    ap_block_state4_pp0_stage0_iter3 = ((imgRgb_full_n == 1'b0) & (1'd1 == and_ln1052_reg_1950_pp0_iter2_reg));
end

always @ (*) begin
    ap_condition_1208 = ((icmp_ln891_reg_1912 == 1'd1) & (icmp_ln881_reg_1908 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1));
end

always @ (*) begin
    ap_condition_228 = ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

assign ap_done = ap_done_sig;

always @ (*) begin
    ap_enable_operation_101 = (ap_predicate_op101_load_state2 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_109 = (ap_predicate_op109_store_state2 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_129 = (ap_predicate_op129_store_state2 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_69 = (ap_predicate_op69_load_state1 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_71 = (ap_predicate_op71_load_state1 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_97 = (ap_predicate_op97_load_state2 == 1'b1);
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

always @ (*) begin
    ap_enable_state1_pp0_iter0_stage0 = ((ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

always @ (*) begin
    ap_enable_state2_pp0_iter1_stage0 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_phi_reg_pp0_iter0_down_1_reg_428 = 'bx;

assign ap_phi_reg_pp0_iter0_down_2_reg_419 = 'bx;

assign ap_phi_reg_pp0_iter0_down_reg_437 = 'bx;

assign ap_phi_reg_pp0_iter0_left_1_reg_455 = 'bx;

assign ap_phi_reg_pp0_iter0_left_2_reg_446 = 'bx;

assign ap_phi_reg_pp0_iter0_left_reg_464 = 'bx;

assign ap_phi_reg_pp0_iter0_up_1_reg_482 = 'bx;

assign ap_phi_reg_pp0_iter0_up_2_reg_473 = 'bx;

assign ap_phi_reg_pp0_iter0_up_reg_491 = 'bx;

assign ap_phi_reg_pp0_iter1_p_0_0_01177_21769_ph_i_reg_362 = 'bx;

assign ap_phi_reg_pp0_iter1_p_0_0_01178_21767_ph_i_reg_371 = 'bx;

assign ap_phi_reg_pp0_iter1_p_0_0_01179_21765_ph_i_reg_380 = 'bx;

assign ap_phi_reg_pp0_iter1_pix_7_reg_399 = 'bx;

assign ap_phi_reg_pp0_iter1_pix_8_reg_389 = 'bx;

assign ap_phi_reg_pp0_iter1_pix_reg_409 = 'bx;

always @ (*) begin
    ap_predicate_op101_load_state2 = ((icmp_ln891_reg_1912 == 1'd1) & (icmp_ln881_reg_1908 == 1'd0));
end

always @ (*) begin
    ap_predicate_op105_read_state2 = ((icmp_ln911_reg_1897 == 1'd1) & (icmp_ln891_reg_1912 == 1'd1) & (icmp_ln881_reg_1908 == 1'd0));
end

always @ (*) begin
    ap_predicate_op109_store_state2 = ((icmp_ln911_reg_1897 == 1'd1) & (icmp_ln891_reg_1912 == 1'd1) & (icmp_ln881_reg_1908 == 1'd0));
end

always @ (*) begin
    ap_predicate_op129_store_state2 = ((icmp_ln891_reg_1912 == 1'd1) & (icmp_ln881_reg_1908 == 1'd0));
end

always @ (*) begin
    ap_predicate_op69_load_state1 = ((icmp_ln881_fu_580_p2 == 1'd0) & (icmp_ln891_fu_602_p2 == 1'd1));
end

always @ (*) begin
    ap_predicate_op71_load_state1 = ((icmp_ln881_fu_580_p2 == 1'd0) & (icmp_ln891_fu_602_p2 == 1'd1));
end

always @ (*) begin
    ap_predicate_op97_load_state2 = ((icmp_ln891_reg_1912 == 1'd1) & (icmp_ln881_reg_1908 == 1'd0));
end

assign ap_ready = ap_ready_sig;

assign b_0_in_i_fu_1598_p2 = ($signed(zext_ln1034_1_fu_1330_p1) - $signed(b_0_in_i_v_v_cast_fu_1594_p1));

assign b_0_in_i_v_v_cast_fu_1594_p1 = $signed(b_0_in_i_v_v_fu_1586_p3);

assign b_0_in_i_v_v_fu_1586_p3 = ((icmp_ln1030_fu_1246_p2[0:0] == 1'b1) ? select_ln1034_fu_1404_p3 : select_ln1040_fu_1560_p3);

assign icmp_ln1014_fu_630_p2 = ((xor_ln1014_1 == zext_ln1014_fu_626_p1) ? 1'b1 : 1'b0);

assign icmp_ln1030_fu_1246_p2 = ((add_ln1030_1_fu_1212_p2 < add_ln1030_3_fu_1240_p2) ? 1'b1 : 1'b0);

assign icmp_ln1042_fu_1644_p2 = ((tmp_21_reg_2080 == 2'd1) ? 1'b1 : 1'b0);

assign icmp_ln1043_fu_1685_p2 = ((tmp_23_reg_2085 == 2'd1) ? 1'b1 : 1'b0);

assign icmp_ln1052_fu_636_p2 = ((ap_sig_allocacmp_z != 11'd0) ? 1'b1 : 1'b0);

assign icmp_ln881_fu_580_p2 = ((ap_sig_allocacmp_z == loopWidth) ? 1'b1 : 1'b0);

assign icmp_ln891_fu_602_p2 = ((ap_sig_allocacmp_z < width_val8_load) ? 1'b1 : 1'b0);

assign icmp_ln911_fu_500_p2 = ((y < height_val4_load) ? 1'b1 : 1'b0);

assign icmp_ln957_fu_608_p2 = ((ap_sig_allocacmp_z == 11'd0) ? 1'b1 : 1'b0);

assign icmp_ln975_fu_506_p2 = ((y != 11'd0) ? 1'b1 : 1'b0);

assign imgRgb_din = {{{phi_ln1046_fu_1718_p3}, {phi_ln1048_fu_1725_p3}}, {pix_7_reg_399_pp0_iter2_reg}};

assign lineBuffer_2_address0 = lineBuffer_2_addr_reg_1922;

assign lineBuffer_2_address1 = zext_ln881_fu_596_p1;

assign lineBuffer_address0 = lineBuffer_addr_reg_1916;

assign lineBuffer_address1 = zext_ln881_fu_596_p1;

assign lshr_ln1033_1_cast_fu_1296_p4 = {{sub_ln1033_2_fu_1290_p2[9:1]}};

assign lshr_ln1034_1_cast_fu_1378_p4 = {{sub_ln1034_2_fu_1372_p2[9:1]}};

assign lshr_ln1039_1_cast_fu_1456_p4 = {{sub_ln1039_2_fu_1450_p2[9:1]}};

assign lshr_ln1040_1_cast_fu_1534_p4 = {{sub_ln1040_2_fu_1528_p2[9:1]}};

assign or_ln1042_fu_1663_p2 = (tmp_20_fu_1636_p3 | icmp_ln1042_fu_1644_p2);

assign or_ln1043_fu_1704_p2 = (tmp_22_fu_1677_p3 | icmp_ln1043_fu_1685_p2);

assign p_0_0_0116417751786_i_out = p_0_0_0116417751786_i_load_reg_1966;

assign p_0_0_0116517731784_i_out = p_0_0_0116517731784_i_load_reg_1960;

assign p_0_0_0116617711782_i_out = p_0_0_0116617711782_i_load_reg_1954;

assign p_0_0_01177_217691798_i_out = p_0_0_01177_217691798_i_load_reg_1999;

assign p_0_0_01178_217671796_i_out = p_0_0_01178_217671796_i_load_reg_1993;

assign p_0_0_01179_217651794_i_out = p_0_0_01179_217651794_i_load_reg_1987;

assign p_0_0_0_0_011581695_i_out = p_0_0_0_0_011581695_i_load_reg_2005;

assign p_0_1_0_0_011591698_i_out = p_0_1_0_0_011591698_i_load_reg_2011;

assign p_0_2_0_0_011601701_i_out = p_0_2_0_0_011601701_i_load_reg_2017;

assign phi_ln1046_fu_1718_p3 = ((icmp_ln1014_reg_1944_pp0_iter2_reg[0:0] == 1'b1) ? pix_reg_409_pp0_iter2_reg : select_ln1046_fu_1669_p3);

assign phi_ln1048_fu_1725_p3 = ((icmp_ln1014_reg_1944_pp0_iter2_reg[0:0] == 1'b1) ? pix_8_reg_389_pp0_iter2_reg : select_ln1048_fu_1710_p3);

assign r_0_in_i_cast1_fu_1624_p1 = r_0_in_i_reg_2068;

assign r_0_in_i_fu_1580_p2 = ($signed(zext_ln1034_1_fu_1330_p1) - $signed(r_0_in_i_v_v_cast_fu_1576_p1));

assign r_0_in_i_v_v_cast_fu_1576_p1 = $signed(r_0_in_i_v_v_fu_1568_p3);

assign r_0_in_i_v_v_fu_1568_p3 = ((icmp_ln1030_fu_1246_p2[0:0] == 1'b1) ? select_ln1033_fu_1322_p3 : select_ln1039_fu_1482_p3);

assign right_1_out = right_4_reg_1977;

assign right_2_out = right_5_reg_1982;

assign right_out = right_3_reg_1972;

assign select_ln1033_fu_1322_p3 = ((tmp_16_fu_1282_p3[0:0] == 1'b1) ? sub_ln1033_3_fu_1306_p2 : zext_ln_fu_1312_p4);

assign select_ln1034_fu_1404_p3 = ((tmp_17_fu_1364_p3[0:0] == 1'b1) ? sub_ln1034_3_fu_1388_p2 : zext_ln1_fu_1394_p4);

assign select_ln1039_fu_1482_p3 = ((tmp_18_fu_1442_p3[0:0] == 1'b1) ? sub_ln1039_3_fu_1466_p2 : zext_ln2_fu_1472_p4);

assign select_ln1040_fu_1560_p3 = ((tmp_19_fu_1520_p3[0:0] == 1'b1) ? sub_ln1040_3_fu_1544_p2 : zext_ln3_fu_1550_p4);

assign select_ln1042_fu_1655_p3 = ((xor_ln1046_fu_1649_p2[0:0] == 1'b1) ? 8'd255 : 8'd0);

assign select_ln1043_fu_1696_p3 = ((xor_ln1048_fu_1690_p2[0:0] == 1'b1) ? 8'd255 : 8'd0);

assign select_ln1046_fu_1669_p3 = ((or_ln1042_fu_1663_p2[0:0] == 1'b1) ? select_ln1042_fu_1655_p3 : trunc_ln1046_fu_1633_p1);

assign select_ln1048_fu_1710_p3 = ((or_ln1043_fu_1704_p2[0:0] == 1'b1) ? select_ln1043_fu_1696_p3 : trunc_ln1048_fu_1630_p1);

assign select_ln957_10_fu_835_p3 = ((icmp_ln957_reg_1928[0:0] == 1'b1) ? ap_phi_mux_p_0_0_01178_21767_ph_i_phi_fu_374_p4 : p_0_0_01178_217671796_i_fu_178);

assign select_ln957_11_fu_842_p3 = ((icmp_ln957_reg_1928[0:0] == 1'b1) ? ap_phi_mux_p_0_0_01179_21765_ph_i_phi_fu_383_p4 : p_0_0_01179_217651794_i_fu_174);

assign select_ln957_1_fu_770_p3 = ((icmp_ln957_reg_1928[0:0] == 1'b1) ? tmp_i_fu_697_p3 : right_1_fu_166);

assign select_ln957_2_fu_778_p3 = ((icmp_ln957_reg_1928[0:0] == 1'b1) ? tmp_1_i_fu_706_p3 : right_2_fu_170);

assign select_ln957_3_fu_786_p3 = ((icmp_ln957_reg_1928[0:0] == 1'b1) ? trunc_ln902_fu_692_p1 : p_0_0_0_0_011581695_i_fu_186);

assign select_ln957_4_fu_793_p3 = ((icmp_ln957_reg_1928[0:0] == 1'b1) ? tmp_i_fu_697_p3 : p_0_1_0_0_011591698_i_fu_190);

assign select_ln957_5_fu_800_p3 = ((icmp_ln957_reg_1928[0:0] == 1'b1) ? tmp_1_i_fu_706_p3 : p_0_2_0_0_011601701_i_fu_194);

assign select_ln957_6_fu_807_p3 = ((icmp_ln957_reg_1928[0:0] == 1'b1) ? tmp_4_i_fu_727_p3 : p_0_0_0116417751786_i_fu_158);

assign select_ln957_7_fu_814_p3 = ((icmp_ln957_reg_1928[0:0] == 1'b1) ? tmp_3_i_fu_719_p3 : p_0_0_0116517731784_i_fu_154);

assign select_ln957_8_fu_821_p3 = ((icmp_ln957_reg_1928[0:0] == 1'b1) ? trunc_ln902_1_fu_715_p1 : p_0_0_0116617711782_i_fu_150);

assign select_ln957_9_fu_828_p3 = ((icmp_ln957_reg_1928[0:0] == 1'b1) ? ap_phi_mux_p_0_0_01177_21769_ph_i_phi_fu_365_p4 : p_0_0_01177_217691798_i_fu_182);

assign select_ln957_fu_762_p3 = ((icmp_ln957_reg_1928[0:0] == 1'b1) ? trunc_ln902_fu_692_p1 : right_fu_162);

assign select_ln975_1_fu_856_p3 = ((icmp_ln975_reg_1901[0:0] == 1'b1) ? tmp_i_fu_697_p3 : ap_phi_mux_p_0_0_01178_21767_ph_i_phi_fu_374_p4);

assign select_ln975_2_fu_863_p3 = ((icmp_ln975_reg_1901[0:0] == 1'b1) ? tmp_1_i_fu_706_p3 : ap_phi_mux_p_0_0_01177_21769_ph_i_phi_fu_365_p4);

assign select_ln975_fu_849_p3 = ((icmp_ln975_reg_1901[0:0] == 1'b1) ? trunc_ln902_fu_692_p1 : ap_phi_mux_p_0_0_01179_21765_ph_i_phi_fu_383_p4);

assign sext_ln1033_1_fu_1268_p1 = $signed(sub_ln1033_1_fu_1258_p2);

assign sext_ln1033_2_fu_1278_p1 = add_ln1033_fu_1272_p2;

assign sext_ln1033_fu_1264_p1 = $signed(sub_ln1033_fu_1252_p2);

assign sext_ln1034_1_fu_1350_p1 = $signed(sub_ln1034_1_fu_1340_p2);

assign sext_ln1034_2_fu_1360_p1 = add_ln1034_fu_1354_p2;

assign sext_ln1034_fu_1346_p1 = $signed(sub_ln1034_fu_1334_p2);

assign sext_ln1039_1_fu_1428_p1 = $signed(sub_ln1039_1_fu_1418_p2);

assign sext_ln1039_2_fu_1438_p1 = add_ln1039_fu_1432_p2;

assign sext_ln1039_fu_1424_p1 = $signed(sub_ln1039_fu_1412_p2);

assign sext_ln1040_1_fu_1506_p1 = $signed(sub_ln1040_1_fu_1496_p2);

assign sext_ln1040_2_fu_1516_p1 = add_ln1040_fu_1510_p2;

assign sext_ln1040_fu_1502_p1 = $signed(sub_ln1040_fu_1490_p2);

assign sext_ln1048_fu_1627_p1 = b_0_in_i_reg_2074;

assign sub_ln1023_fu_958_p2 = (zext_ln1023_fu_950_p1 - zext_ln1023_1_fu_954_p1);

assign sub_ln1024_fu_998_p2 = (zext_ln1024_fu_990_p1 - zext_ln1024_1_fu_994_p1);

assign sub_ln1025_fu_1038_p2 = (zext_ln1025_fu_1030_p1 - zext_ln1025_1_fu_1034_p1);

assign sub_ln1026_fu_1078_p2 = (zext_ln1026_fu_1070_p1 - zext_ln1026_1_fu_1074_p1);

assign sub_ln1027_fu_1118_p2 = (zext_ln1027_fu_1110_p1 - zext_ln1027_1_fu_1114_p1);

assign sub_ln1028_fu_1158_p2 = (zext_ln1028_fu_1150_p1 - zext_ln1028_1_fu_1154_p1);

assign sub_ln1033_1_fu_1258_p2 = (zext_ln1025_1_fu_1034_p1 - zext_ln1023_1_fu_954_p1);

assign sub_ln1033_2_fu_1290_p2 = ($signed(11'd0) - $signed(sext_ln1033_2_fu_1278_p1));

assign sub_ln1033_3_fu_1306_p2 = (9'd0 - lshr_ln1033_1_cast_fu_1296_p4);

assign sub_ln1033_fu_1252_p2 = (zext_ln1025_fu_1030_p1 - zext_ln1023_fu_950_p1);

assign sub_ln1034_1_fu_1340_p2 = (zext_ln1025_1_fu_1034_p1 - zext_ln1027_1_fu_1114_p1);

assign sub_ln1034_2_fu_1372_p2 = ($signed(11'd0) - $signed(sext_ln1034_2_fu_1360_p1));

assign sub_ln1034_3_fu_1388_p2 = (9'd0 - lshr_ln1034_1_cast_fu_1378_p4);

assign sub_ln1034_fu_1334_p2 = (zext_ln1025_fu_1030_p1 - zext_ln1027_fu_1110_p1);

assign sub_ln1039_1_fu_1418_p2 = (zext_ln1026_1_fu_1074_p1 - zext_ln1024_1_fu_994_p1);

assign sub_ln1039_2_fu_1450_p2 = ($signed(11'd0) - $signed(sext_ln1039_2_fu_1438_p1));

assign sub_ln1039_3_fu_1466_p2 = (9'd0 - lshr_ln1039_1_cast_fu_1456_p4);

assign sub_ln1039_fu_1412_p2 = (zext_ln1026_fu_1070_p1 - zext_ln1024_fu_990_p1);

assign sub_ln1040_1_fu_1496_p2 = (zext_ln1026_1_fu_1074_p1 - zext_ln1028_1_fu_1154_p1);

assign sub_ln1040_2_fu_1528_p2 = ($signed(11'd0) - $signed(sext_ln1040_2_fu_1516_p1));

assign sub_ln1040_3_fu_1544_p2 = (9'd0 - lshr_ln1040_1_cast_fu_1534_p4);

assign sub_ln1040_fu_1490_p2 = (zext_ln1026_fu_1070_p1 - zext_ln1028_fu_1150_p1);

assign sub_ln61_4_fu_1016_p2 = (8'd0 - trunc_ln61_4_fu_1004_p1);

assign sub_ln61_5_fu_1056_p2 = (8'd0 - trunc_ln61_5_fu_1044_p1);

assign sub_ln61_6_fu_1096_p2 = (8'd0 - trunc_ln61_6_fu_1084_p1);

assign sub_ln61_7_fu_1136_p2 = (8'd0 - trunc_ln61_7_fu_1124_p1);

assign sub_ln61_8_fu_1176_p2 = (8'd0 - trunc_ln61_8_fu_1164_p1);

assign sub_ln61_fu_976_p2 = (8'd0 - trunc_ln61_fu_964_p1);

assign tmp_10_fu_968_p3 = sub_ln1023_fu_958_p2[32'd8];

assign tmp_11_fu_1008_p3 = sub_ln1024_fu_998_p2[32'd8];

assign tmp_12_fu_1048_p3 = sub_ln1025_fu_1038_p2[32'd8];

assign tmp_13_fu_1088_p3 = sub_ln1026_fu_1078_p2[32'd8];

assign tmp_14_fu_1128_p3 = sub_ln1027_fu_1118_p2[32'd8];

assign tmp_15_fu_1168_p3 = sub_ln1028_fu_1158_p2[32'd8];

assign tmp_16_fu_1282_p3 = add_ln1033_fu_1272_p2[32'd9];

assign tmp_17_fu_1364_p3 = add_ln1034_fu_1354_p2[32'd9];

assign tmp_18_fu_1442_p3 = add_ln1039_fu_1432_p2[32'd9];

assign tmp_19_fu_1520_p3 = add_ln1040_fu_1510_p2[32'd9];

assign tmp_1_i_fu_706_p3 = {{lineBuffer_q1[23:16]}};

assign tmp_20_fu_1636_p3 = r_0_in_i_cast1_fu_1624_p1[32'd11];

assign tmp_22_fu_1677_p3 = sext_ln1048_fu_1627_p1[32'd11];

assign tmp_3_i_fu_719_p3 = {{lineBuffer_2_q1[15:8]}};

assign tmp_4_i_fu_727_p3 = {{lineBuffer_2_q1[23:16]}};

assign tmp_i_fu_697_p3 = {{lineBuffer_q1[15:8]}};

assign trunc_ln1046_fu_1633_p1 = r_0_in_i_reg_2068[7:0];

assign trunc_ln1048_fu_1630_p1 = b_0_in_i_reg_2074[7:0];

assign trunc_ln61_4_fu_1004_p1 = sub_ln1024_fu_998_p2[7:0];

assign trunc_ln61_5_fu_1044_p1 = sub_ln1025_fu_1038_p2[7:0];

assign trunc_ln61_6_fu_1084_p1 = sub_ln1026_fu_1078_p2[7:0];

assign trunc_ln61_7_fu_1124_p1 = sub_ln1027_fu_1118_p2[7:0];

assign trunc_ln61_8_fu_1164_p1 = sub_ln1028_fu_1158_p2[7:0];

assign trunc_ln61_fu_964_p1 = sub_ln1023_fu_958_p2[7:0];

assign trunc_ln881_fu_592_p1 = ap_sig_allocacmp_z[0:0];

assign trunc_ln902_1_fu_715_p1 = lineBuffer_2_q1[7:0];

assign trunc_ln902_fu_692_p1 = lineBuffer_q1[7:0];

assign trunc_ln913_fu_735_p1 = imgRB_dout[7:0];

assign x_8_fu_586_p2 = (ap_sig_allocacmp_z + 11'd1);

assign xor_ln1014_2_fu_620_p2 = (xor_ln1014_fu_614_p2 ^ 1'd1);

assign xor_ln1014_fu_614_p2 = (trunc_ln881_fu_592_p1 ^ empty);

assign xor_ln1046_fu_1649_p2 = (tmp_20_fu_1636_p3 ^ 1'd1);

assign xor_ln1048_fu_1690_p2 = (tmp_22_fu_1677_p3 ^ 1'd1);

assign zext_ln1014_fu_626_p1 = xor_ln1014_2_fu_620_p2;

assign zext_ln1023_1_fu_954_p1 = right_fu_162;

assign zext_ln1023_fu_950_p1 = ap_phi_reg_pp0_iter2_left_reg_464;

assign zext_ln1024_1_fu_994_p1 = ap_phi_reg_pp0_iter2_down_reg_437;

assign zext_ln1024_fu_990_p1 = ap_phi_reg_pp0_iter2_up_reg_491;

assign zext_ln1025_1_fu_1034_p1 = right_1_fu_166;

assign zext_ln1025_fu_1030_p1 = ap_phi_reg_pp0_iter2_left_1_reg_455;

assign zext_ln1026_1_fu_1074_p1 = ap_phi_reg_pp0_iter2_down_1_reg_428;

assign zext_ln1026_fu_1070_p1 = ap_phi_reg_pp0_iter2_up_1_reg_482;

assign zext_ln1027_1_fu_1114_p1 = right_2_fu_170;

assign zext_ln1027_fu_1110_p1 = ap_phi_reg_pp0_iter2_left_2_reg_446;

assign zext_ln1028_1_fu_1154_p1 = ap_phi_reg_pp0_iter2_down_2_reg_419;

assign zext_ln1028_fu_1150_p1 = ap_phi_reg_pp0_iter2_up_2_reg_473;

assign zext_ln1030_1_fu_1194_p1 = DGh_fu_1062_p3;

assign zext_ln1030_2_fu_1204_p1 = add_ln1030_fu_1198_p2;

assign zext_ln1030_3_fu_1208_p1 = DBh_fu_1142_p3;

assign zext_ln1030_4_fu_1218_p1 = DRv_fu_1022_p3;

assign zext_ln1030_5_fu_1222_p1 = DGv_fu_1102_p3;

assign zext_ln1030_6_fu_1232_p1 = add_ln1030_2_fu_1226_p2;

assign zext_ln1030_7_fu_1236_p1 = DBv_fu_1182_p3;

assign zext_ln1030_fu_1190_p1 = DRh_fu_982_p3;

assign zext_ln1034_1_fu_1330_p1 = pix_7_reg_399;

assign zext_ln1_fu_1394_p4 = {{add_ln1034_fu_1354_p2[9:1]}};

assign zext_ln2_fu_1472_p4 = {{add_ln1039_fu_1432_p2[9:1]}};

assign zext_ln3_fu_1550_p4 = {{add_ln1040_fu_1510_p2[9:1]}};

assign zext_ln881_fu_596_p1 = x_8_fu_586_p2;

assign zext_ln_fu_1312_p4 = {{add_ln1033_fu_1272_p2[9:1]}};

endmodule //pcam_v_demosaic_0_0_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2
