// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* DowngradeIPIdentifiedWarnings="yes" *)
module pcam_v_demosaic_0_0_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        imgG_dout,
        imgG_empty_n,
        imgG_read,
        imgG_num_data_valid,
        imgG_fifo_cap,
        imgRB_din,
        imgRB_full_n,
        imgRB_write,
        imgRB_num_data_valid,
        imgRB_fifo_cap,
        p_0_2_0_0_09091518_lcssa1555_i,
        p_0_1_0_0_09081516_lcssa1553_i,
        p_0_0_0_0_09071514_lcssa1551_i,
        p_0_0_0938_115011513_lcssa1549_i,
        p_0_0_0939_114991511_lcssa1547_i,
        p_0_0_0940_114971509_lcssa1545_i,
        p_0_2_0_0_09151506_lcssa1543_i,
        p_0_1_0_0_09141504_lcssa1541_i,
        p_0_0_0_0_09131502_lcssa1539_i,
        p_0_0_0938_21441_lcssa1473_i,
        p_0_0_0939_21438_lcssa1471_i,
        p_0_0_0940_21435_lcssa1469_i,
        p_0_0_09381411_lcssa1461_i,
        p_0_0_09391408_lcssa1459_i,
        p_0_0_09401405_lcssa1457_i,
        xor_ln772,
        trunc_ln,
        y,
        height_val4_load,
        loopWidth,
        empty,
        xor_ln772_1,
        width_val8_load,
        p_0_2_0_0_09091519_i_out,
        p_0_2_0_0_09091519_i_out_ap_vld,
        p_0_1_0_0_09081517_i_out,
        p_0_1_0_0_09081517_i_out_ap_vld,
        p_0_0_0_0_09071515_i_out,
        p_0_0_0_0_09071515_i_out_ap_vld,
        p_0_0_0938_115011512_i_out,
        p_0_0_0938_115011512_i_out_ap_vld,
        p_0_0_0939_114991510_i_out,
        p_0_0_0939_114991510_i_out_ap_vld,
        p_0_0_0940_114971508_i_out,
        p_0_0_0940_114971508_i_out_ap_vld,
        p_0_2_0_0_09151507_i_out,
        p_0_2_0_0_09151507_i_out_ap_vld,
        p_0_1_0_0_09141505_i_out,
        p_0_1_0_0_09141505_i_out_ap_vld,
        p_0_0_0_0_09131503_i_out,
        p_0_0_0_0_09131503_i_out_ap_vld,
        p_0_0_0938_21440_i_out,
        p_0_0_0938_21440_i_out_ap_vld,
        p_0_0_0939_21437_i_out,
        p_0_0_0939_21437_i_out_ap_vld,
        p_0_0_0940_21434_i_out,
        p_0_0_0940_21434_i_out_ap_vld,
        p_0_0_09381410_i_out,
        p_0_0_09381410_i_out_ap_vld,
        p_0_0_09391407_i_out,
        p_0_0_09391407_i_out_ap_vld,
        p_0_0_09401404_i_out,
        p_0_0_09401404_i_out_ap_vld
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [23:0] imgG_dout;
input   imgG_empty_n;
output   imgG_read;
input  [2:0] imgG_num_data_valid;
input  [2:0] imgG_fifo_cap;
output  [23:0] imgRB_din;
input   imgRB_full_n;
output   imgRB_write;
input  [31:0] imgRB_num_data_valid;
input  [31:0] imgRB_fifo_cap;
input  [7:0] p_0_2_0_0_09091518_lcssa1555_i;
input  [7:0] p_0_1_0_0_09081516_lcssa1553_i;
input  [7:0] p_0_0_0_0_09071514_lcssa1551_i;
input  [7:0] p_0_0_0938_115011513_lcssa1549_i;
input  [7:0] p_0_0_0939_114991511_lcssa1547_i;
input  [7:0] p_0_0_0940_114971509_lcssa1545_i;
input  [7:0] p_0_2_0_0_09151506_lcssa1543_i;
input  [7:0] p_0_1_0_0_09141504_lcssa1541_i;
input  [7:0] p_0_0_0_0_09131502_lcssa1539_i;
input  [7:0] p_0_0_0938_21441_lcssa1473_i;
input  [7:0] p_0_0_0939_21438_lcssa1471_i;
input  [7:0] p_0_0_0940_21435_lcssa1469_i;
input  [7:0] p_0_0_09381411_lcssa1461_i;
input  [7:0] p_0_0_09391408_lcssa1459_i;
input  [7:0] p_0_0_09401405_lcssa1457_i;
input  [0:0] xor_ln772;
input  [14:0] trunc_ln;
input  [10:0] y;
input  [10:0] height_val4_load;
input  [10:0] loopWidth;
input  [0:0] empty;
input  [14:0] xor_ln772_1;
input  [10:0] width_val8_load;
output  [7:0] p_0_2_0_0_09091519_i_out;
output   p_0_2_0_0_09091519_i_out_ap_vld;
output  [7:0] p_0_1_0_0_09081517_i_out;
output   p_0_1_0_0_09081517_i_out_ap_vld;
output  [7:0] p_0_0_0_0_09071515_i_out;
output   p_0_0_0_0_09071515_i_out_ap_vld;
output  [7:0] p_0_0_0938_115011512_i_out;
output   p_0_0_0938_115011512_i_out_ap_vld;
output  [7:0] p_0_0_0939_114991510_i_out;
output   p_0_0_0939_114991510_i_out_ap_vld;
output  [7:0] p_0_0_0940_114971508_i_out;
output   p_0_0_0940_114971508_i_out_ap_vld;
output  [7:0] p_0_2_0_0_09151507_i_out;
output   p_0_2_0_0_09151507_i_out_ap_vld;
output  [7:0] p_0_1_0_0_09141505_i_out;
output   p_0_1_0_0_09141505_i_out_ap_vld;
output  [7:0] p_0_0_0_0_09131503_i_out;
output   p_0_0_0_0_09131503_i_out_ap_vld;
output  [7:0] p_0_0_0938_21440_i_out;
output   p_0_0_0938_21440_i_out_ap_vld;
output  [7:0] p_0_0_0939_21437_i_out;
output   p_0_0_0939_21437_i_out_ap_vld;
output  [7:0] p_0_0_0940_21434_i_out;
output   p_0_0_0940_21434_i_out_ap_vld;
output  [7:0] p_0_0_09381410_i_out;
output   p_0_0_09381410_i_out_ap_vld;
output  [7:0] p_0_0_09391407_i_out;
output   p_0_0_09391407_i_out_ap_vld;
output  [7:0] p_0_0_09401404_i_out;
output   p_0_0_09401404_i_out_ap_vld;

reg ap_idle;
reg imgG_read;
reg imgRB_write;
reg p_0_2_0_0_09091519_i_out_ap_vld;
reg p_0_1_0_0_09081517_i_out_ap_vld;
reg p_0_0_0_0_09071515_i_out_ap_vld;
reg p_0_0_0938_115011512_i_out_ap_vld;
reg p_0_0_0939_114991510_i_out_ap_vld;
reg p_0_0_0940_114971508_i_out_ap_vld;
reg p_0_2_0_0_09151507_i_out_ap_vld;
reg p_0_1_0_0_09141505_i_out_ap_vld;
reg p_0_0_0_0_09131503_i_out_ap_vld;
reg p_0_0_0938_21440_i_out_ap_vld;
reg p_0_0_0939_21437_i_out_ap_vld;
reg p_0_0_0940_21434_i_out_ap_vld;
reg p_0_0_09381410_i_out_ap_vld;
reg p_0_0_09391407_i_out_ap_vld;
reg p_0_0_09401404_i_out_ap_vld;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_idle_pp0;
reg   [0:0] icmp_ln633_reg_2243;
reg   [0:0] icmp_ln643_reg_2247;
reg   [0:0] icmp_ln664_reg_2232;
reg    ap_predicate_op123_read_state2;
reg    ap_block_state2_pp0_stage0_iter1;
reg   [0:0] and_ln833_reg_2286;
reg   [0:0] and_ln833_reg_2286_pp0_iter3_reg;
reg    ap_block_state5_pp0_stage0_iter4;
reg    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln633_fu_874_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    imgG_blk_n;
wire    ap_block_pp0_stage0;
reg    imgRB_blk_n;
reg   [7:0] pix_4_reg_617;
reg   [7:0] pix_4_reg_617_pp0_iter3_reg;
reg    ap_block_pp0_stage0_11001;
reg   [7:0] pix_3_reg_627;
reg   [7:0] pix_3_reg_627_pp0_iter3_reg;
reg   [7:0] pix_reg_637;
reg   [7:0] pix_reg_637_pp0_iter3_reg;
wire    ap_block_pp0_stage0_11001_grp0;
reg    ap_block_pp0_stage0_subdone_grp0_done_reg;
wire    ap_block_pp0_stage0_subdone_grp0;
wire   [0:0] red_fu_773_p2;
reg   [0:0] red_reg_2221;
wire   [0:0] icmp_ln664_fu_779_p2;
wire   [0:0] icmp_ln728_fu_785_p2;
reg   [0:0] icmp_ln728_reg_2236;
reg   [0:0] icmp_ln633_reg_2243_pp0_iter1_reg;
reg   [0:0] icmp_ln633_reg_2243_pp0_iter2_reg;
reg   [0:0] icmp_ln633_reg_2243_pp0_iter3_reg;
wire   [0:0] icmp_ln643_fu_896_p2;
reg   [10:0] lineBuffer_addr_reg_2251;
reg   [10:0] lineBuffer_1_addr_reg_2257;
wire   [0:0] icmp_ln710_fu_902_p2;
reg   [0:0] icmp_ln710_reg_2263;
wire   [0:0] icmp_ln772_fu_924_p2;
reg   [0:0] icmp_ln772_reg_2282;
reg   [0:0] icmp_ln772_reg_2282_pp0_iter1_reg;
reg   [0:0] icmp_ln772_reg_2282_pp0_iter2_reg;
reg   [0:0] icmp_ln772_reg_2282_pp0_iter3_reg;
wire   [0:0] and_ln833_fu_936_p2;
reg   [0:0] and_ln833_reg_2286_pp0_iter1_reg;
reg   [0:0] and_ln833_reg_2286_pp0_iter2_reg;
reg   [7:0] p_0_0_0_0_09131503_i_load_reg_2290;
reg   [7:0] p_0_0_0_0_09131503_i_load_reg_2290_pp0_iter2_reg;
reg   [7:0] p_0_1_0_0_09141505_i_load_reg_2295;
reg   [7:0] p_0_1_0_0_09141505_i_load_reg_2295_pp0_iter2_reg;
reg   [7:0] p_0_2_0_0_09151507_i_load_reg_2300;
reg   [7:0] p_0_2_0_0_09151507_i_load_reg_2300_pp0_iter2_reg;
reg   [7:0] p_0_0_0940_114971508_i_load_reg_2305;
reg   [7:0] p_0_0_0940_114971508_i_load_reg_2305_pp0_iter2_reg;
reg   [7:0] p_0_0_0939_114991510_i_load_reg_2311;
reg   [7:0] p_0_0_0939_114991510_i_load_reg_2311_pp0_iter2_reg;
reg   [7:0] p_0_0_0938_115011512_i_load_reg_2317;
reg   [7:0] p_0_0_0938_115011512_i_load_reg_2317_pp0_iter2_reg;
reg   [7:0] p_0_0_0_0_09071515_i_load_reg_2323;
reg   [7:0] p_0_0_0_0_09071515_i_load_reg_2323_pp0_iter2_reg;
reg   [7:0] p_0_1_0_0_09081517_i_load_reg_2328;
reg   [7:0] p_0_1_0_0_09081517_i_load_reg_2328_pp0_iter2_reg;
reg   [7:0] p_0_2_0_0_09091519_i_load_reg_2333;
reg   [7:0] p_0_2_0_0_09091519_i_load_reg_2333_pp0_iter2_reg;
reg   [7:0] p_0_0_09401404_i_load_reg_2338;
reg   [7:0] p_0_0_09401404_i_load_reg_2338_pp0_iter2_reg;
reg   [7:0] p_0_0_09391407_i_load_reg_2343;
reg   [7:0] p_0_0_09391407_i_load_reg_2343_pp0_iter2_reg;
reg   [7:0] p_0_0_09381410_i_load_reg_2348;
reg   [7:0] p_0_0_09381410_i_load_reg_2348_pp0_iter2_reg;
reg   [7:0] p_0_0_0940_21434_i_load_reg_2353;
reg   [7:0] p_0_0_0940_21434_i_load_reg_2353_pp0_iter2_reg;
reg   [7:0] p_0_0_0939_21437_i_load_reg_2358;
reg   [7:0] p_0_0_0939_21437_i_load_reg_2358_pp0_iter2_reg;
reg   [7:0] p_0_0_0938_21440_i_load_reg_2363;
reg   [7:0] p_0_0_0938_21440_i_load_reg_2363_pp0_iter2_reg;
wire   [7:0] select_ln710_fu_1074_p3;
wire   [7:0] select_ln710_1_fu_1081_p3;
wire   [7:0] select_ln710_2_fu_1088_p3;
wire   [8:0] zext_ln790_1_fu_1268_p1;
reg   [8:0] zext_ln790_1_reg_2383;
wire   [8:0] zext_ln791_fu_1272_p1;
reg   [8:0] zext_ln791_reg_2388;
wire   [8:0] sub_ln817_fu_1287_p2;
reg   [8:0] sub_ln817_reg_2393;
reg   [8:0] sub_ln817_reg_2393_pp0_iter2_reg;
wire   [8:0] sub_ln818_fu_1304_p2;
reg   [8:0] sub_ln818_reg_2398;
reg   [8:0] sub_ln818_reg_2398_pp0_iter2_reg;
wire   [4:0] enable_6_fu_1586_p3;
reg   [4:0] enable_6_reg_2403;
wire   [0:0] icmp_ln800_fu_1594_p2;
reg   [0:0] icmp_ln800_reg_2409;
wire   [8:0] sub_ln819_fu_1623_p2;
reg   [8:0] sub_ln819_reg_2414;
wire   [8:0] sub_ln820_fu_1640_p2;
reg   [8:0] sub_ln820_reg_2419;
wire   [5:0] enable_7_fu_1656_p3;
wire   [10:0] add_ln820_fu_1807_p2;
reg   [10:0] add_ln820_reg_2428;
wire   [9:0] sub_ln820_2_fu_1829_p2;
reg   [9:0] sub_ln820_2_reg_2434;
reg    ap_condition_exit_pp0_iter1_stage0;
wire   [10:0] lineBuffer_1_address0;
wire   [10:0] lineBuffer_1_address1;
wire   [23:0] lineBuffer_1_q1;
wire   [10:0] lineBuffer_address0;
wire   [10:0] lineBuffer_address1;
wire   [23:0] lineBuffer_q1;
reg   [7:0] ap_phi_mux_p_0_0_0938_21489_ph_i_phi_fu_485_p4;
wire   [7:0] ap_phi_reg_pp0_iter1_p_0_0_0938_21489_ph_i_reg_482;
wire   [7:0] tmp_5_i_fu_1018_p3;
reg   [7:0] ap_phi_mux_p_0_0_0939_21487_ph_i_phi_fu_494_p4;
wire   [7:0] ap_phi_reg_pp0_iter1_p_0_0_0939_21487_ph_i_reg_491;
wire   [7:0] tmp_4_i_fu_1009_p3;
reg   [7:0] ap_phi_mux_p_0_0_0940_21485_ph_i_phi_fu_503_p4;
wire   [7:0] trunc_ln666_fu_1047_p1;
wire   [7:0] ap_phi_reg_pp0_iter1_p_0_0_0940_21485_ph_i_reg_500;
wire   [7:0] trunc_ln654_fu_1004_p1;
reg   [7:0] ap_phi_mux_downleft_2_phi_fu_512_p4;
wire   [7:0] select_ln710_9_fu_1143_p3;
wire   [7:0] ap_phi_reg_pp0_iter1_downleft_2_reg_509;
reg   [7:0] ap_phi_mux_downleft_1_phi_fu_521_p4;
wire   [7:0] select_ln710_10_fu_1151_p3;
wire   [7:0] ap_phi_reg_pp0_iter1_downleft_1_reg_518;
reg   [7:0] ap_phi_mux_downleft_phi_fu_530_p4;
wire   [7:0] select_ln710_11_fu_1159_p3;
wire   [7:0] ap_phi_reg_pp0_iter1_downleft_reg_527;
reg   [7:0] ap_phi_mux_p_0_0_0938_21441_i_phi_fu_539_p4;
wire   [7:0] select_ln710_12_fu_1167_p3;
wire   [7:0] ap_phi_reg_pp0_iter1_p_0_0_0938_21441_i_reg_536;
reg   [7:0] ap_phi_mux_p_0_0_0939_21438_i_phi_fu_548_p4;
wire   [7:0] select_ln710_13_fu_1175_p3;
wire   [7:0] ap_phi_reg_pp0_iter1_p_0_0_0939_21438_i_reg_545;
reg   [7:0] ap_phi_mux_p_0_0_0940_21435_i_phi_fu_557_p4;
wire   [7:0] select_ln710_14_fu_1183_p3;
wire   [7:0] ap_phi_reg_pp0_iter1_p_0_0_0940_21435_i_reg_554;
reg   [7:0] ap_phi_mux_upleft_2_phi_fu_566_p4;
wire   [7:0] select_ln710_3_fu_1095_p3;
wire   [7:0] ap_phi_reg_pp0_iter1_upleft_2_reg_563;
reg   [7:0] ap_phi_mux_upleft_1_phi_fu_575_p4;
wire   [7:0] select_ln710_4_fu_1103_p3;
wire   [7:0] ap_phi_reg_pp0_iter1_upleft_1_reg_572;
reg   [7:0] ap_phi_mux_upleft_phi_fu_584_p4;
wire   [7:0] select_ln710_5_fu_1111_p3;
wire   [7:0] ap_phi_reg_pp0_iter1_upleft_reg_581;
reg   [7:0] ap_phi_mux_p_0_0_09381411_i_phi_fu_593_p4;
wire   [7:0] select_ln710_6_fu_1119_p3;
wire   [7:0] ap_phi_reg_pp0_iter1_p_0_0_09381411_i_reg_590;
reg   [7:0] ap_phi_mux_p_0_0_09391408_i_phi_fu_602_p4;
wire   [7:0] select_ln710_7_fu_1127_p3;
wire   [7:0] ap_phi_reg_pp0_iter1_p_0_0_09391408_i_reg_599;
reg   [7:0] ap_phi_mux_p_0_0_09401405_i_phi_fu_611_p4;
wire   [7:0] select_ln710_8_fu_1135_p3;
wire   [7:0] ap_phi_reg_pp0_iter1_p_0_0_09401405_i_reg_608;
wire   [7:0] ap_phi_reg_pp0_iter0_pix_4_reg_617;
reg   [7:0] ap_phi_reg_pp0_iter1_pix_4_reg_617;
reg   [7:0] ap_phi_reg_pp0_iter2_pix_4_reg_617;
wire   [7:0] ap_phi_reg_pp0_iter0_pix_3_reg_627;
reg   [7:0] ap_phi_reg_pp0_iter1_pix_3_reg_627;
reg   [7:0] ap_phi_reg_pp0_iter2_pix_3_reg_627;
wire   [7:0] ap_phi_reg_pp0_iter0_pix_reg_637;
reg   [7:0] ap_phi_reg_pp0_iter1_pix_reg_637;
reg   [7:0] ap_phi_reg_pp0_iter2_pix_reg_637;
reg   [0:0] ap_phi_mux_en_rgd_3_phi_fu_650_p14;
wire   [0:0] ap_phi_reg_pp0_iter3_en_rgd_3_reg_647;
reg   [0:0] ap_phi_mux_en_rgd_2_phi_fu_676_p14;
wire   [0:0] ap_phi_reg_pp0_iter3_en_rgd_2_reg_673;
reg   [0:0] ap_phi_mux_en_rgd_1_phi_fu_702_p14;
wire   [0:0] ap_phi_reg_pp0_iter3_en_rgd_1_reg_699;
reg   [0:0] ap_phi_mux_en_rgd_phi_fu_728_p14;
wire   [0:0] ap_phi_reg_pp0_iter3_en_rgd_reg_725;
reg   [9:0] ap_phi_mux_r_1_phi_fu_754_p4;
wire   [9:0] r_fu_1889_p3;
wire   [9:0] ap_phi_reg_pp0_iter4_r_1_reg_751;
wire   [9:0] zext_ln763_fu_1835_p1;
reg   [9:0] ap_phi_mux_b_1_phi_fu_763_p4;
wire   [9:0] b_fu_1897_p3;
wire   [9:0] ap_phi_reg_pp0_iter4_b_1_reg_760;
wire   [9:0] zext_ln765_fu_1840_p1;
wire   [63:0] zext_ln633_fu_890_p1;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
wire    ap_block_pp0_stage0_grp0;
reg   [10:0] x_fu_224;
wire   [10:0] x_5_fu_880_p2;
wire    ap_loop_init;
reg   [10:0] ap_sig_allocacmp_z;
reg   [7:0] p_0_0_0_0_09131503_i_fu_228;
wire   [7:0] trunc_ln654_1_fu_1027_p1;
reg   [7:0] p_0_1_0_0_09141505_i_fu_232;
wire   [7:0] tmp_7_i_fu_1031_p3;
reg   [7:0] p_0_2_0_0_09151507_i_fu_236;
wire   [7:0] tmp_8_i_fu_1039_p3;
reg   [7:0] p_0_0_0940_114971508_i_fu_240;
reg   [7:0] p_0_0_0939_114991510_i_fu_244;
reg   [7:0] p_0_0_0938_115011512_i_fu_248;
reg   [7:0] p_0_0_0_0_09071515_i_fu_252;
reg   [7:0] p_0_1_0_0_09081517_i_fu_256;
reg   [7:0] p_0_2_0_0_09091519_i_fu_260;
reg   [7:0] p_0_0_09401404_i_fu_264;
reg   [7:0] p_0_0_09391407_i_fu_268;
reg   [7:0] p_0_0_09381410_i_fu_272;
reg   [7:0] p_0_0_0940_21434_i_fu_276;
reg   [7:0] p_0_0_0939_21437_i_fu_280;
reg   [7:0] p_0_0_0938_21440_i_fu_284;
reg    ap_block_pp0_stage0_01001;
reg    lineBuffer_ce1_local;
reg    lineBuffer_we0_local;
reg    lineBuffer_ce0_local;
reg    lineBuffer_1_ce1_local;
reg    lineBuffer_1_we0_local;
wire   [23:0] LineBufVal_2_fu_1212_p4;
reg    lineBuffer_1_ce0_local;
wire   [14:0] zext_ln772_fu_769_p1;
wire   [0:0] trunc_ln633_fu_886_p1;
wire   [0:0] xor_ln772_2_fu_908_p2;
wire   [0:0] xor_ln772_3_fu_914_p2;
wire   [14:0] zext_ln772_1_fu_920_p1;
wire   [0:0] icmp_ln833_fu_930_p2;
wire   [7:0] select_ln728_2_fu_1205_p3;
wire   [7:0] select_ln728_1_fu_1198_p3;
wire   [7:0] select_ln728_fu_1191_p3;
wire   [7:0] select_ln817_fu_1276_p3;
wire   [8:0] zext_ln817_fu_1283_p1;
wire   [7:0] select_ln818_fu_1293_p3;
wire   [8:0] zext_ln818_fu_1300_p1;
wire   [8:0] zext_ln790_fu_1346_p1;
wire   [8:0] sub_ln790_fu_1350_p2;
wire   [7:0] trunc_ln61_fu_1355_p1;
wire   [0:0] tmp_1_fu_1359_p3;
wire   [7:0] sub_ln61_fu_1367_p2;
wire   [8:0] sub_ln791_fu_1381_p2;
wire   [7:0] trunc_ln61_1_fu_1386_p1;
wire   [0:0] tmp_2_fu_1390_p3;
wire   [7:0] sub_ln61_1_fu_1398_p2;
wire   [8:0] zext_ln792_fu_1412_p1;
wire   [8:0] sub_ln792_fu_1416_p2;
wire   [7:0] trunc_ln61_2_fu_1422_p1;
wire   [0:0] tmp_3_fu_1426_p3;
wire   [7:0] sub_ln61_2_fu_1434_p2;
wire   [8:0] zext_ln793_fu_1448_p1;
wire   [8:0] sub_ln793_fu_1452_p2;
wire   [7:0] trunc_ln61_3_fu_1458_p1;
wire   [0:0] tmp_4_fu_1462_p3;
wire   [7:0] sub_ln61_3_fu_1470_p2;
wire   [7:0] agdiff_fu_1373_p3;
wire   [7:0] agdiff_1_fu_1404_p3;
wire   [0:0] enable_fu_1484_p2;
wire   [7:0] agdiff_2_fu_1440_p3;
wire   [0:0] icmp_ln796_fu_1494_p2;
wire   [1:0] or_ln_fu_1500_p3;
wire   [1:0] zext_ln769_fu_1490_p1;
wire   [1:0] enable_1_fu_1508_p3;
wire   [7:0] agdiff_3_fu_1476_p3;
wire   [0:0] icmp_ln797_fu_1520_p2;
wire   [2:0] enable_2_fu_1526_p3;
wire   [2:0] zext_ln769_1_fu_1516_p1;
wire   [2:0] enable_3_fu_1534_p3;
wire   [0:0] icmp_ln798_fu_1546_p2;
wire   [3:0] or_ln1_fu_1552_p3;
wire   [3:0] zext_ln769_2_fu_1542_p1;
wire   [3:0] enable_4_fu_1560_p3;
wire   [0:0] icmp_ln799_fu_1572_p2;
wire   [4:0] enable_5_fu_1578_p3;
wire   [4:0] zext_ln769_3_fu_1568_p1;
wire   [7:0] select_ln819_fu_1612_p3;
wire   [8:0] zext_ln819_fu_1619_p1;
wire   [7:0] select_ln820_fu_1629_p3;
wire   [8:0] zext_ln820_fu_1636_p1;
wire   [5:0] or_ln2_fu_1649_p3;
wire   [5:0] zext_ln769_4_fu_1646_p1;
wire   [8:0] select_ln817_1_fu_1719_p3;
wire   [8:0] and_ln817_fu_1727_p2;
wire   [8:0] select_ln818_1_fu_1736_p3;
wire   [8:0] and_ln818_fu_1744_p2;
wire  signed [9:0] sext_ln817_fu_1749_p1;
wire  signed [9:0] sext_ln818_fu_1732_p1;
wire   [8:0] select_ln819_1_fu_1759_p3;
wire   [9:0] add_ln817_fu_1753_p2;
wire   [8:0] and_ln819_fu_1767_p2;
wire   [8:0] select_ln820_2_fu_1780_p3;
wire   [8:0] and_ln820_fu_1788_p2;
wire  signed [9:0] sext_ln820_1_fu_1776_p1;
wire  signed [9:0] sext_ln820_fu_1793_p1;
wire   [9:0] add_ln820_1_fu_1797_p2;
wire  signed [10:0] sext_ln820_2_fu_1803_p1;
wire  signed [10:0] sext_ln818_1_fu_1772_p1;
wire   [10:0] sub_ln820_1_fu_1813_p2;
wire   [9:0] trunc_ln820_1_fu_1819_p4;
wire   [7:0] CH_fu_1845_p3;
wire   [0:0] tmp_5_fu_1856_p3;
wire   [9:0] trunc_ln820_2_fu_1863_p4;
wire   [9:0] zext_ln817_1_fu_1879_p1;
wire   [9:0] select_ln820_1_fu_1872_p3;
wire   [9:0] zext_ln788_fu_1852_p1;
wire   [9:0] CV_fu_1883_p2;
wire   [1:0] tmp_7_fu_1913_p4;
wire   [0:0] tmp_6_fu_1905_p3;
wire   [0:0] xor_ln827_fu_1933_p2;
wire   [0:0] icmp_ln827_fu_1923_p2;
wire   [0:0] or_ln827_fu_1947_p2;
wire   [7:0] select_ln827_1_fu_1939_p3;
wire   [7:0] trunc_ln827_fu_1929_p1;
wire   [1:0] tmp_9_fu_1969_p4;
wire   [0:0] tmp_8_fu_1961_p3;
wire   [0:0] xor_ln829_fu_1989_p2;
wire   [0:0] icmp_ln829_fu_1979_p2;
wire   [0:0] or_ln829_fu_2003_p2;
wire   [7:0] select_ln829_1_fu_1995_p3;
wire   [7:0] trunc_ln829_fu_1985_p1;
wire   [7:0] select_ln829_fu_2009_p3;
wire   [7:0] select_ln827_fu_1953_p3;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
reg    ap_block_pp0;
reg    ap_predicate_op83_load_state1;
reg    ap_enable_operation_83;
reg    ap_enable_state1_pp0_iter0_stage0;
reg    ap_predicate_op115_load_state2;
reg    ap_enable_operation_115;
reg    ap_enable_state2_pp0_iter1_stage0;
reg    ap_predicate_op127_store_state2;
reg    ap_enable_operation_127;
reg    ap_predicate_op85_load_state1;
reg    ap_enable_operation_85;
reg    ap_predicate_op119_load_state2;
reg    ap_enable_operation_119;
reg    ap_predicate_op150_store_state2;
reg    ap_enable_operation_150;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
reg    ap_condition_280;
reg    ap_condition_1476;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_block_pp0_stage0_subdone_grp0_done_reg = 1'b0;
#0 x_fu_224 = 11'd0;
#0 p_0_0_0_0_09131503_i_fu_228 = 8'd0;
#0 p_0_1_0_0_09141505_i_fu_232 = 8'd0;
#0 p_0_2_0_0_09151507_i_fu_236 = 8'd0;
#0 p_0_0_0940_114971508_i_fu_240 = 8'd0;
#0 p_0_0_0939_114991510_i_fu_244 = 8'd0;
#0 p_0_0_0938_115011512_i_fu_248 = 8'd0;
#0 p_0_0_0_0_09071515_i_fu_252 = 8'd0;
#0 p_0_1_0_0_09081517_i_fu_256 = 8'd0;
#0 p_0_2_0_0_09091519_i_fu_260 = 8'd0;
#0 p_0_0_09401404_i_fu_264 = 8'd0;
#0 p_0_0_09391407_i_fu_268 = 8'd0;
#0 p_0_0_09381410_i_fu_272 = 8'd0;
#0 p_0_0_0940_21434_i_fu_276 = 8'd0;
#0 p_0_0_0939_21437_i_fu_280 = 8'd0;
#0 p_0_0_0938_21440_i_fu_284 = 8'd0;
#0 ap_done_reg = 1'b0;
end

pcam_v_demosaic_0_0_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_lineBuffer_1_RAM_AUTO_1R1W #(
    .DataWidth( 24 ),
    .AddressRange( 1921 ),
    .AddressWidth( 11 ))
lineBuffer_1_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(lineBuffer_1_address0),
    .ce0(lineBuffer_1_ce0_local),
    .we0(lineBuffer_1_we0_local),
    .d0(LineBufVal_2_fu_1212_p4),
    .address1(lineBuffer_1_address1),
    .ce1(lineBuffer_1_ce1_local),
    .q1(lineBuffer_1_q1)
);

pcam_v_demosaic_0_0_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_lineBuffer_1_RAM_AUTO_1R1W #(
    .DataWidth( 24 ),
    .AddressRange( 1921 ),
    .AddressWidth( 11 ))
lineBuffer_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(lineBuffer_address0),
    .ce0(lineBuffer_ce0_local),
    .we0(lineBuffer_we0_local),
    .d0(imgG_dout),
    .address1(lineBuffer_address1),
    .ce1(lineBuffer_ce1_local),
    .q1(lineBuffer_q1)
);

pcam_v_demosaic_0_0_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_block_pp0_stage0_subdone_grp0_done_reg <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_block_pp0_stage0_subdone_grp0_done_reg <= 1'b0;
        end else if ((1'b0 == ap_block_pp0_stage0_subdone_grp0)) begin
            ap_block_pp0_stage0_subdone_grp0_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready_pp0_iter3_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter1_stage0)) begin
            ap_enable_reg_pp0_iter2 <= 1'b0;
        end else if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_280)) begin
        if (((icmp_ln643_reg_2247 == 1'd0) & (icmp_ln633_reg_2243 == 1'd0))) begin
            ap_phi_reg_pp0_iter2_pix_3_reg_627 <= p_0_0_0939_114991510_i_fu_244;
        end else if (((icmp_ln643_reg_2247 == 1'd1) & (icmp_ln633_reg_2243 == 1'd0))) begin
            ap_phi_reg_pp0_iter2_pix_3_reg_627 <= select_ln710_1_fu_1081_p3;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter2_pix_3_reg_627 <= ap_phi_reg_pp0_iter1_pix_3_reg_627;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_280)) begin
        if (((icmp_ln643_reg_2247 == 1'd0) & (icmp_ln633_reg_2243 == 1'd0))) begin
            ap_phi_reg_pp0_iter2_pix_4_reg_617 <= p_0_0_0938_115011512_i_fu_248;
        end else if (((icmp_ln643_reg_2247 == 1'd1) & (icmp_ln633_reg_2243 == 1'd0))) begin
            ap_phi_reg_pp0_iter2_pix_4_reg_617 <= select_ln710_2_fu_1088_p3;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter2_pix_4_reg_617 <= ap_phi_reg_pp0_iter1_pix_4_reg_617;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_280)) begin
        if (((icmp_ln643_reg_2247 == 1'd0) & (icmp_ln633_reg_2243 == 1'd0))) begin
            ap_phi_reg_pp0_iter2_pix_reg_637 <= p_0_0_0940_114971508_i_fu_240;
        end else if (((icmp_ln643_reg_2247 == 1'd1) & (icmp_ln633_reg_2243 == 1'd0))) begin
            ap_phi_reg_pp0_iter2_pix_reg_637 <= select_ln710_fu_1074_p3;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter2_pix_reg_637 <= ap_phi_reg_pp0_iter1_pix_reg_637;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            p_0_0_09381410_i_fu_272 <= p_0_0_09381411_lcssa1461_i;
        end else if (((icmp_ln633_reg_2243 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            p_0_0_09381410_i_fu_272 <= ap_phi_mux_p_0_0_09381411_i_phi_fu_593_p4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            p_0_0_0938_115011512_i_fu_248 <= p_0_0_0938_115011513_lcssa1549_i;
        end else if ((1'b1 == ap_condition_1476)) begin
            p_0_0_0938_115011512_i_fu_248 <= {{lineBuffer_q1[23:16]}};
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            p_0_0_0938_21440_i_fu_284 <= p_0_0_0938_21441_lcssa1473_i;
        end else if (((icmp_ln633_reg_2243 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            p_0_0_0938_21440_i_fu_284 <= ap_phi_mux_p_0_0_0938_21441_i_phi_fu_539_p4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            p_0_0_09391407_i_fu_268 <= p_0_0_09391408_lcssa1459_i;
        end else if (((icmp_ln633_reg_2243 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            p_0_0_09391407_i_fu_268 <= ap_phi_mux_p_0_0_09391408_i_phi_fu_602_p4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            p_0_0_0939_114991510_i_fu_244 <= p_0_0_0939_114991511_lcssa1547_i;
        end else if ((1'b1 == ap_condition_1476)) begin
            p_0_0_0939_114991510_i_fu_244 <= {{lineBuffer_q1[15:8]}};
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            p_0_0_0939_21437_i_fu_280 <= p_0_0_0939_21438_lcssa1471_i;
        end else if (((icmp_ln633_reg_2243 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            p_0_0_0939_21437_i_fu_280 <= ap_phi_mux_p_0_0_0939_21438_i_phi_fu_548_p4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            p_0_0_09401404_i_fu_264 <= p_0_0_09401405_lcssa1457_i;
        end else if (((icmp_ln633_reg_2243 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            p_0_0_09401404_i_fu_264 <= ap_phi_mux_p_0_0_09401405_i_phi_fu_611_p4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            p_0_0_0940_114971508_i_fu_240 <= p_0_0_0940_114971509_lcssa1545_i;
        end else if ((1'b1 == ap_condition_1476)) begin
            p_0_0_0940_114971508_i_fu_240 <= trunc_ln654_fu_1004_p1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            p_0_0_0940_21434_i_fu_276 <= p_0_0_0940_21435_lcssa1469_i;
        end else if (((icmp_ln633_reg_2243 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            p_0_0_0940_21434_i_fu_276 <= ap_phi_mux_p_0_0_0940_21435_i_phi_fu_557_p4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            p_0_0_0_0_09071515_i_fu_252 <= p_0_0_0_0_09071514_lcssa1551_i;
        end else if ((1'b1 == ap_condition_1476)) begin
            p_0_0_0_0_09071515_i_fu_252 <= ap_phi_mux_p_0_0_0940_21485_ph_i_phi_fu_503_p4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            p_0_0_0_0_09131503_i_fu_228 <= p_0_0_0_0_09131502_lcssa1539_i;
        end else if ((1'b1 == ap_condition_1476)) begin
            p_0_0_0_0_09131503_i_fu_228 <= trunc_ln654_1_fu_1027_p1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            p_0_1_0_0_09081517_i_fu_256 <= p_0_1_0_0_09081516_lcssa1553_i;
        end else if ((1'b1 == ap_condition_1476)) begin
            p_0_1_0_0_09081517_i_fu_256 <= ap_phi_mux_p_0_0_0939_21487_ph_i_phi_fu_494_p4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            p_0_1_0_0_09141505_i_fu_232 <= p_0_1_0_0_09141504_lcssa1541_i;
        end else if ((1'b1 == ap_condition_1476)) begin
            p_0_1_0_0_09141505_i_fu_232 <= {{lineBuffer_1_q1[15:8]}};
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            p_0_2_0_0_09091519_i_fu_260 <= p_0_2_0_0_09091518_lcssa1555_i;
        end else if ((1'b1 == ap_condition_1476)) begin
            p_0_2_0_0_09091519_i_fu_260 <= ap_phi_mux_p_0_0_0938_21489_ph_i_phi_fu_485_p4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            p_0_2_0_0_09151507_i_fu_236 <= p_0_2_0_0_09151506_lcssa1543_i;
        end else if ((1'b1 == ap_condition_1476)) begin
            p_0_2_0_0_09151507_i_fu_236 <= {{lineBuffer_1_q1[23:16]}};
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln633_fu_874_p2 == 1'd0) & (ap_start_int == 1'b1))) begin
            x_fu_224 <= x_5_fu_880_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            x_fu_224 <= 11'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        add_ln820_reg_2428 <= add_ln820_fu_1807_p2;
        and_ln833_reg_2286_pp0_iter2_reg <= and_ln833_reg_2286_pp0_iter1_reg;
        and_ln833_reg_2286_pp0_iter3_reg <= and_ln833_reg_2286_pp0_iter2_reg;
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        enable_6_reg_2403 <= enable_6_fu_1586_p3;
        icmp_ln633_reg_2243_pp0_iter2_reg <= icmp_ln633_reg_2243_pp0_iter1_reg;
        icmp_ln633_reg_2243_pp0_iter3_reg <= icmp_ln633_reg_2243_pp0_iter2_reg;
        icmp_ln772_reg_2282_pp0_iter2_reg <= icmp_ln772_reg_2282_pp0_iter1_reg;
        icmp_ln772_reg_2282_pp0_iter3_reg <= icmp_ln772_reg_2282_pp0_iter2_reg;
        icmp_ln800_reg_2409 <= icmp_ln800_fu_1594_p2;
        p_0_0_09381410_i_load_reg_2348_pp0_iter2_reg <= p_0_0_09381410_i_load_reg_2348;
        p_0_0_0938_115011512_i_load_reg_2317_pp0_iter2_reg <= p_0_0_0938_115011512_i_load_reg_2317;
        p_0_0_0938_21440_i_load_reg_2363_pp0_iter2_reg <= p_0_0_0938_21440_i_load_reg_2363;
        p_0_0_09391407_i_load_reg_2343_pp0_iter2_reg <= p_0_0_09391407_i_load_reg_2343;
        p_0_0_0939_114991510_i_load_reg_2311_pp0_iter2_reg <= p_0_0_0939_114991510_i_load_reg_2311;
        p_0_0_0939_21437_i_load_reg_2358_pp0_iter2_reg <= p_0_0_0939_21437_i_load_reg_2358;
        p_0_0_09401404_i_load_reg_2338_pp0_iter2_reg <= p_0_0_09401404_i_load_reg_2338;
        p_0_0_0940_114971508_i_load_reg_2305_pp0_iter2_reg <= p_0_0_0940_114971508_i_load_reg_2305;
        p_0_0_0940_21434_i_load_reg_2353_pp0_iter2_reg <= p_0_0_0940_21434_i_load_reg_2353;
        p_0_0_0_0_09071515_i_load_reg_2323_pp0_iter2_reg <= p_0_0_0_0_09071515_i_load_reg_2323;
        p_0_0_0_0_09131503_i_load_reg_2290_pp0_iter2_reg <= p_0_0_0_0_09131503_i_load_reg_2290;
        p_0_1_0_0_09081517_i_load_reg_2328_pp0_iter2_reg <= p_0_1_0_0_09081517_i_load_reg_2328;
        p_0_1_0_0_09141505_i_load_reg_2295_pp0_iter2_reg <= p_0_1_0_0_09141505_i_load_reg_2295;
        p_0_2_0_0_09091519_i_load_reg_2333_pp0_iter2_reg <= p_0_2_0_0_09091519_i_load_reg_2333;
        p_0_2_0_0_09151507_i_load_reg_2300_pp0_iter2_reg <= p_0_2_0_0_09151507_i_load_reg_2300;
        pix_3_reg_627_pp0_iter3_reg <= pix_3_reg_627;
        pix_4_reg_617_pp0_iter3_reg <= pix_4_reg_617;
        pix_reg_637_pp0_iter3_reg <= pix_reg_637;
        sub_ln817_reg_2393_pp0_iter2_reg <= sub_ln817_reg_2393;
        sub_ln818_reg_2398_pp0_iter2_reg <= sub_ln818_reg_2398;
        sub_ln819_reg_2414 <= sub_ln819_fu_1623_p2;
        sub_ln820_2_reg_2434 <= sub_ln820_2_fu_1829_p2;
        sub_ln820_reg_2419 <= sub_ln820_fu_1640_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        and_ln833_reg_2286 <= and_ln833_fu_936_p2;
        and_ln833_reg_2286_pp0_iter1_reg <= and_ln833_reg_2286;
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        icmp_ln633_reg_2243 <= icmp_ln633_fu_874_p2;
        icmp_ln633_reg_2243_pp0_iter1_reg <= icmp_ln633_reg_2243;
        icmp_ln643_reg_2247 <= icmp_ln643_fu_896_p2;
        icmp_ln664_reg_2232 <= icmp_ln664_fu_779_p2;
        icmp_ln710_reg_2263 <= icmp_ln710_fu_902_p2;
        icmp_ln728_reg_2236 <= icmp_ln728_fu_785_p2;
        icmp_ln772_reg_2282 <= icmp_ln772_fu_924_p2;
        icmp_ln772_reg_2282_pp0_iter1_reg <= icmp_ln772_reg_2282;
        lineBuffer_1_addr_reg_2257 <= zext_ln633_fu_890_p1;
        lineBuffer_addr_reg_2251 <= zext_ln633_fu_890_p1;
        red_reg_2221 <= red_fu_773_p2;
        sub_ln817_reg_2393 <= sub_ln817_fu_1287_p2;
        sub_ln818_reg_2398 <= sub_ln818_fu_1304_p2;
        zext_ln790_1_reg_2383[7 : 0] <= zext_ln790_1_fu_1268_p1[7 : 0];
        zext_ln791_reg_2388[7 : 0] <= zext_ln791_fu_1272_p1[7 : 0];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_phi_reg_pp0_iter1_pix_3_reg_627 <= ap_phi_reg_pp0_iter0_pix_3_reg_627;
        ap_phi_reg_pp0_iter1_pix_4_reg_617 <= ap_phi_reg_pp0_iter0_pix_4_reg_617;
        ap_phi_reg_pp0_iter1_pix_reg_637 <= ap_phi_reg_pp0_iter0_pix_reg_637;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_0_0_09381410_i_load_reg_2348 <= p_0_0_09381410_i_fu_272;
        p_0_0_0938_115011512_i_load_reg_2317 <= p_0_0_0938_115011512_i_fu_248;
        p_0_0_0938_21440_i_load_reg_2363 <= p_0_0_0938_21440_i_fu_284;
        p_0_0_09391407_i_load_reg_2343 <= p_0_0_09391407_i_fu_268;
        p_0_0_0939_114991510_i_load_reg_2311 <= p_0_0_0939_114991510_i_fu_244;
        p_0_0_0939_21437_i_load_reg_2358 <= p_0_0_0939_21437_i_fu_280;
        p_0_0_09401404_i_load_reg_2338 <= p_0_0_09401404_i_fu_264;
        p_0_0_0940_114971508_i_load_reg_2305 <= p_0_0_0940_114971508_i_fu_240;
        p_0_0_0940_21434_i_load_reg_2353 <= p_0_0_0940_21434_i_fu_276;
        p_0_0_0_0_09071515_i_load_reg_2323 <= p_0_0_0_0_09071515_i_fu_252;
        p_0_0_0_0_09131503_i_load_reg_2290 <= p_0_0_0_0_09131503_i_fu_228;
        p_0_1_0_0_09081517_i_load_reg_2328 <= p_0_1_0_0_09081517_i_fu_256;
        p_0_1_0_0_09141505_i_load_reg_2295 <= p_0_1_0_0_09141505_i_fu_232;
        p_0_2_0_0_09091519_i_load_reg_2333 <= p_0_2_0_0_09091519_i_fu_260;
        p_0_2_0_0_09151507_i_load_reg_2300 <= p_0_2_0_0_09151507_i_fu_236;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        pix_3_reg_627 <= ap_phi_reg_pp0_iter2_pix_3_reg_627;
        pix_4_reg_617 <= ap_phi_reg_pp0_iter2_pix_4_reg_617;
        pix_reg_637 <= ap_phi_reg_pp0_iter2_pix_reg_637;
    end
end

always @ (*) begin
    if (((icmp_ln633_fu_874_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (icmp_ln633_reg_2243 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter3_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_start_int == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if ((icmp_ln633_reg_2243_pp0_iter3_reg == 1'd0)) begin
        if ((icmp_ln772_reg_2282_pp0_iter3_reg == 1'd0)) begin
            ap_phi_mux_b_1_phi_fu_763_p4 = zext_ln765_fu_1840_p1;
        end else if ((icmp_ln772_reg_2282_pp0_iter3_reg == 1'd1)) begin
            ap_phi_mux_b_1_phi_fu_763_p4 = b_fu_1897_p3;
        end else begin
            ap_phi_mux_b_1_phi_fu_763_p4 = ap_phi_reg_pp0_iter4_b_1_reg_760;
        end
    end else begin
        ap_phi_mux_b_1_phi_fu_763_p4 = ap_phi_reg_pp0_iter4_b_1_reg_760;
    end
end

always @ (*) begin
    if ((icmp_ln633_reg_2243 == 1'd0)) begin
        if ((icmp_ln643_reg_2247 == 1'd0)) begin
            ap_phi_mux_downleft_1_phi_fu_521_p4 = p_0_0_0939_21437_i_fu_280;
        end else if ((icmp_ln643_reg_2247 == 1'd1)) begin
            ap_phi_mux_downleft_1_phi_fu_521_p4 = select_ln710_10_fu_1151_p3;
        end else begin
            ap_phi_mux_downleft_1_phi_fu_521_p4 = ap_phi_reg_pp0_iter1_downleft_1_reg_518;
        end
    end else begin
        ap_phi_mux_downleft_1_phi_fu_521_p4 = ap_phi_reg_pp0_iter1_downleft_1_reg_518;
    end
end

always @ (*) begin
    if ((icmp_ln633_reg_2243 == 1'd0)) begin
        if ((icmp_ln643_reg_2247 == 1'd0)) begin
            ap_phi_mux_downleft_2_phi_fu_512_p4 = p_0_0_0938_21440_i_fu_284;
        end else if ((icmp_ln643_reg_2247 == 1'd1)) begin
            ap_phi_mux_downleft_2_phi_fu_512_p4 = select_ln710_9_fu_1143_p3;
        end else begin
            ap_phi_mux_downleft_2_phi_fu_512_p4 = ap_phi_reg_pp0_iter1_downleft_2_reg_509;
        end
    end else begin
        ap_phi_mux_downleft_2_phi_fu_512_p4 = ap_phi_reg_pp0_iter1_downleft_2_reg_509;
    end
end

always @ (*) begin
    if ((icmp_ln633_reg_2243 == 1'd0)) begin
        if ((icmp_ln643_reg_2247 == 1'd0)) begin
            ap_phi_mux_downleft_phi_fu_530_p4 = p_0_0_0940_21434_i_fu_276;
        end else if ((icmp_ln643_reg_2247 == 1'd1)) begin
            ap_phi_mux_downleft_phi_fu_530_p4 = select_ln710_11_fu_1159_p3;
        end else begin
            ap_phi_mux_downleft_phi_fu_530_p4 = ap_phi_reg_pp0_iter1_downleft_reg_527;
        end
    end else begin
        ap_phi_mux_downleft_phi_fu_530_p4 = ap_phi_reg_pp0_iter1_downleft_reg_527;
    end
end

always @ (*) begin
    if ((((enable_7_fu_1656_p3 == 6'd26) & (icmp_ln772_reg_2282_pp0_iter2_reg == 1'd1) & (icmp_ln633_reg_2243_pp0_iter2_reg == 1'd0)) | ((enable_7_fu_1656_p3 == 6'd24) & (icmp_ln772_reg_2282_pp0_iter2_reg == 1'd1) & (icmp_ln633_reg_2243_pp0_iter2_reg == 1'd0)) | ((enable_7_fu_1656_p3 == 6'd10) & (icmp_ln772_reg_2282_pp0_iter2_reg == 1'd1) & (icmp_ln633_reg_2243_pp0_iter2_reg == 1'd0)) | ((enable_7_fu_1656_p3 == 6'd8) & (icmp_ln772_reg_2282_pp0_iter2_reg == 1'd1) & (icmp_ln633_reg_2243_pp0_iter2_reg == 1'd0)) | ((enable_7_fu_1656_p3 == 6'd60) & (icmp_ln772_reg_2282_pp0_iter2_reg == 1'd1) & (icmp_ln633_reg_2243_pp0_iter2_reg == 1'd0)) | ((enable_7_fu_1656_p3 == 6'd56) & (icmp_ln772_reg_2282_pp0_iter2_reg == 1'd1) & (icmp_ln633_reg_2243_pp0_iter2_reg == 1'd0)) | ((enable_7_fu_1656_p3 == 6'd52) & (icmp_ln772_reg_2282_pp0_iter2_reg == 1'd1) & (icmp_ln633_reg_2243_pp0_iter2_reg == 1'd0)) | ((enable_7_fu_1656_p3 == 6'd48) & (icmp_ln772_reg_2282_pp0_iter2_reg == 1'd1) & (icmp_ln633_reg_2243_pp0_iter2_reg == 1'd0)) | ((enable_7_fu_1656_p3 
    == 6'd63) & (icmp_ln772_reg_2282_pp0_iter2_reg == 1'd1) & (icmp_ln633_reg_2243_pp0_iter2_reg == 1'd0)) | ((enable_7_fu_1656_p3 == 6'd62) & (icmp_ln772_reg_2282_pp0_iter2_reg == 1'd1) & (icmp_ln633_reg_2243_pp0_iter2_reg == 1'd0)) | ((enable_7_fu_1656_p3 == 6'd31) & (icmp_ln772_reg_2282_pp0_iter2_reg == 1'd1) & (icmp_ln633_reg_2243_pp0_iter2_reg == 1'd0)) | ((enable_7_fu_1656_p3 == 6'd30) & (icmp_ln772_reg_2282_pp0_iter2_reg == 1'd1) & (icmp_ln633_reg_2243_pp0_iter2_reg == 1'd0)))) begin
        ap_phi_mux_en_rgd_1_phi_fu_702_p14 = 1'd1;
    end else if (((~(enable_7_fu_1656_p3 == 6'd33) & ~(enable_7_fu_1656_p3 == 6'd32) & ~(enable_7_fu_1656_p3 == 6'd1) & ~(enable_7_fu_1656_p3 == 6'd0) & ~(enable_7_fu_1656_p3 == 6'd26) & ~(enable_7_fu_1656_p3 == 6'd24) & ~(enable_7_fu_1656_p3 == 6'd10) & ~(enable_7_fu_1656_p3 == 6'd8) & ~(enable_7_fu_1656_p3 == 6'd60) & ~(enable_7_fu_1656_p3 == 6'd56) & ~(enable_7_fu_1656_p3 == 6'd52) & ~(enable_7_fu_1656_p3 == 6'd48) & ~(enable_7_fu_1656_p3 == 6'd15) & ~(enable_7_fu_1656_p3 == 6'd11) & ~(enable_7_fu_1656_p3 == 6'd7) & ~(enable_7_fu_1656_p3 == 6'd3) & ~(enable_7_fu_1656_p3 == 6'd55) & ~(enable_7_fu_1656_p3 == 6'd53) & ~(enable_7_fu_1656_p3 == 6'd39) & ~(enable_7_fu_1656_p3 == 6'd37) & ~(enable_7_fu_1656_p3 == 6'd63) & ~(enable_7_fu_1656_p3 == 6'd62) & ~(enable_7_fu_1656_p3 == 6'd31) & ~(enable_7_fu_1656_p3 == 6'd30) & (icmp_ln772_reg_2282_pp0_iter2_reg == 1'd1) & (icmp_ln633_reg_2243_pp0_iter2_reg == 1'd0)) | ((enable_7_fu_1656_p3 == 6'd33) & (icmp_ln772_reg_2282_pp0_iter2_reg == 1'd1) & (icmp_ln633_reg_2243_pp0_iter2_reg == 1'd0)) 
    | ((enable_7_fu_1656_p3 == 6'd32) & (icmp_ln772_reg_2282_pp0_iter2_reg == 1'd1) & (icmp_ln633_reg_2243_pp0_iter2_reg == 1'd0)) | ((enable_7_fu_1656_p3 == 6'd1) & (icmp_ln772_reg_2282_pp0_iter2_reg == 1'd1) & (icmp_ln633_reg_2243_pp0_iter2_reg == 1'd0)) | ((enable_7_fu_1656_p3 == 6'd0) & (icmp_ln772_reg_2282_pp0_iter2_reg == 1'd1) & (icmp_ln633_reg_2243_pp0_iter2_reg == 1'd0)) | ((enable_7_fu_1656_p3 == 6'd15) & (icmp_ln772_reg_2282_pp0_iter2_reg == 1'd1) & (icmp_ln633_reg_2243_pp0_iter2_reg == 1'd0)) | ((enable_7_fu_1656_p3 == 6'd11) & (icmp_ln772_reg_2282_pp0_iter2_reg == 1'd1) & (icmp_ln633_reg_2243_pp0_iter2_reg == 1'd0)) | ((enable_7_fu_1656_p3 == 6'd7) & (icmp_ln772_reg_2282_pp0_iter2_reg == 1'd1) & (icmp_ln633_reg_2243_pp0_iter2_reg == 1'd0)) | ((enable_7_fu_1656_p3 == 6'd3) & (icmp_ln772_reg_2282_pp0_iter2_reg == 1'd1) & (icmp_ln633_reg_2243_pp0_iter2_reg == 1'd0)) | ((enable_7_fu_1656_p3 == 6'd55) & (icmp_ln772_reg_2282_pp0_iter2_reg == 1'd1) & (icmp_ln633_reg_2243_pp0_iter2_reg == 1'd0)) | ((enable_7_fu_1656_p3 
    == 6'd53) & (icmp_ln772_reg_2282_pp0_iter2_reg == 1'd1) & (icmp_ln633_reg_2243_pp0_iter2_reg == 1'd0)) | ((enable_7_fu_1656_p3 == 6'd39) & (icmp_ln772_reg_2282_pp0_iter2_reg == 1'd1) & (icmp_ln633_reg_2243_pp0_iter2_reg == 1'd0)) | ((enable_7_fu_1656_p3 == 6'd37) & (icmp_ln772_reg_2282_pp0_iter2_reg == 1'd1) & (icmp_ln633_reg_2243_pp0_iter2_reg == 1'd0)))) begin
        ap_phi_mux_en_rgd_1_phi_fu_702_p14 = 1'd0;
    end else begin
        ap_phi_mux_en_rgd_1_phi_fu_702_p14 = ap_phi_reg_pp0_iter3_en_rgd_1_reg_699;
    end
end

always @ (*) begin
    if ((((enable_7_fu_1656_p3 == 6'd33) & (icmp_ln772_reg_2282_pp0_iter2_reg == 1'd1) & (icmp_ln633_reg_2243_pp0_iter2_reg == 1'd0)) | ((enable_7_fu_1656_p3 == 6'd32) & (icmp_ln772_reg_2282_pp0_iter2_reg == 1'd1) & (icmp_ln633_reg_2243_pp0_iter2_reg == 1'd0)) | ((enable_7_fu_1656_p3 == 6'd1) & (icmp_ln772_reg_2282_pp0_iter2_reg == 1'd1) & (icmp_ln633_reg_2243_pp0_iter2_reg == 1'd0)) | ((enable_7_fu_1656_p3 == 6'd0) & (icmp_ln772_reg_2282_pp0_iter2_reg == 1'd1) & (icmp_ln633_reg_2243_pp0_iter2_reg == 1'd0)) | ((enable_7_fu_1656_p3 == 6'd60) & (icmp_ln772_reg_2282_pp0_iter2_reg == 1'd1) & (icmp_ln633_reg_2243_pp0_iter2_reg == 1'd0)) | ((enable_7_fu_1656_p3 == 6'd56) & (icmp_ln772_reg_2282_pp0_iter2_reg == 1'd1) & (icmp_ln633_reg_2243_pp0_iter2_reg == 1'd0)) | ((enable_7_fu_1656_p3 == 6'd52) & (icmp_ln772_reg_2282_pp0_iter2_reg == 1'd1) & (icmp_ln633_reg_2243_pp0_iter2_reg == 1'd0)) | ((enable_7_fu_1656_p3 == 6'd48) & (icmp_ln772_reg_2282_pp0_iter2_reg == 1'd1) & (icmp_ln633_reg_2243_pp0_iter2_reg == 1'd0)) | ((enable_7_fu_1656_p3 
    == 6'd55) & (icmp_ln772_reg_2282_pp0_iter2_reg == 1'd1) & (icmp_ln633_reg_2243_pp0_iter2_reg == 1'd0)) | ((enable_7_fu_1656_p3 == 6'd53) & (icmp_ln772_reg_2282_pp0_iter2_reg == 1'd1) & (icmp_ln633_reg_2243_pp0_iter2_reg == 1'd0)) | ((enable_7_fu_1656_p3 == 6'd39) & (icmp_ln772_reg_2282_pp0_iter2_reg == 1'd1) & (icmp_ln633_reg_2243_pp0_iter2_reg == 1'd0)) | ((enable_7_fu_1656_p3 == 6'd37) & (icmp_ln772_reg_2282_pp0_iter2_reg == 1'd1) & (icmp_ln633_reg_2243_pp0_iter2_reg == 1'd0)))) begin
        ap_phi_mux_en_rgd_2_phi_fu_676_p14 = 1'd1;
    end else if (((~(enable_7_fu_1656_p3 == 6'd33) & ~(enable_7_fu_1656_p3 == 6'd32) & ~(enable_7_fu_1656_p3 == 6'd1) & ~(enable_7_fu_1656_p3 == 6'd0) & ~(enable_7_fu_1656_p3 == 6'd26) & ~(enable_7_fu_1656_p3 == 6'd24) & ~(enable_7_fu_1656_p3 == 6'd10) & ~(enable_7_fu_1656_p3 == 6'd8) & ~(enable_7_fu_1656_p3 == 6'd60) & ~(enable_7_fu_1656_p3 == 6'd56) & ~(enable_7_fu_1656_p3 == 6'd52) & ~(enable_7_fu_1656_p3 == 6'd48) & ~(enable_7_fu_1656_p3 == 6'd15) & ~(enable_7_fu_1656_p3 == 6'd11) & ~(enable_7_fu_1656_p3 == 6'd7) & ~(enable_7_fu_1656_p3 == 6'd3) & ~(enable_7_fu_1656_p3 == 6'd55) & ~(enable_7_fu_1656_p3 == 6'd53) & ~(enable_7_fu_1656_p3 == 6'd39) & ~(enable_7_fu_1656_p3 == 6'd37) & ~(enable_7_fu_1656_p3 == 6'd63) & ~(enable_7_fu_1656_p3 == 6'd62) & ~(enable_7_fu_1656_p3 == 6'd31) & ~(enable_7_fu_1656_p3 == 6'd30) & (icmp_ln772_reg_2282_pp0_iter2_reg == 1'd1) & (icmp_ln633_reg_2243_pp0_iter2_reg == 1'd0)) | ((enable_7_fu_1656_p3 == 6'd26) & (icmp_ln772_reg_2282_pp0_iter2_reg == 1'd1) & (icmp_ln633_reg_2243_pp0_iter2_reg == 1'd0)) 
    | ((enable_7_fu_1656_p3 == 6'd24) & (icmp_ln772_reg_2282_pp0_iter2_reg == 1'd1) & (icmp_ln633_reg_2243_pp0_iter2_reg == 1'd0)) | ((enable_7_fu_1656_p3 == 6'd10) & (icmp_ln772_reg_2282_pp0_iter2_reg == 1'd1) & (icmp_ln633_reg_2243_pp0_iter2_reg == 1'd0)) | ((enable_7_fu_1656_p3 == 6'd8) & (icmp_ln772_reg_2282_pp0_iter2_reg == 1'd1) & (icmp_ln633_reg_2243_pp0_iter2_reg == 1'd0)) | ((enable_7_fu_1656_p3 == 6'd15) & (icmp_ln772_reg_2282_pp0_iter2_reg == 1'd1) & (icmp_ln633_reg_2243_pp0_iter2_reg == 1'd0)) | ((enable_7_fu_1656_p3 == 6'd11) & (icmp_ln772_reg_2282_pp0_iter2_reg == 1'd1) & (icmp_ln633_reg_2243_pp0_iter2_reg == 1'd0)) | ((enable_7_fu_1656_p3 == 6'd7) & (icmp_ln772_reg_2282_pp0_iter2_reg == 1'd1) & (icmp_ln633_reg_2243_pp0_iter2_reg == 1'd0)) | ((enable_7_fu_1656_p3 == 6'd3) & (icmp_ln772_reg_2282_pp0_iter2_reg == 1'd1) & (icmp_ln633_reg_2243_pp0_iter2_reg == 1'd0)) | ((enable_7_fu_1656_p3 == 6'd63) & (icmp_ln772_reg_2282_pp0_iter2_reg == 1'd1) & (icmp_ln633_reg_2243_pp0_iter2_reg == 1'd0)) | ((enable_7_fu_1656_p3 
    == 6'd62) & (icmp_ln772_reg_2282_pp0_iter2_reg == 1'd1) & (icmp_ln633_reg_2243_pp0_iter2_reg == 1'd0)) | ((enable_7_fu_1656_p3 == 6'd31) & (icmp_ln772_reg_2282_pp0_iter2_reg == 1'd1) & (icmp_ln633_reg_2243_pp0_iter2_reg == 1'd0)) | ((enable_7_fu_1656_p3 == 6'd30) & (icmp_ln772_reg_2282_pp0_iter2_reg == 1'd1) & (icmp_ln633_reg_2243_pp0_iter2_reg == 1'd0)))) begin
        ap_phi_mux_en_rgd_2_phi_fu_676_p14 = 1'd0;
    end else begin
        ap_phi_mux_en_rgd_2_phi_fu_676_p14 = ap_phi_reg_pp0_iter3_en_rgd_2_reg_673;
    end
end

always @ (*) begin
    if ((((enable_7_fu_1656_p3 == 6'd33) & (icmp_ln772_reg_2282_pp0_iter2_reg == 1'd1) & (icmp_ln633_reg_2243_pp0_iter2_reg == 1'd0)) | ((enable_7_fu_1656_p3 == 6'd32) & (icmp_ln772_reg_2282_pp0_iter2_reg == 1'd1) & (icmp_ln633_reg_2243_pp0_iter2_reg == 1'd0)) | ((enable_7_fu_1656_p3 == 6'd1) & (icmp_ln772_reg_2282_pp0_iter2_reg == 1'd1) & (icmp_ln633_reg_2243_pp0_iter2_reg == 1'd0)) | ((enable_7_fu_1656_p3 == 6'd0) & (icmp_ln772_reg_2282_pp0_iter2_reg == 1'd1) & (icmp_ln633_reg_2243_pp0_iter2_reg == 1'd0)) | ((enable_7_fu_1656_p3 == 6'd26) & (icmp_ln772_reg_2282_pp0_iter2_reg == 1'd1) & (icmp_ln633_reg_2243_pp0_iter2_reg == 1'd0)) | ((enable_7_fu_1656_p3 == 6'd24) & (icmp_ln772_reg_2282_pp0_iter2_reg == 1'd1) & (icmp_ln633_reg_2243_pp0_iter2_reg == 1'd0)) | ((enable_7_fu_1656_p3 == 6'd10) & (icmp_ln772_reg_2282_pp0_iter2_reg == 1'd1) & (icmp_ln633_reg_2243_pp0_iter2_reg == 1'd0)) | ((enable_7_fu_1656_p3 == 6'd8) & (icmp_ln772_reg_2282_pp0_iter2_reg == 1'd1) & (icmp_ln633_reg_2243_pp0_iter2_reg == 1'd0)) | ((enable_7_fu_1656_p3 
    == 6'd15) & (icmp_ln772_reg_2282_pp0_iter2_reg == 1'd1) & (icmp_ln633_reg_2243_pp0_iter2_reg == 1'd0)) | ((enable_7_fu_1656_p3 == 6'd11) & (icmp_ln772_reg_2282_pp0_iter2_reg == 1'd1) & (icmp_ln633_reg_2243_pp0_iter2_reg == 1'd0)) | ((enable_7_fu_1656_p3 == 6'd7) & (icmp_ln772_reg_2282_pp0_iter2_reg == 1'd1) & (icmp_ln633_reg_2243_pp0_iter2_reg == 1'd0)) | ((enable_7_fu_1656_p3 == 6'd3) & (icmp_ln772_reg_2282_pp0_iter2_reg == 1'd1) & (icmp_ln633_reg_2243_pp0_iter2_reg == 1'd0)))) begin
        ap_phi_mux_en_rgd_3_phi_fu_650_p14 = 1'd1;
    end else if (((~(enable_7_fu_1656_p3 == 6'd33) & ~(enable_7_fu_1656_p3 == 6'd32) & ~(enable_7_fu_1656_p3 == 6'd1) & ~(enable_7_fu_1656_p3 == 6'd0) & ~(enable_7_fu_1656_p3 == 6'd26) & ~(enable_7_fu_1656_p3 == 6'd24) & ~(enable_7_fu_1656_p3 == 6'd10) & ~(enable_7_fu_1656_p3 == 6'd8) & ~(enable_7_fu_1656_p3 == 6'd60) & ~(enable_7_fu_1656_p3 == 6'd56) & ~(enable_7_fu_1656_p3 == 6'd52) & ~(enable_7_fu_1656_p3 == 6'd48) & ~(enable_7_fu_1656_p3 == 6'd15) & ~(enable_7_fu_1656_p3 == 6'd11) & ~(enable_7_fu_1656_p3 == 6'd7) & ~(enable_7_fu_1656_p3 == 6'd3) & ~(enable_7_fu_1656_p3 == 6'd55) & ~(enable_7_fu_1656_p3 == 6'd53) & ~(enable_7_fu_1656_p3 == 6'd39) & ~(enable_7_fu_1656_p3 == 6'd37) & ~(enable_7_fu_1656_p3 == 6'd63) & ~(enable_7_fu_1656_p3 == 6'd62) & ~(enable_7_fu_1656_p3 == 6'd31) & ~(enable_7_fu_1656_p3 == 6'd30) & (icmp_ln772_reg_2282_pp0_iter2_reg == 1'd1) & (icmp_ln633_reg_2243_pp0_iter2_reg == 1'd0)) | ((enable_7_fu_1656_p3 == 6'd60) & (icmp_ln772_reg_2282_pp0_iter2_reg == 1'd1) & (icmp_ln633_reg_2243_pp0_iter2_reg == 1'd0)) 
    | ((enable_7_fu_1656_p3 == 6'd56) & (icmp_ln772_reg_2282_pp0_iter2_reg == 1'd1) & (icmp_ln633_reg_2243_pp0_iter2_reg == 1'd0)) | ((enable_7_fu_1656_p3 == 6'd52) & (icmp_ln772_reg_2282_pp0_iter2_reg == 1'd1) & (icmp_ln633_reg_2243_pp0_iter2_reg == 1'd0)) | ((enable_7_fu_1656_p3 == 6'd48) & (icmp_ln772_reg_2282_pp0_iter2_reg == 1'd1) & (icmp_ln633_reg_2243_pp0_iter2_reg == 1'd0)) | ((enable_7_fu_1656_p3 == 6'd55) & (icmp_ln772_reg_2282_pp0_iter2_reg == 1'd1) & (icmp_ln633_reg_2243_pp0_iter2_reg == 1'd0)) | ((enable_7_fu_1656_p3 == 6'd53) & (icmp_ln772_reg_2282_pp0_iter2_reg == 1'd1) & (icmp_ln633_reg_2243_pp0_iter2_reg == 1'd0)) | ((enable_7_fu_1656_p3 == 6'd39) & (icmp_ln772_reg_2282_pp0_iter2_reg == 1'd1) & (icmp_ln633_reg_2243_pp0_iter2_reg == 1'd0)) | ((enable_7_fu_1656_p3 == 6'd37) & (icmp_ln772_reg_2282_pp0_iter2_reg == 1'd1) & (icmp_ln633_reg_2243_pp0_iter2_reg == 1'd0)) | ((enable_7_fu_1656_p3 == 6'd63) & (icmp_ln772_reg_2282_pp0_iter2_reg == 1'd1) & (icmp_ln633_reg_2243_pp0_iter2_reg == 1'd0)) | ((enable_7_fu_1656_p3 
    == 6'd62) & (icmp_ln772_reg_2282_pp0_iter2_reg == 1'd1) & (icmp_ln633_reg_2243_pp0_iter2_reg == 1'd0)) | ((enable_7_fu_1656_p3 == 6'd31) & (icmp_ln772_reg_2282_pp0_iter2_reg == 1'd1) & (icmp_ln633_reg_2243_pp0_iter2_reg == 1'd0)) | ((enable_7_fu_1656_p3 == 6'd30) & (icmp_ln772_reg_2282_pp0_iter2_reg == 1'd1) & (icmp_ln633_reg_2243_pp0_iter2_reg == 1'd0)))) begin
        ap_phi_mux_en_rgd_3_phi_fu_650_p14 = 1'd0;
    end else begin
        ap_phi_mux_en_rgd_3_phi_fu_650_p14 = ap_phi_reg_pp0_iter3_en_rgd_3_reg_647;
    end
end

always @ (*) begin
    if ((((enable_7_fu_1656_p3 == 6'd15) & (icmp_ln772_reg_2282_pp0_iter2_reg == 1'd1) & (icmp_ln633_reg_2243_pp0_iter2_reg == 1'd0)) | ((enable_7_fu_1656_p3 == 6'd11) & (icmp_ln772_reg_2282_pp0_iter2_reg == 1'd1) & (icmp_ln633_reg_2243_pp0_iter2_reg == 1'd0)) | ((enable_7_fu_1656_p3 == 6'd7) & (icmp_ln772_reg_2282_pp0_iter2_reg == 1'd1) & (icmp_ln633_reg_2243_pp0_iter2_reg == 1'd0)) | ((enable_7_fu_1656_p3 == 6'd3) & (icmp_ln772_reg_2282_pp0_iter2_reg == 1'd1) & (icmp_ln633_reg_2243_pp0_iter2_reg == 1'd0)) | ((enable_7_fu_1656_p3 == 6'd55) & (icmp_ln772_reg_2282_pp0_iter2_reg == 1'd1) & (icmp_ln633_reg_2243_pp0_iter2_reg == 1'd0)) | ((enable_7_fu_1656_p3 == 6'd53) & (icmp_ln772_reg_2282_pp0_iter2_reg == 1'd1) & (icmp_ln633_reg_2243_pp0_iter2_reg == 1'd0)) | ((enable_7_fu_1656_p3 == 6'd39) & (icmp_ln772_reg_2282_pp0_iter2_reg == 1'd1) & (icmp_ln633_reg_2243_pp0_iter2_reg == 1'd0)) | ((enable_7_fu_1656_p3 == 6'd37) & (icmp_ln772_reg_2282_pp0_iter2_reg == 1'd1) & (icmp_ln633_reg_2243_pp0_iter2_reg == 1'd0)) | ((enable_7_fu_1656_p3 
    == 6'd63) & (icmp_ln772_reg_2282_pp0_iter2_reg == 1'd1) & (icmp_ln633_reg_2243_pp0_iter2_reg == 1'd0)) | ((enable_7_fu_1656_p3 == 6'd62) & (icmp_ln772_reg_2282_pp0_iter2_reg == 1'd1) & (icmp_ln633_reg_2243_pp0_iter2_reg == 1'd0)) | ((enable_7_fu_1656_p3 == 6'd31) & (icmp_ln772_reg_2282_pp0_iter2_reg == 1'd1) & (icmp_ln633_reg_2243_pp0_iter2_reg == 1'd0)) | ((enable_7_fu_1656_p3 == 6'd30) & (icmp_ln772_reg_2282_pp0_iter2_reg == 1'd1) & (icmp_ln633_reg_2243_pp0_iter2_reg == 1'd0)))) begin
        ap_phi_mux_en_rgd_phi_fu_728_p14 = 1'd1;
    end else if (((~(enable_7_fu_1656_p3 == 6'd33) & ~(enable_7_fu_1656_p3 == 6'd32) & ~(enable_7_fu_1656_p3 == 6'd1) & ~(enable_7_fu_1656_p3 == 6'd0) & ~(enable_7_fu_1656_p3 == 6'd26) & ~(enable_7_fu_1656_p3 == 6'd24) & ~(enable_7_fu_1656_p3 == 6'd10) & ~(enable_7_fu_1656_p3 == 6'd8) & ~(enable_7_fu_1656_p3 == 6'd60) & ~(enable_7_fu_1656_p3 == 6'd56) & ~(enable_7_fu_1656_p3 == 6'd52) & ~(enable_7_fu_1656_p3 == 6'd48) & ~(enable_7_fu_1656_p3 == 6'd15) & ~(enable_7_fu_1656_p3 == 6'd11) & ~(enable_7_fu_1656_p3 == 6'd7) & ~(enable_7_fu_1656_p3 == 6'd3) & ~(enable_7_fu_1656_p3 == 6'd55) & ~(enable_7_fu_1656_p3 == 6'd53) & ~(enable_7_fu_1656_p3 == 6'd39) & ~(enable_7_fu_1656_p3 == 6'd37) & ~(enable_7_fu_1656_p3 == 6'd63) & ~(enable_7_fu_1656_p3 == 6'd62) & ~(enable_7_fu_1656_p3 == 6'd31) & ~(enable_7_fu_1656_p3 == 6'd30) & (icmp_ln772_reg_2282_pp0_iter2_reg == 1'd1) & (icmp_ln633_reg_2243_pp0_iter2_reg == 1'd0)) | ((enable_7_fu_1656_p3 == 6'd33) & (icmp_ln772_reg_2282_pp0_iter2_reg == 1'd1) & (icmp_ln633_reg_2243_pp0_iter2_reg == 1'd0)) 
    | ((enable_7_fu_1656_p3 == 6'd32) & (icmp_ln772_reg_2282_pp0_iter2_reg == 1'd1) & (icmp_ln633_reg_2243_pp0_iter2_reg == 1'd0)) | ((enable_7_fu_1656_p3 == 6'd1) & (icmp_ln772_reg_2282_pp0_iter2_reg == 1'd1) & (icmp_ln633_reg_2243_pp0_iter2_reg == 1'd0)) | ((enable_7_fu_1656_p3 == 6'd0) & (icmp_ln772_reg_2282_pp0_iter2_reg == 1'd1) & (icmp_ln633_reg_2243_pp0_iter2_reg == 1'd0)) | ((enable_7_fu_1656_p3 == 6'd26) & (icmp_ln772_reg_2282_pp0_iter2_reg == 1'd1) & (icmp_ln633_reg_2243_pp0_iter2_reg == 1'd0)) | ((enable_7_fu_1656_p3 == 6'd24) & (icmp_ln772_reg_2282_pp0_iter2_reg == 1'd1) & (icmp_ln633_reg_2243_pp0_iter2_reg == 1'd0)) | ((enable_7_fu_1656_p3 == 6'd10) & (icmp_ln772_reg_2282_pp0_iter2_reg == 1'd1) & (icmp_ln633_reg_2243_pp0_iter2_reg == 1'd0)) | ((enable_7_fu_1656_p3 == 6'd8) & (icmp_ln772_reg_2282_pp0_iter2_reg == 1'd1) & (icmp_ln633_reg_2243_pp0_iter2_reg == 1'd0)) | ((enable_7_fu_1656_p3 == 6'd60) & (icmp_ln772_reg_2282_pp0_iter2_reg == 1'd1) & (icmp_ln633_reg_2243_pp0_iter2_reg == 1'd0)) | ((enable_7_fu_1656_p3 
    == 6'd56) & (icmp_ln772_reg_2282_pp0_iter2_reg == 1'd1) & (icmp_ln633_reg_2243_pp0_iter2_reg == 1'd0)) | ((enable_7_fu_1656_p3 == 6'd52) & (icmp_ln772_reg_2282_pp0_iter2_reg == 1'd1) & (icmp_ln633_reg_2243_pp0_iter2_reg == 1'd0)) | ((enable_7_fu_1656_p3 == 6'd48) & (icmp_ln772_reg_2282_pp0_iter2_reg == 1'd1) & (icmp_ln633_reg_2243_pp0_iter2_reg == 1'd0)))) begin
        ap_phi_mux_en_rgd_phi_fu_728_p14 = 1'd0;
    end else begin
        ap_phi_mux_en_rgd_phi_fu_728_p14 = ap_phi_reg_pp0_iter3_en_rgd_reg_725;
    end
end

always @ (*) begin
    if ((icmp_ln633_reg_2243 == 1'd0)) begin
        if ((icmp_ln643_reg_2247 == 1'd0)) begin
            ap_phi_mux_p_0_0_09381411_i_phi_fu_593_p4 = p_0_2_0_0_09151507_i_fu_236;
        end else if ((icmp_ln643_reg_2247 == 1'd1)) begin
            ap_phi_mux_p_0_0_09381411_i_phi_fu_593_p4 = select_ln710_6_fu_1119_p3;
        end else begin
            ap_phi_mux_p_0_0_09381411_i_phi_fu_593_p4 = ap_phi_reg_pp0_iter1_p_0_0_09381411_i_reg_590;
        end
    end else begin
        ap_phi_mux_p_0_0_09381411_i_phi_fu_593_p4 = ap_phi_reg_pp0_iter1_p_0_0_09381411_i_reg_590;
    end
end

always @ (*) begin
    if ((icmp_ln633_reg_2243 == 1'd0)) begin
        if ((icmp_ln643_reg_2247 == 1'd0)) begin
            ap_phi_mux_p_0_0_0938_21441_i_phi_fu_539_p4 = p_0_2_0_0_09091519_i_fu_260;
        end else if ((icmp_ln643_reg_2247 == 1'd1)) begin
            ap_phi_mux_p_0_0_0938_21441_i_phi_fu_539_p4 = select_ln710_12_fu_1167_p3;
        end else begin
            ap_phi_mux_p_0_0_0938_21441_i_phi_fu_539_p4 = ap_phi_reg_pp0_iter1_p_0_0_0938_21441_i_reg_536;
        end
    end else begin
        ap_phi_mux_p_0_0_0938_21441_i_phi_fu_539_p4 = ap_phi_reg_pp0_iter1_p_0_0_0938_21441_i_reg_536;
    end
end

always @ (*) begin
    if (((icmp_ln643_reg_2247 == 1'd1) & (icmp_ln633_reg_2243 == 1'd0))) begin
        if ((icmp_ln664_reg_2232 == 1'd0)) begin
            ap_phi_mux_p_0_0_0938_21489_ph_i_phi_fu_485_p4 = {{lineBuffer_q1[23:16]}};
        end else if ((icmp_ln664_reg_2232 == 1'd1)) begin
            ap_phi_mux_p_0_0_0938_21489_ph_i_phi_fu_485_p4 = {{imgG_dout[23:16]}};
        end else begin
            ap_phi_mux_p_0_0_0938_21489_ph_i_phi_fu_485_p4 = ap_phi_reg_pp0_iter1_p_0_0_0938_21489_ph_i_reg_482;
        end
    end else begin
        ap_phi_mux_p_0_0_0938_21489_ph_i_phi_fu_485_p4 = ap_phi_reg_pp0_iter1_p_0_0_0938_21489_ph_i_reg_482;
    end
end

always @ (*) begin
    if ((icmp_ln633_reg_2243 == 1'd0)) begin
        if ((icmp_ln643_reg_2247 == 1'd0)) begin
            ap_phi_mux_p_0_0_09391408_i_phi_fu_602_p4 = p_0_1_0_0_09141505_i_fu_232;
        end else if ((icmp_ln643_reg_2247 == 1'd1)) begin
            ap_phi_mux_p_0_0_09391408_i_phi_fu_602_p4 = select_ln710_7_fu_1127_p3;
        end else begin
            ap_phi_mux_p_0_0_09391408_i_phi_fu_602_p4 = ap_phi_reg_pp0_iter1_p_0_0_09391408_i_reg_599;
        end
    end else begin
        ap_phi_mux_p_0_0_09391408_i_phi_fu_602_p4 = ap_phi_reg_pp0_iter1_p_0_0_09391408_i_reg_599;
    end
end

always @ (*) begin
    if ((icmp_ln633_reg_2243 == 1'd0)) begin
        if ((icmp_ln643_reg_2247 == 1'd0)) begin
            ap_phi_mux_p_0_0_0939_21438_i_phi_fu_548_p4 = p_0_1_0_0_09081517_i_fu_256;
        end else if ((icmp_ln643_reg_2247 == 1'd1)) begin
            ap_phi_mux_p_0_0_0939_21438_i_phi_fu_548_p4 = select_ln710_13_fu_1175_p3;
        end else begin
            ap_phi_mux_p_0_0_0939_21438_i_phi_fu_548_p4 = ap_phi_reg_pp0_iter1_p_0_0_0939_21438_i_reg_545;
        end
    end else begin
        ap_phi_mux_p_0_0_0939_21438_i_phi_fu_548_p4 = ap_phi_reg_pp0_iter1_p_0_0_0939_21438_i_reg_545;
    end
end

always @ (*) begin
    if (((icmp_ln643_reg_2247 == 1'd1) & (icmp_ln633_reg_2243 == 1'd0))) begin
        if ((icmp_ln664_reg_2232 == 1'd0)) begin
            ap_phi_mux_p_0_0_0939_21487_ph_i_phi_fu_494_p4 = {{lineBuffer_q1[15:8]}};
        end else if ((icmp_ln664_reg_2232 == 1'd1)) begin
            ap_phi_mux_p_0_0_0939_21487_ph_i_phi_fu_494_p4 = {{imgG_dout[15:8]}};
        end else begin
            ap_phi_mux_p_0_0_0939_21487_ph_i_phi_fu_494_p4 = ap_phi_reg_pp0_iter1_p_0_0_0939_21487_ph_i_reg_491;
        end
    end else begin
        ap_phi_mux_p_0_0_0939_21487_ph_i_phi_fu_494_p4 = ap_phi_reg_pp0_iter1_p_0_0_0939_21487_ph_i_reg_491;
    end
end

always @ (*) begin
    if ((icmp_ln633_reg_2243 == 1'd0)) begin
        if ((icmp_ln643_reg_2247 == 1'd0)) begin
            ap_phi_mux_p_0_0_09401405_i_phi_fu_611_p4 = p_0_0_0_0_09131503_i_fu_228;
        end else if ((icmp_ln643_reg_2247 == 1'd1)) begin
            ap_phi_mux_p_0_0_09401405_i_phi_fu_611_p4 = select_ln710_8_fu_1135_p3;
        end else begin
            ap_phi_mux_p_0_0_09401405_i_phi_fu_611_p4 = ap_phi_reg_pp0_iter1_p_0_0_09401405_i_reg_608;
        end
    end else begin
        ap_phi_mux_p_0_0_09401405_i_phi_fu_611_p4 = ap_phi_reg_pp0_iter1_p_0_0_09401405_i_reg_608;
    end
end

always @ (*) begin
    if ((icmp_ln633_reg_2243 == 1'd0)) begin
        if ((icmp_ln643_reg_2247 == 1'd0)) begin
            ap_phi_mux_p_0_0_0940_21435_i_phi_fu_557_p4 = p_0_0_0_0_09071515_i_fu_252;
        end else if ((icmp_ln643_reg_2247 == 1'd1)) begin
            ap_phi_mux_p_0_0_0940_21435_i_phi_fu_557_p4 = select_ln710_14_fu_1183_p3;
        end else begin
            ap_phi_mux_p_0_0_0940_21435_i_phi_fu_557_p4 = ap_phi_reg_pp0_iter1_p_0_0_0940_21435_i_reg_554;
        end
    end else begin
        ap_phi_mux_p_0_0_0940_21435_i_phi_fu_557_p4 = ap_phi_reg_pp0_iter1_p_0_0_0940_21435_i_reg_554;
    end
end

always @ (*) begin
    if (((icmp_ln643_reg_2247 == 1'd1) & (icmp_ln633_reg_2243 == 1'd0))) begin
        if ((icmp_ln664_reg_2232 == 1'd0)) begin
            ap_phi_mux_p_0_0_0940_21485_ph_i_phi_fu_503_p4 = trunc_ln654_fu_1004_p1;
        end else if ((icmp_ln664_reg_2232 == 1'd1)) begin
            ap_phi_mux_p_0_0_0940_21485_ph_i_phi_fu_503_p4 = trunc_ln666_fu_1047_p1;
        end else begin
            ap_phi_mux_p_0_0_0940_21485_ph_i_phi_fu_503_p4 = ap_phi_reg_pp0_iter1_p_0_0_0940_21485_ph_i_reg_500;
        end
    end else begin
        ap_phi_mux_p_0_0_0940_21485_ph_i_phi_fu_503_p4 = ap_phi_reg_pp0_iter1_p_0_0_0940_21485_ph_i_reg_500;
    end
end

always @ (*) begin
    if ((icmp_ln633_reg_2243_pp0_iter3_reg == 1'd0)) begin
        if ((icmp_ln772_reg_2282_pp0_iter3_reg == 1'd0)) begin
            ap_phi_mux_r_1_phi_fu_754_p4 = zext_ln763_fu_1835_p1;
        end else if ((icmp_ln772_reg_2282_pp0_iter3_reg == 1'd1)) begin
            ap_phi_mux_r_1_phi_fu_754_p4 = r_fu_1889_p3;
        end else begin
            ap_phi_mux_r_1_phi_fu_754_p4 = ap_phi_reg_pp0_iter4_r_1_reg_751;
        end
    end else begin
        ap_phi_mux_r_1_phi_fu_754_p4 = ap_phi_reg_pp0_iter4_r_1_reg_751;
    end
end

always @ (*) begin
    if ((icmp_ln633_reg_2243 == 1'd0)) begin
        if ((icmp_ln643_reg_2247 == 1'd0)) begin
            ap_phi_mux_upleft_1_phi_fu_575_p4 = p_0_0_09391407_i_fu_268;
        end else if ((icmp_ln643_reg_2247 == 1'd1)) begin
            ap_phi_mux_upleft_1_phi_fu_575_p4 = select_ln710_4_fu_1103_p3;
        end else begin
            ap_phi_mux_upleft_1_phi_fu_575_p4 = ap_phi_reg_pp0_iter1_upleft_1_reg_572;
        end
    end else begin
        ap_phi_mux_upleft_1_phi_fu_575_p4 = ap_phi_reg_pp0_iter1_upleft_1_reg_572;
    end
end

always @ (*) begin
    if ((icmp_ln633_reg_2243 == 1'd0)) begin
        if ((icmp_ln643_reg_2247 == 1'd0)) begin
            ap_phi_mux_upleft_2_phi_fu_566_p4 = p_0_0_09381410_i_fu_272;
        end else if ((icmp_ln643_reg_2247 == 1'd1)) begin
            ap_phi_mux_upleft_2_phi_fu_566_p4 = select_ln710_3_fu_1095_p3;
        end else begin
            ap_phi_mux_upleft_2_phi_fu_566_p4 = ap_phi_reg_pp0_iter1_upleft_2_reg_563;
        end
    end else begin
        ap_phi_mux_upleft_2_phi_fu_566_p4 = ap_phi_reg_pp0_iter1_upleft_2_reg_563;
    end
end

always @ (*) begin
    if ((icmp_ln633_reg_2243 == 1'd0)) begin
        if ((icmp_ln643_reg_2247 == 1'd0)) begin
            ap_phi_mux_upleft_phi_fu_584_p4 = p_0_0_09401404_i_fu_264;
        end else if ((icmp_ln643_reg_2247 == 1'd1)) begin
            ap_phi_mux_upleft_phi_fu_584_p4 = select_ln710_5_fu_1111_p3;
        end else begin
            ap_phi_mux_upleft_phi_fu_584_p4 = ap_phi_reg_pp0_iter1_upleft_reg_581;
        end
    end else begin
        ap_phi_mux_upleft_phi_fu_584_p4 = ap_phi_reg_pp0_iter1_upleft_reg_581;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_z = 11'd0;
    end else begin
        ap_sig_allocacmp_z = x_fu_224;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_predicate_op123_read_state2 == 1'b1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        imgG_blk_n = imgG_empty_n;
    end else begin
        imgG_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_predicate_op123_read_state2 == 1'b1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        imgG_read = 1'b1;
    end else begin
        imgG_read = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'd1 == and_ln833_reg_2286_pp0_iter3_reg) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        imgRB_blk_n = imgRB_full_n;
    end else begin
        imgRB_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'd1 == and_ln833_reg_2286_pp0_iter3_reg) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        imgRB_write = 1'b1;
    end else begin
        imgRB_write = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        lineBuffer_1_ce0_local = 1'b1;
    end else begin
        lineBuffer_1_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        lineBuffer_1_ce1_local = 1'b1;
    end else begin
        lineBuffer_1_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln643_reg_2247 == 1'd1) & (icmp_ln633_reg_2243 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        lineBuffer_1_we0_local = 1'b1;
    end else begin
        lineBuffer_1_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        lineBuffer_ce0_local = 1'b1;
    end else begin
        lineBuffer_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        lineBuffer_ce1_local = 1'b1;
    end else begin
        lineBuffer_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln664_reg_2232 == 1'd1) & (icmp_ln643_reg_2247 == 1'd1) & (icmp_ln633_reg_2243 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        lineBuffer_we0_local = 1'b1;
    end else begin
        lineBuffer_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter3_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (icmp_ln633_reg_2243_pp0_iter2_reg == 1'd1))) begin
        p_0_0_09381410_i_out_ap_vld = 1'b1;
    end else begin
        p_0_0_09381410_i_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter3_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (icmp_ln633_reg_2243_pp0_iter2_reg == 1'd1))) begin
        p_0_0_0938_115011512_i_out_ap_vld = 1'b1;
    end else begin
        p_0_0_0938_115011512_i_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter3_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (icmp_ln633_reg_2243_pp0_iter2_reg == 1'd1))) begin
        p_0_0_0938_21440_i_out_ap_vld = 1'b1;
    end else begin
        p_0_0_0938_21440_i_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter3_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (icmp_ln633_reg_2243_pp0_iter2_reg == 1'd1))) begin
        p_0_0_09391407_i_out_ap_vld = 1'b1;
    end else begin
        p_0_0_09391407_i_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter3_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (icmp_ln633_reg_2243_pp0_iter2_reg == 1'd1))) begin
        p_0_0_0939_114991510_i_out_ap_vld = 1'b1;
    end else begin
        p_0_0_0939_114991510_i_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter3_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (icmp_ln633_reg_2243_pp0_iter2_reg == 1'd1))) begin
        p_0_0_0939_21437_i_out_ap_vld = 1'b1;
    end else begin
        p_0_0_0939_21437_i_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter3_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (icmp_ln633_reg_2243_pp0_iter2_reg == 1'd1))) begin
        p_0_0_09401404_i_out_ap_vld = 1'b1;
    end else begin
        p_0_0_09401404_i_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter3_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (icmp_ln633_reg_2243_pp0_iter2_reg == 1'd1))) begin
        p_0_0_0940_114971508_i_out_ap_vld = 1'b1;
    end else begin
        p_0_0_0940_114971508_i_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter3_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (icmp_ln633_reg_2243_pp0_iter2_reg == 1'd1))) begin
        p_0_0_0940_21434_i_out_ap_vld = 1'b1;
    end else begin
        p_0_0_0940_21434_i_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter3_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (icmp_ln633_reg_2243_pp0_iter2_reg == 1'd1))) begin
        p_0_0_0_0_09071515_i_out_ap_vld = 1'b1;
    end else begin
        p_0_0_0_0_09071515_i_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter3_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (icmp_ln633_reg_2243_pp0_iter2_reg == 1'd1))) begin
        p_0_0_0_0_09131503_i_out_ap_vld = 1'b1;
    end else begin
        p_0_0_0_0_09131503_i_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter3_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (icmp_ln633_reg_2243_pp0_iter2_reg == 1'd1))) begin
        p_0_1_0_0_09081517_i_out_ap_vld = 1'b1;
    end else begin
        p_0_1_0_0_09081517_i_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter3_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (icmp_ln633_reg_2243_pp0_iter2_reg == 1'd1))) begin
        p_0_1_0_0_09141505_i_out_ap_vld = 1'b1;
    end else begin
        p_0_1_0_0_09141505_i_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter3_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (icmp_ln633_reg_2243_pp0_iter2_reg == 1'd1))) begin
        p_0_2_0_0_09091519_i_out_ap_vld = 1'b1;
    end else begin
        p_0_2_0_0_09091519_i_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter3_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (icmp_ln633_reg_2243_pp0_iter2_reg == 1'd1))) begin
        p_0_2_0_0_09151507_i_out_ap_vld = 1'b1;
    end else begin
        p_0_2_0_0_09151507_i_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign CH_fu_1845_p3 = ((red_reg_2221[0:0] == 1'b1) ? pix_reg_637_pp0_iter3_reg : pix_4_reg_617_pp0_iter3_reg);

assign CV_fu_1883_p2 = (zext_ln817_1_fu_1879_p1 - select_ln820_1_fu_1872_p3);

assign LineBufVal_2_fu_1212_p4 = {{{select_ln728_2_fu_1205_p3}, {select_ln728_1_fu_1198_p3}}, {select_ln728_fu_1191_p3}};

assign add_ln817_fu_1753_p2 = ($signed(sext_ln817_fu_1749_p1) + $signed(sext_ln818_fu_1732_p1));

assign add_ln820_1_fu_1797_p2 = ($signed(sext_ln820_1_fu_1776_p1) + $signed(sext_ln820_fu_1793_p1));

assign add_ln820_fu_1807_p2 = ($signed(sext_ln820_2_fu_1803_p1) + $signed(sext_ln818_1_fu_1772_p1));

assign agdiff_1_fu_1404_p3 = ((tmp_2_fu_1390_p3[0:0] == 1'b1) ? sub_ln61_1_fu_1398_p2 : trunc_ln61_1_fu_1386_p1);

assign agdiff_2_fu_1440_p3 = ((tmp_3_fu_1426_p3[0:0] == 1'b1) ? sub_ln61_2_fu_1434_p2 : trunc_ln61_2_fu_1422_p1);

assign agdiff_3_fu_1476_p3 = ((tmp_4_fu_1462_p3[0:0] == 1'b1) ? sub_ln61_3_fu_1470_p2 : trunc_ln61_3_fu_1458_p1);

assign agdiff_fu_1373_p3 = ((tmp_1_fu_1359_p3[0:0] == 1'b1) ? sub_ln61_fu_1367_p2 : trunc_ln61_fu_1355_p1);

assign and_ln817_fu_1727_p2 = (sub_ln817_reg_2393_pp0_iter2_reg & select_ln817_1_fu_1719_p3);

assign and_ln818_fu_1744_p2 = (sub_ln818_reg_2398_pp0_iter2_reg & select_ln818_1_fu_1736_p3);

assign and_ln819_fu_1767_p2 = (sub_ln819_reg_2414 & select_ln819_1_fu_1759_p3);

assign and_ln820_fu_1788_p2 = (sub_ln820_reg_2419 & select_ln820_2_fu_1780_p3);

assign and_ln833_fu_936_p2 = (icmp_ln833_fu_930_p2 & icmp_ln728_fu_785_p2);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

always @ (*) begin
    ap_block_pp0 = ((ap_ST_fsm_pp0_stage0 == ap_CS_fsm) & (1'b1 == ap_block_pp0_stage0_subdone));
end

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = (((ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_block_state5_pp0_stage0_iter4)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state2_pp0_stage0_iter1)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = (((ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_block_state5_pp0_stage0_iter4)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state2_pp0_stage0_iter1)));
end

assign ap_block_pp0_stage0_11001_grp0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_grp0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_subdone = (((ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_block_state5_pp0_stage0_iter4)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state2_pp0_stage0_iter1)));
end

assign ap_block_pp0_stage0_subdone_grp0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state2_pp0_stage0_iter1 = ((ap_predicate_op123_read_state2 == 1'b1) & (imgG_empty_n == 1'b0));
end

always @ (*) begin
    ap_block_state5_pp0_stage0_iter4 = ((imgRB_full_n == 1'b0) & (1'd1 == and_ln833_reg_2286_pp0_iter3_reg));
end

always @ (*) begin
    ap_condition_1476 = ((icmp_ln643_reg_2247 == 1'd1) & (icmp_ln633_reg_2243 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1));
end

always @ (*) begin
    ap_condition_280 = ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

assign ap_done = ap_done_sig;

always @ (*) begin
    ap_enable_operation_115 = (ap_predicate_op115_load_state2 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_119 = (ap_predicate_op119_load_state2 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_127 = (ap_predicate_op127_store_state2 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_150 = (ap_predicate_op150_store_state2 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_83 = (ap_predicate_op83_load_state1 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_85 = (ap_predicate_op85_load_state1 == 1'b1);
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

always @ (*) begin
    ap_enable_state1_pp0_iter0_stage0 = ((ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

always @ (*) begin
    ap_enable_state2_pp0_iter1_stage0 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_phi_reg_pp0_iter0_pix_3_reg_627 = 'bx;

assign ap_phi_reg_pp0_iter0_pix_4_reg_617 = 'bx;

assign ap_phi_reg_pp0_iter0_pix_reg_637 = 'bx;

assign ap_phi_reg_pp0_iter1_downleft_1_reg_518 = 'bx;

assign ap_phi_reg_pp0_iter1_downleft_2_reg_509 = 'bx;

assign ap_phi_reg_pp0_iter1_downleft_reg_527 = 'bx;

assign ap_phi_reg_pp0_iter1_p_0_0_09381411_i_reg_590 = 'bx;

assign ap_phi_reg_pp0_iter1_p_0_0_0938_21441_i_reg_536 = 'bx;

assign ap_phi_reg_pp0_iter1_p_0_0_0938_21489_ph_i_reg_482 = 'bx;

assign ap_phi_reg_pp0_iter1_p_0_0_09391408_i_reg_599 = 'bx;

assign ap_phi_reg_pp0_iter1_p_0_0_0939_21438_i_reg_545 = 'bx;

assign ap_phi_reg_pp0_iter1_p_0_0_0939_21487_ph_i_reg_491 = 'bx;

assign ap_phi_reg_pp0_iter1_p_0_0_09401405_i_reg_608 = 'bx;

assign ap_phi_reg_pp0_iter1_p_0_0_0940_21435_i_reg_554 = 'bx;

assign ap_phi_reg_pp0_iter1_p_0_0_0940_21485_ph_i_reg_500 = 'bx;

assign ap_phi_reg_pp0_iter1_upleft_1_reg_572 = 'bx;

assign ap_phi_reg_pp0_iter1_upleft_2_reg_563 = 'bx;

assign ap_phi_reg_pp0_iter1_upleft_reg_581 = 'bx;

assign ap_phi_reg_pp0_iter3_en_rgd_1_reg_699 = 'bx;

assign ap_phi_reg_pp0_iter3_en_rgd_2_reg_673 = 'bx;

assign ap_phi_reg_pp0_iter3_en_rgd_3_reg_647 = 'bx;

assign ap_phi_reg_pp0_iter3_en_rgd_reg_725 = 'bx;

assign ap_phi_reg_pp0_iter4_b_1_reg_760 = 'bx;

assign ap_phi_reg_pp0_iter4_r_1_reg_751 = 'bx;

always @ (*) begin
    ap_predicate_op115_load_state2 = ((icmp_ln643_reg_2247 == 1'd1) & (icmp_ln633_reg_2243 == 1'd0));
end

always @ (*) begin
    ap_predicate_op119_load_state2 = ((icmp_ln643_reg_2247 == 1'd1) & (icmp_ln633_reg_2243 == 1'd0));
end

always @ (*) begin
    ap_predicate_op123_read_state2 = ((icmp_ln664_reg_2232 == 1'd1) & (icmp_ln643_reg_2247 == 1'd1) & (icmp_ln633_reg_2243 == 1'd0));
end

always @ (*) begin
    ap_predicate_op127_store_state2 = ((icmp_ln664_reg_2232 == 1'd1) & (icmp_ln643_reg_2247 == 1'd1) & (icmp_ln633_reg_2243 == 1'd0));
end

always @ (*) begin
    ap_predicate_op150_store_state2 = ((icmp_ln643_reg_2247 == 1'd1) & (icmp_ln633_reg_2243 == 1'd0));
end

always @ (*) begin
    ap_predicate_op83_load_state1 = ((icmp_ln633_fu_874_p2 == 1'd0) & (icmp_ln643_fu_896_p2 == 1'd1));
end

always @ (*) begin
    ap_predicate_op85_load_state1 = ((icmp_ln633_fu_874_p2 == 1'd0) & (icmp_ln643_fu_896_p2 == 1'd1));
end

assign ap_ready = ap_ready_sig;

assign b_fu_1897_p3 = ((red_reg_2221[0:0] == 1'b1) ? CV_fu_1883_p2 : zext_ln788_fu_1852_p1);

assign enable_1_fu_1508_p3 = ((icmp_ln796_fu_1494_p2[0:0] == 1'b1) ? or_ln_fu_1500_p3 : zext_ln769_fu_1490_p1);

assign enable_2_fu_1526_p3 = {{1'd1}, {enable_1_fu_1508_p3}};

assign enable_3_fu_1534_p3 = ((icmp_ln797_fu_1520_p2[0:0] == 1'b1) ? enable_2_fu_1526_p3 : zext_ln769_1_fu_1516_p1);

assign enable_4_fu_1560_p3 = ((icmp_ln798_fu_1546_p2[0:0] == 1'b1) ? or_ln1_fu_1552_p3 : zext_ln769_2_fu_1542_p1);

assign enable_5_fu_1578_p3 = {{1'd1}, {enable_4_fu_1560_p3}};

assign enable_6_fu_1586_p3 = ((icmp_ln799_fu_1572_p2[0:0] == 1'b1) ? enable_5_fu_1578_p3 : zext_ln769_3_fu_1568_p1);

assign enable_7_fu_1656_p3 = ((icmp_ln800_reg_2409[0:0] == 1'b1) ? or_ln2_fu_1649_p3 : zext_ln769_4_fu_1646_p1);

assign enable_fu_1484_p2 = ((agdiff_fu_1373_p3 < agdiff_1_fu_1404_p3) ? 1'b1 : 1'b0);

assign icmp_ln633_fu_874_p2 = ((ap_sig_allocacmp_z == loopWidth) ? 1'b1 : 1'b0);

assign icmp_ln643_fu_896_p2 = ((ap_sig_allocacmp_z < width_val8_load) ? 1'b1 : 1'b0);

assign icmp_ln664_fu_779_p2 = ((y < height_val4_load) ? 1'b1 : 1'b0);

assign icmp_ln710_fu_902_p2 = ((ap_sig_allocacmp_z == 11'd0) ? 1'b1 : 1'b0);

assign icmp_ln728_fu_785_p2 = ((y != 11'd0) ? 1'b1 : 1'b0);

assign icmp_ln772_fu_924_p2 = ((xor_ln772_1 == zext_ln772_1_fu_920_p1) ? 1'b1 : 1'b0);

assign icmp_ln796_fu_1494_p2 = ((agdiff_fu_1373_p3 < agdiff_2_fu_1440_p3) ? 1'b1 : 1'b0);

assign icmp_ln797_fu_1520_p2 = ((agdiff_fu_1373_p3 < agdiff_3_fu_1476_p3) ? 1'b1 : 1'b0);

assign icmp_ln798_fu_1546_p2 = ((agdiff_1_fu_1404_p3 < agdiff_2_fu_1440_p3) ? 1'b1 : 1'b0);

assign icmp_ln799_fu_1572_p2 = ((agdiff_1_fu_1404_p3 < agdiff_3_fu_1476_p3) ? 1'b1 : 1'b0);

assign icmp_ln800_fu_1594_p2 = ((agdiff_2_fu_1440_p3 < agdiff_3_fu_1476_p3) ? 1'b1 : 1'b0);

assign icmp_ln827_fu_1923_p2 = ((tmp_7_fu_1913_p4 == 2'd1) ? 1'b1 : 1'b0);

assign icmp_ln829_fu_1979_p2 = ((tmp_9_fu_1969_p4 == 2'd1) ? 1'b1 : 1'b0);

assign icmp_ln833_fu_930_p2 = ((ap_sig_allocacmp_z != 11'd0) ? 1'b1 : 1'b0);

assign imgRB_din = {{{select_ln829_fu_2009_p3}, {pix_3_reg_627_pp0_iter3_reg}}, {select_ln827_fu_1953_p3}};

assign lineBuffer_1_address0 = lineBuffer_1_addr_reg_2257;

assign lineBuffer_1_address1 = zext_ln633_fu_890_p1;

assign lineBuffer_address0 = lineBuffer_addr_reg_2251;

assign lineBuffer_address1 = zext_ln633_fu_890_p1;

assign or_ln1_fu_1552_p3 = {{1'd1}, {enable_3_fu_1534_p3}};

assign or_ln2_fu_1649_p3 = {{1'd1}, {enable_6_reg_2403}};

assign or_ln827_fu_1947_p2 = (tmp_6_fu_1905_p3 | icmp_ln827_fu_1923_p2);

assign or_ln829_fu_2003_p2 = (tmp_8_fu_1961_p3 | icmp_ln829_fu_1979_p2);

assign or_ln_fu_1500_p3 = {{1'd1}, {enable_fu_1484_p2}};

assign p_0_0_09381410_i_out = p_0_0_09381410_i_load_reg_2348_pp0_iter2_reg;

assign p_0_0_0938_115011512_i_out = p_0_0_0938_115011512_i_load_reg_2317_pp0_iter2_reg;

assign p_0_0_0938_21440_i_out = p_0_0_0938_21440_i_load_reg_2363_pp0_iter2_reg;

assign p_0_0_09391407_i_out = p_0_0_09391407_i_load_reg_2343_pp0_iter2_reg;

assign p_0_0_0939_114991510_i_out = p_0_0_0939_114991510_i_load_reg_2311_pp0_iter2_reg;

assign p_0_0_0939_21437_i_out = p_0_0_0939_21437_i_load_reg_2358_pp0_iter2_reg;

assign p_0_0_09401404_i_out = p_0_0_09401404_i_load_reg_2338_pp0_iter2_reg;

assign p_0_0_0940_114971508_i_out = p_0_0_0940_114971508_i_load_reg_2305_pp0_iter2_reg;

assign p_0_0_0940_21434_i_out = p_0_0_0940_21434_i_load_reg_2353_pp0_iter2_reg;

assign p_0_0_0_0_09071515_i_out = p_0_0_0_0_09071515_i_load_reg_2323_pp0_iter2_reg;

assign p_0_0_0_0_09131503_i_out = p_0_0_0_0_09131503_i_load_reg_2290_pp0_iter2_reg;

assign p_0_1_0_0_09081517_i_out = p_0_1_0_0_09081517_i_load_reg_2328_pp0_iter2_reg;

assign p_0_1_0_0_09141505_i_out = p_0_1_0_0_09141505_i_load_reg_2295_pp0_iter2_reg;

assign p_0_2_0_0_09091519_i_out = p_0_2_0_0_09091519_i_load_reg_2333_pp0_iter2_reg;

assign p_0_2_0_0_09151507_i_out = p_0_2_0_0_09151507_i_load_reg_2300_pp0_iter2_reg;

assign r_fu_1889_p3 = ((red_reg_2221[0:0] == 1'b1) ? zext_ln788_fu_1852_p1 : CV_fu_1883_p2);

assign red_fu_773_p2 = ((zext_ln772_fu_769_p1 == trunc_ln) ? 1'b1 : 1'b0);

assign select_ln710_10_fu_1151_p3 = ((icmp_ln710_reg_2263[0:0] == 1'b1) ? ap_phi_mux_p_0_0_0939_21487_ph_i_phi_fu_494_p4 : p_0_0_0939_21437_i_fu_280);

assign select_ln710_11_fu_1159_p3 = ((icmp_ln710_reg_2263[0:0] == 1'b1) ? ap_phi_mux_p_0_0_0940_21485_ph_i_phi_fu_503_p4 : p_0_0_0940_21434_i_fu_276);

assign select_ln710_12_fu_1167_p3 = ((icmp_ln710_reg_2263[0:0] == 1'b1) ? ap_phi_mux_p_0_0_0938_21489_ph_i_phi_fu_485_p4 : p_0_2_0_0_09091519_i_fu_260);

assign select_ln710_13_fu_1175_p3 = ((icmp_ln710_reg_2263[0:0] == 1'b1) ? ap_phi_mux_p_0_0_0939_21487_ph_i_phi_fu_494_p4 : p_0_1_0_0_09081517_i_fu_256);

assign select_ln710_14_fu_1183_p3 = ((icmp_ln710_reg_2263[0:0] == 1'b1) ? ap_phi_mux_p_0_0_0940_21485_ph_i_phi_fu_503_p4 : p_0_0_0_0_09071515_i_fu_252);

assign select_ln710_1_fu_1081_p3 = ((icmp_ln710_reg_2263[0:0] == 1'b1) ? tmp_4_i_fu_1009_p3 : p_0_0_0939_114991510_i_fu_244);

assign select_ln710_2_fu_1088_p3 = ((icmp_ln710_reg_2263[0:0] == 1'b1) ? tmp_5_i_fu_1018_p3 : p_0_0_0938_115011512_i_fu_248);

assign select_ln710_3_fu_1095_p3 = ((icmp_ln710_reg_2263[0:0] == 1'b1) ? tmp_8_i_fu_1039_p3 : p_0_0_09381410_i_fu_272);

assign select_ln710_4_fu_1103_p3 = ((icmp_ln710_reg_2263[0:0] == 1'b1) ? tmp_7_i_fu_1031_p3 : p_0_0_09391407_i_fu_268);

assign select_ln710_5_fu_1111_p3 = ((icmp_ln710_reg_2263[0:0] == 1'b1) ? trunc_ln654_1_fu_1027_p1 : p_0_0_09401404_i_fu_264);

assign select_ln710_6_fu_1119_p3 = ((icmp_ln710_reg_2263[0:0] == 1'b1) ? tmp_8_i_fu_1039_p3 : p_0_2_0_0_09151507_i_fu_236);

assign select_ln710_7_fu_1127_p3 = ((icmp_ln710_reg_2263[0:0] == 1'b1) ? tmp_7_i_fu_1031_p3 : p_0_1_0_0_09141505_i_fu_232);

assign select_ln710_8_fu_1135_p3 = ((icmp_ln710_reg_2263[0:0] == 1'b1) ? trunc_ln654_1_fu_1027_p1 : p_0_0_0_0_09131503_i_fu_228);

assign select_ln710_9_fu_1143_p3 = ((icmp_ln710_reg_2263[0:0] == 1'b1) ? ap_phi_mux_p_0_0_0938_21489_ph_i_phi_fu_485_p4 : p_0_0_0938_21440_i_fu_284);

assign select_ln710_fu_1074_p3 = ((icmp_ln710_reg_2263[0:0] == 1'b1) ? trunc_ln654_fu_1004_p1 : p_0_0_0940_114971508_i_fu_240);

assign select_ln728_1_fu_1198_p3 = ((icmp_ln728_reg_2236[0:0] == 1'b1) ? tmp_4_i_fu_1009_p3 : ap_phi_mux_p_0_0_0939_21487_ph_i_phi_fu_494_p4);

assign select_ln728_2_fu_1205_p3 = ((icmp_ln728_reg_2236[0:0] == 1'b1) ? tmp_5_i_fu_1018_p3 : ap_phi_mux_p_0_0_0938_21489_ph_i_phi_fu_485_p4);

assign select_ln728_fu_1191_p3 = ((icmp_ln728_reg_2236[0:0] == 1'b1) ? trunc_ln654_fu_1004_p1 : ap_phi_mux_p_0_0_0940_21485_ph_i_phi_fu_503_p4);

assign select_ln817_1_fu_1719_p3 = ((ap_phi_mux_en_rgd_phi_fu_728_p14[0:0] == 1'b1) ? 9'd511 : 9'd0);

assign select_ln817_fu_1276_p3 = ((red_reg_2221[0:0] == 1'b1) ? ap_phi_mux_upleft_2_phi_fu_566_p4 : ap_phi_mux_upleft_phi_fu_584_p4);

assign select_ln818_1_fu_1736_p3 = ((ap_phi_mux_en_rgd_1_phi_fu_702_p14[0:0] == 1'b1) ? 9'd511 : 9'd0);

assign select_ln818_fu_1293_p3 = ((red_reg_2221[0:0] == 1'b1) ? ap_phi_mux_downleft_2_phi_fu_512_p4 : ap_phi_mux_downleft_phi_fu_530_p4);

assign select_ln819_1_fu_1759_p3 = ((ap_phi_mux_en_rgd_2_phi_fu_676_p14[0:0] == 1'b1) ? 9'd511 : 9'd0);

assign select_ln819_fu_1612_p3 = ((red_reg_2221[0:0] == 1'b1) ? p_0_2_0_0_09151507_i_fu_236 : p_0_0_0_0_09131503_i_fu_228);

assign select_ln820_1_fu_1872_p3 = ((tmp_5_fu_1856_p3[0:0] == 1'b1) ? sub_ln820_2_reg_2434 : trunc_ln820_2_fu_1863_p4);

assign select_ln820_2_fu_1780_p3 = ((ap_phi_mux_en_rgd_3_phi_fu_650_p14[0:0] == 1'b1) ? 9'd511 : 9'd0);

assign select_ln820_fu_1629_p3 = ((red_reg_2221[0:0] == 1'b1) ? p_0_2_0_0_09091519_i_fu_260 : p_0_0_0_0_09071515_i_fu_252);

assign select_ln827_1_fu_1939_p3 = ((xor_ln827_fu_1933_p2[0:0] == 1'b1) ? 8'd255 : 8'd0);

assign select_ln827_fu_1953_p3 = ((or_ln827_fu_1947_p2[0:0] == 1'b1) ? select_ln827_1_fu_1939_p3 : trunc_ln827_fu_1929_p1);

assign select_ln829_1_fu_1995_p3 = ((xor_ln829_fu_1989_p2[0:0] == 1'b1) ? 8'd255 : 8'd0);

assign select_ln829_fu_2009_p3 = ((or_ln829_fu_2003_p2[0:0] == 1'b1) ? select_ln829_1_fu_1995_p3 : trunc_ln829_fu_1985_p1);

assign sext_ln817_fu_1749_p1 = $signed(and_ln818_fu_1744_p2);

assign sext_ln818_1_fu_1772_p1 = $signed(add_ln817_fu_1753_p2);

assign sext_ln818_fu_1732_p1 = $signed(and_ln817_fu_1727_p2);

assign sext_ln820_1_fu_1776_p1 = $signed(and_ln819_fu_1767_p2);

assign sext_ln820_2_fu_1803_p1 = $signed(add_ln820_1_fu_1797_p2);

assign sext_ln820_fu_1793_p1 = $signed(and_ln820_fu_1788_p2);

assign sub_ln61_1_fu_1398_p2 = (8'd0 - trunc_ln61_1_fu_1386_p1);

assign sub_ln61_2_fu_1434_p2 = (8'd0 - trunc_ln61_2_fu_1422_p1);

assign sub_ln61_3_fu_1470_p2 = (8'd0 - trunc_ln61_3_fu_1458_p1);

assign sub_ln61_fu_1367_p2 = (8'd0 - trunc_ln61_fu_1355_p1);

assign sub_ln790_fu_1350_p2 = (zext_ln790_fu_1346_p1 - zext_ln790_1_reg_2383);

assign sub_ln791_fu_1381_p2 = (zext_ln790_fu_1346_p1 - zext_ln791_reg_2388);

assign sub_ln792_fu_1416_p2 = (zext_ln790_fu_1346_p1 - zext_ln792_fu_1412_p1);

assign sub_ln793_fu_1452_p2 = (zext_ln790_fu_1346_p1 - zext_ln793_fu_1448_p1);

assign sub_ln817_fu_1287_p2 = (zext_ln790_1_fu_1268_p1 - zext_ln817_fu_1283_p1);

assign sub_ln818_fu_1304_p2 = (zext_ln791_fu_1272_p1 - zext_ln818_fu_1300_p1);

assign sub_ln819_fu_1623_p2 = (zext_ln792_fu_1412_p1 - zext_ln819_fu_1619_p1);

assign sub_ln820_1_fu_1813_p2 = (11'd0 - add_ln820_fu_1807_p2);

assign sub_ln820_2_fu_1829_p2 = (10'd0 - trunc_ln820_1_fu_1819_p4);

assign sub_ln820_fu_1640_p2 = (zext_ln793_fu_1448_p1 - zext_ln820_fu_1636_p1);

assign tmp_1_fu_1359_p3 = sub_ln790_fu_1350_p2[32'd8];

assign tmp_2_fu_1390_p3 = sub_ln791_fu_1381_p2[32'd8];

assign tmp_3_fu_1426_p3 = sub_ln792_fu_1416_p2[32'd8];

assign tmp_4_fu_1462_p3 = sub_ln793_fu_1452_p2[32'd8];

assign tmp_4_i_fu_1009_p3 = {{lineBuffer_q1[15:8]}};

assign tmp_5_fu_1856_p3 = add_ln820_reg_2428[32'd10];

assign tmp_5_i_fu_1018_p3 = {{lineBuffer_q1[23:16]}};

assign tmp_6_fu_1905_p3 = ap_phi_mux_r_1_phi_fu_754_p4[32'd9];

assign tmp_7_fu_1913_p4 = {{ap_phi_mux_r_1_phi_fu_754_p4[9:8]}};

assign tmp_7_i_fu_1031_p3 = {{lineBuffer_1_q1[15:8]}};

assign tmp_8_fu_1961_p3 = ap_phi_mux_b_1_phi_fu_763_p4[32'd9];

assign tmp_8_i_fu_1039_p3 = {{lineBuffer_1_q1[23:16]}};

assign tmp_9_fu_1969_p4 = {{ap_phi_mux_b_1_phi_fu_763_p4[9:8]}};

assign trunc_ln61_1_fu_1386_p1 = sub_ln791_fu_1381_p2[7:0];

assign trunc_ln61_2_fu_1422_p1 = sub_ln792_fu_1416_p2[7:0];

assign trunc_ln61_3_fu_1458_p1 = sub_ln793_fu_1452_p2[7:0];

assign trunc_ln61_fu_1355_p1 = sub_ln790_fu_1350_p2[7:0];

assign trunc_ln633_fu_886_p1 = ap_sig_allocacmp_z[0:0];

assign trunc_ln654_1_fu_1027_p1 = lineBuffer_1_q1[7:0];

assign trunc_ln654_fu_1004_p1 = lineBuffer_q1[7:0];

assign trunc_ln666_fu_1047_p1 = imgG_dout[7:0];

assign trunc_ln820_1_fu_1819_p4 = {{sub_ln820_1_fu_1813_p2[10:1]}};

assign trunc_ln820_2_fu_1863_p4 = {{add_ln820_reg_2428[10:1]}};

assign trunc_ln827_fu_1929_p1 = ap_phi_mux_r_1_phi_fu_754_p4[7:0];

assign trunc_ln829_fu_1985_p1 = ap_phi_mux_b_1_phi_fu_763_p4[7:0];

assign x_5_fu_880_p2 = (ap_sig_allocacmp_z + 11'd1);

assign xor_ln772_2_fu_908_p2 = (trunc_ln633_fu_886_p1 ^ empty);

assign xor_ln772_3_fu_914_p2 = (xor_ln772_2_fu_908_p2 ^ 1'd1);

assign xor_ln827_fu_1933_p2 = (tmp_6_fu_1905_p3 ^ 1'd1);

assign xor_ln829_fu_1989_p2 = (tmp_8_fu_1961_p3 ^ 1'd1);

assign zext_ln633_fu_890_p1 = x_5_fu_880_p2;

assign zext_ln763_fu_1835_p1 = pix_reg_637_pp0_iter3_reg;

assign zext_ln765_fu_1840_p1 = pix_4_reg_617_pp0_iter3_reg;

assign zext_ln769_1_fu_1516_p1 = enable_1_fu_1508_p3;

assign zext_ln769_2_fu_1542_p1 = enable_3_fu_1534_p3;

assign zext_ln769_3_fu_1568_p1 = enable_4_fu_1560_p3;

assign zext_ln769_4_fu_1646_p1 = enable_6_reg_2403;

assign zext_ln769_fu_1490_p1 = enable_fu_1484_p2;

assign zext_ln772_1_fu_920_p1 = xor_ln772_3_fu_914_p2;

assign zext_ln772_fu_769_p1 = xor_ln772;

assign zext_ln788_fu_1852_p1 = CH_fu_1845_p3;

assign zext_ln790_1_fu_1268_p1 = ap_phi_mux_upleft_1_phi_fu_575_p4;

assign zext_ln790_fu_1346_p1 = ap_phi_reg_pp0_iter2_pix_3_reg_627;

assign zext_ln791_fu_1272_p1 = ap_phi_mux_downleft_1_phi_fu_521_p4;

assign zext_ln792_fu_1412_p1 = p_0_1_0_0_09141505_i_fu_232;

assign zext_ln793_fu_1448_p1 = p_0_1_0_0_09081517_i_fu_256;

assign zext_ln817_1_fu_1879_p1 = pix_3_reg_627_pp0_iter3_reg;

assign zext_ln817_fu_1283_p1 = select_ln817_fu_1276_p3;

assign zext_ln818_fu_1300_p1 = select_ln818_fu_1293_p3;

assign zext_ln819_fu_1619_p1 = select_ln819_fu_1612_p3;

assign zext_ln820_fu_1636_p1 = select_ln820_fu_1629_p3;

always @ (posedge ap_clk) begin
    zext_ln790_1_reg_2383[8] <= 1'b0;
    zext_ln791_reg_2388[8] <= 1'b0;
end

endmodule //pcam_v_demosaic_0_0_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2
