// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* DowngradeIPIdentifiedWarnings="yes" *)
module pcam_v_demosaic_0_0_ZipperRemoval (
        ap_clk,
        ap_rst,
        ap_start,
        start_full_n,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        start_out,
        start_write,
        imgRgb_dout,
        imgRgb_empty_n,
        imgRgb_read,
        imgRgb_num_data_valid,
        imgRgb_fifo_cap,
        imgUnzip_din,
        imgUnzip_full_n,
        imgUnzip_write,
        imgUnzip_num_data_valid,
        imgUnzip_fifo_cap,
        height_val,
        width_val
);

parameter    ap_ST_fsm_state1 = 4'd1;
parameter    ap_ST_fsm_state2 = 4'd2;
parameter    ap_ST_fsm_state3 = 4'd4;
parameter    ap_ST_fsm_state4 = 4'd8;

input   ap_clk;
input   ap_rst;
input   ap_start;
input   start_full_n;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
output   start_out;
output   start_write;
input  [23:0] imgRgb_dout;
input   imgRgb_empty_n;
output   imgRgb_read;
input  [2:0] imgRgb_num_data_valid;
input  [2:0] imgRgb_fifo_cap;
output  [23:0] imgUnzip_din;
input   imgUnzip_full_n;
output   imgUnzip_write;
input  [31:0] imgUnzip_num_data_valid;
input  [31:0] imgUnzip_fifo_cap;
input  [15:0] height_val;
input  [15:0] width_val;

reg ap_done;
reg ap_idle;
reg start_write;

reg    real_start;
reg    start_once_reg;
reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [3:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    internal_ap_ready;
reg   [15:0] width_val_read_reg_261;
reg    ap_block_state1;
reg   [15:0] height_val_read_reg_266;
wire   [16:0] loopWidth_fu_120_p2;
reg   [16:0] loopWidth_reg_271;
reg   [4:0] conv2_i_i_lcssa724_load_reg_279;
wire    ap_CS_fsm_state2;
reg   [7:0] p_0_0_0503692_lcssa699726_load_reg_284;
reg   [7:0] p_0_0_0502688_lcssa702727_load_reg_289;
reg   [7:0] p_0_0_0501690_lcssa705729_load_reg_294;
wire    grp_ZipperRemoval_Pipeline_VITIS_LOOP_1101_2_fu_94_ap_start;
wire    grp_ZipperRemoval_Pipeline_VITIS_LOOP_1101_2_fu_94_ap_done;
wire    grp_ZipperRemoval_Pipeline_VITIS_LOOP_1101_2_fu_94_ap_idle;
wire    grp_ZipperRemoval_Pipeline_VITIS_LOOP_1101_2_fu_94_ap_ready;
wire    grp_ZipperRemoval_Pipeline_VITIS_LOOP_1101_2_fu_94_imgRgb_read;
wire   [23:0] grp_ZipperRemoval_Pipeline_VITIS_LOOP_1101_2_fu_94_imgUnzip_din;
wire    grp_ZipperRemoval_Pipeline_VITIS_LOOP_1101_2_fu_94_imgUnzip_write;
wire   [7:0] grp_ZipperRemoval_Pipeline_VITIS_LOOP_1101_2_fu_94_p_0_0_0504_1704_out;
wire    grp_ZipperRemoval_Pipeline_VITIS_LOOP_1101_2_fu_94_p_0_0_0504_1704_out_ap_vld;
wire   [7:0] grp_ZipperRemoval_Pipeline_VITIS_LOOP_1101_2_fu_94_p_0_0_0505_1701_out;
wire    grp_ZipperRemoval_Pipeline_VITIS_LOOP_1101_2_fu_94_p_0_0_0505_1701_out_ap_vld;
wire   [7:0] grp_ZipperRemoval_Pipeline_VITIS_LOOP_1101_2_fu_94_p_0_0_0506_1698_out;
wire    grp_ZipperRemoval_Pipeline_VITIS_LOOP_1101_2_fu_94_p_0_0_0506_1698_out_ap_vld;
wire   [7:0] grp_ZipperRemoval_Pipeline_VITIS_LOOP_1101_2_fu_94_p_0_0_0504_1696_out_o;
wire    grp_ZipperRemoval_Pipeline_VITIS_LOOP_1101_2_fu_94_p_0_0_0504_1696_out_o_ap_vld;
wire   [7:0] grp_ZipperRemoval_Pipeline_VITIS_LOOP_1101_2_fu_94_p_0_0_0505_1695_out_o;
wire    grp_ZipperRemoval_Pipeline_VITIS_LOOP_1101_2_fu_94_p_0_0_0505_1695_out_o_ap_vld;
wire   [7:0] grp_ZipperRemoval_Pipeline_VITIS_LOOP_1101_2_fu_94_p_0_0_0506_1694_out_o;
wire    grp_ZipperRemoval_Pipeline_VITIS_LOOP_1101_2_fu_94_p_0_0_0506_1694_out_o_ap_vld;
wire   [7:0] grp_ZipperRemoval_Pipeline_VITIS_LOOP_1101_2_fu_94_p_0_0_0507_1693_out_o;
wire    grp_ZipperRemoval_Pipeline_VITIS_LOOP_1101_2_fu_94_p_0_0_0507_1693_out_o_ap_vld;
wire   [4:0] grp_ZipperRemoval_Pipeline_VITIS_LOOP_1101_2_fu_94_phi_ln1132_out;
wire    grp_ZipperRemoval_Pipeline_VITIS_LOOP_1101_2_fu_94_phi_ln1132_out_ap_vld;
reg    grp_ZipperRemoval_Pipeline_VITIS_LOOP_1101_2_fu_94_ap_start_reg;
wire    ap_CS_fsm_state3;
wire    ap_CS_fsm_state4;
reg   [7:0] p_0_0_0501690_lcssa705729_fu_78;
reg   [7:0] p_0_0_0502688_lcssa702727_fu_74;
reg   [7:0] p_0_0_0503692_lcssa699726_fu_70;
reg   [7:0] p_0_0_0504_1_lcssa722_fu_62;
reg   [7:0] p_0_0_0505_1_lcssa720_fu_58;
reg   [7:0] p_0_0_0506_1_lcssa718_fu_54;
reg   [7:0] p_0_0_0507_1_lcssa716_fu_50;
reg   [4:0] conv2_i_i_lcssa724_fu_66;
reg   [15:0] y_fu_46;
wire   [15:0] y_2_fu_179_p2;
wire   [0:0] icmp_ln1099_fu_174_p2;
wire   [16:0] zext_ln1085_fu_116_p1;
reg   [3:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
reg    ap_ST_fsm_state4_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 start_once_reg = 1'b0;
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 4'd1;
#0 grp_ZipperRemoval_Pipeline_VITIS_LOOP_1101_2_fu_94_ap_start_reg = 1'b0;
#0 p_0_0_0501690_lcssa705729_fu_78 = 8'd0;
#0 p_0_0_0502688_lcssa702727_fu_74 = 8'd0;
#0 p_0_0_0503692_lcssa699726_fu_70 = 8'd0;
#0 p_0_0_0504_1_lcssa722_fu_62 = 8'd0;
#0 p_0_0_0505_1_lcssa720_fu_58 = 8'd0;
#0 p_0_0_0506_1_lcssa718_fu_54 = 8'd0;
#0 p_0_0_0507_1_lcssa716_fu_50 = 8'd0;
#0 conv2_i_i_lcssa724_fu_66 = 5'd0;
#0 y_fu_46 = 16'd0;
end

pcam_v_demosaic_0_0_ZipperRemoval_Pipeline_VITIS_LOOP_1101_2 grp_ZipperRemoval_Pipeline_VITIS_LOOP_1101_2_fu_94(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_ZipperRemoval_Pipeline_VITIS_LOOP_1101_2_fu_94_ap_start),
    .ap_done(grp_ZipperRemoval_Pipeline_VITIS_LOOP_1101_2_fu_94_ap_done),
    .ap_idle(grp_ZipperRemoval_Pipeline_VITIS_LOOP_1101_2_fu_94_ap_idle),
    .ap_ready(grp_ZipperRemoval_Pipeline_VITIS_LOOP_1101_2_fu_94_ap_ready),
    .imgRgb_dout(imgRgb_dout),
    .imgRgb_empty_n(imgRgb_empty_n),
    .imgRgb_read(grp_ZipperRemoval_Pipeline_VITIS_LOOP_1101_2_fu_94_imgRgb_read),
    .imgRgb_num_data_valid(3'd0),
    .imgRgb_fifo_cap(3'd0),
    .imgUnzip_din(grp_ZipperRemoval_Pipeline_VITIS_LOOP_1101_2_fu_94_imgUnzip_din),
    .imgUnzip_full_n(imgUnzip_full_n),
    .imgUnzip_write(grp_ZipperRemoval_Pipeline_VITIS_LOOP_1101_2_fu_94_imgUnzip_write),
    .imgUnzip_num_data_valid(imgUnzip_num_data_valid),
    .imgUnzip_fifo_cap(imgUnzip_fifo_cap),
    .p_0_0_0501690_lcssa705729(p_0_0_0501690_lcssa705729_load_reg_294),
    .p_0_0_0502688_lcssa702727(p_0_0_0502688_lcssa702727_load_reg_289),
    .p_0_0_0503692_lcssa699726(p_0_0_0503692_lcssa699726_load_reg_284),
    .conv2_i_i_lcssa724(conv2_i_i_lcssa724_load_reg_279),
    .width_val(width_val_read_reg_261),
    .loopWidth(loopWidth_reg_271),
    .p_0_0_0504_1704_out(grp_ZipperRemoval_Pipeline_VITIS_LOOP_1101_2_fu_94_p_0_0_0504_1704_out),
    .p_0_0_0504_1704_out_ap_vld(grp_ZipperRemoval_Pipeline_VITIS_LOOP_1101_2_fu_94_p_0_0_0504_1704_out_ap_vld),
    .p_0_0_0505_1701_out(grp_ZipperRemoval_Pipeline_VITIS_LOOP_1101_2_fu_94_p_0_0_0505_1701_out),
    .p_0_0_0505_1701_out_ap_vld(grp_ZipperRemoval_Pipeline_VITIS_LOOP_1101_2_fu_94_p_0_0_0505_1701_out_ap_vld),
    .p_0_0_0506_1698_out(grp_ZipperRemoval_Pipeline_VITIS_LOOP_1101_2_fu_94_p_0_0_0506_1698_out),
    .p_0_0_0506_1698_out_ap_vld(grp_ZipperRemoval_Pipeline_VITIS_LOOP_1101_2_fu_94_p_0_0_0506_1698_out_ap_vld),
    .p_0_0_0504_1696_out_i(p_0_0_0504_1_lcssa722_fu_62),
    .p_0_0_0504_1696_out_o(grp_ZipperRemoval_Pipeline_VITIS_LOOP_1101_2_fu_94_p_0_0_0504_1696_out_o),
    .p_0_0_0504_1696_out_o_ap_vld(grp_ZipperRemoval_Pipeline_VITIS_LOOP_1101_2_fu_94_p_0_0_0504_1696_out_o_ap_vld),
    .p_0_0_0505_1695_out_i(p_0_0_0505_1_lcssa720_fu_58),
    .p_0_0_0505_1695_out_o(grp_ZipperRemoval_Pipeline_VITIS_LOOP_1101_2_fu_94_p_0_0_0505_1695_out_o),
    .p_0_0_0505_1695_out_o_ap_vld(grp_ZipperRemoval_Pipeline_VITIS_LOOP_1101_2_fu_94_p_0_0_0505_1695_out_o_ap_vld),
    .p_0_0_0506_1694_out_i(p_0_0_0506_1_lcssa718_fu_54),
    .p_0_0_0506_1694_out_o(grp_ZipperRemoval_Pipeline_VITIS_LOOP_1101_2_fu_94_p_0_0_0506_1694_out_o),
    .p_0_0_0506_1694_out_o_ap_vld(grp_ZipperRemoval_Pipeline_VITIS_LOOP_1101_2_fu_94_p_0_0_0506_1694_out_o_ap_vld),
    .p_0_0_0507_1693_out_i(p_0_0_0507_1_lcssa716_fu_50),
    .p_0_0_0507_1693_out_o(grp_ZipperRemoval_Pipeline_VITIS_LOOP_1101_2_fu_94_p_0_0_0507_1693_out_o),
    .p_0_0_0507_1693_out_o_ap_vld(grp_ZipperRemoval_Pipeline_VITIS_LOOP_1101_2_fu_94_p_0_0_0507_1693_out_o_ap_vld),
    .phi_ln1132_out(grp_ZipperRemoval_Pipeline_VITIS_LOOP_1101_2_fu_94_phi_ln1132_out),
    .phi_ln1132_out_ap_vld(grp_ZipperRemoval_Pipeline_VITIS_LOOP_1101_2_fu_94_phi_ln1132_out_ap_vld)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln1099_fu_174_p2 == 1'd1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_ZipperRemoval_Pipeline_VITIS_LOOP_1101_2_fu_94_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state3)) begin
            grp_ZipperRemoval_Pipeline_VITIS_LOOP_1101_2_fu_94_ap_start_reg <= 1'b1;
        end else if ((grp_ZipperRemoval_Pipeline_VITIS_LOOP_1101_2_fu_94_ap_ready == 1'b1)) begin
            grp_ZipperRemoval_Pipeline_VITIS_LOOP_1101_2_fu_94_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        start_once_reg <= 1'b0;
    end else begin
        if (((internal_ap_ready == 1'b0) & (real_start == 1'b1))) begin
            start_once_reg <= 1'b1;
        end else if ((internal_ap_ready == 1'b1)) begin
            start_once_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        conv2_i_i_lcssa724_fu_66 <= 5'd0;
    end else if (((1'b1 == ap_CS_fsm_state4) & (grp_ZipperRemoval_Pipeline_VITIS_LOOP_1101_2_fu_94_phi_ln1132_out_ap_vld == 1'b1))) begin
        conv2_i_i_lcssa724_fu_66 <= grp_ZipperRemoval_Pipeline_VITIS_LOOP_1101_2_fu_94_phi_ln1132_out;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        p_0_0_0501690_lcssa705729_fu_78 <= 8'd0;
    end else if (((1'b1 == ap_CS_fsm_state4) & (grp_ZipperRemoval_Pipeline_VITIS_LOOP_1101_2_fu_94_p_0_0_0504_1704_out_ap_vld == 1'b1))) begin
        p_0_0_0501690_lcssa705729_fu_78 <= grp_ZipperRemoval_Pipeline_VITIS_LOOP_1101_2_fu_94_p_0_0_0504_1704_out;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        p_0_0_0502688_lcssa702727_fu_74 <= 8'd0;
    end else if (((1'b1 == ap_CS_fsm_state4) & (grp_ZipperRemoval_Pipeline_VITIS_LOOP_1101_2_fu_94_p_0_0_0505_1701_out_ap_vld == 1'b1))) begin
        p_0_0_0502688_lcssa702727_fu_74 <= grp_ZipperRemoval_Pipeline_VITIS_LOOP_1101_2_fu_94_p_0_0_0505_1701_out;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        p_0_0_0503692_lcssa699726_fu_70 <= 8'd0;
    end else if (((1'b1 == ap_CS_fsm_state4) & (grp_ZipperRemoval_Pipeline_VITIS_LOOP_1101_2_fu_94_p_0_0_0506_1698_out_ap_vld == 1'b1))) begin
        p_0_0_0503692_lcssa699726_fu_70 <= grp_ZipperRemoval_Pipeline_VITIS_LOOP_1101_2_fu_94_p_0_0_0506_1698_out;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        p_0_0_0504_1_lcssa722_fu_62 <= 8'd0;
    end else if (((1'b1 == ap_CS_fsm_state4) & (grp_ZipperRemoval_Pipeline_VITIS_LOOP_1101_2_fu_94_p_0_0_0504_1696_out_o_ap_vld == 1'b1))) begin
        p_0_0_0504_1_lcssa722_fu_62 <= grp_ZipperRemoval_Pipeline_VITIS_LOOP_1101_2_fu_94_p_0_0_0504_1696_out_o;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        p_0_0_0505_1_lcssa720_fu_58 <= 8'd0;
    end else if (((1'b1 == ap_CS_fsm_state4) & (grp_ZipperRemoval_Pipeline_VITIS_LOOP_1101_2_fu_94_p_0_0_0505_1695_out_o_ap_vld == 1'b1))) begin
        p_0_0_0505_1_lcssa720_fu_58 <= grp_ZipperRemoval_Pipeline_VITIS_LOOP_1101_2_fu_94_p_0_0_0505_1695_out_o;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        p_0_0_0506_1_lcssa718_fu_54 <= 8'd0;
    end else if (((1'b1 == ap_CS_fsm_state4) & (grp_ZipperRemoval_Pipeline_VITIS_LOOP_1101_2_fu_94_p_0_0_0506_1694_out_o_ap_vld == 1'b1))) begin
        p_0_0_0506_1_lcssa718_fu_54 <= grp_ZipperRemoval_Pipeline_VITIS_LOOP_1101_2_fu_94_p_0_0_0506_1694_out_o;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        p_0_0_0507_1_lcssa716_fu_50 <= 8'd0;
    end else if (((1'b1 == ap_CS_fsm_state4) & (grp_ZipperRemoval_Pipeline_VITIS_LOOP_1101_2_fu_94_p_0_0_0507_1693_out_o_ap_vld == 1'b1))) begin
        p_0_0_0507_1_lcssa716_fu_50 <= grp_ZipperRemoval_Pipeline_VITIS_LOOP_1101_2_fu_94_p_0_0_0507_1693_out_o;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        y_fu_46 <= 16'd0;
    end else if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln1099_fu_174_p2 == 1'd0))) begin
        y_fu_46 <= y_2_fu_179_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        conv2_i_i_lcssa724_load_reg_279 <= conv2_i_i_lcssa724_fu_66;
        p_0_0_0501690_lcssa705729_load_reg_294 <= p_0_0_0501690_lcssa705729_fu_78;
        p_0_0_0502688_lcssa702727_load_reg_289 <= p_0_0_0502688_lcssa702727_fu_74;
        p_0_0_0503692_lcssa699726_load_reg_284 <= p_0_0_0503692_lcssa699726_fu_70;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        height_val_read_reg_266 <= height_val;
        loopWidth_reg_271 <= loopWidth_fu_120_p2;
        width_val_read_reg_261 <= width_val;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state1)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

assign ap_ST_fsm_state3_blk = 1'b0;

always @ (*) begin
    if ((grp_ZipperRemoval_Pipeline_VITIS_LOOP_1101_2_fu_94_ap_done == 1'b0)) begin
        ap_ST_fsm_state4_blk = 1'b1;
    end else begin
        ap_ST_fsm_state4_blk = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln1099_fu_174_p2 == 1'd1))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (real_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln1099_fu_174_p2 == 1'd1))) begin
        internal_ap_ready = 1'b1;
    end else begin
        internal_ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (start_full_n == 1'b0))) begin
        real_start = 1'b0;
    end else begin
        real_start = ap_start;
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (real_start == 1'b1))) begin
        start_write = 1'b1;
    end else begin
        start_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln1099_fu_174_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            if (((grp_ZipperRemoval_Pipeline_VITIS_LOOP_1101_2_fu_94_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

always @ (*) begin
    ap_block_state1 = ((ap_done_reg == 1'b1) | (real_start == 1'b0));
end

assign ap_ready = internal_ap_ready;

assign grp_ZipperRemoval_Pipeline_VITIS_LOOP_1101_2_fu_94_ap_start = grp_ZipperRemoval_Pipeline_VITIS_LOOP_1101_2_fu_94_ap_start_reg;

assign icmp_ln1099_fu_174_p2 = ((y_fu_46 == height_val_read_reg_266) ? 1'b1 : 1'b0);

assign imgRgb_read = grp_ZipperRemoval_Pipeline_VITIS_LOOP_1101_2_fu_94_imgRgb_read;

assign imgUnzip_din = grp_ZipperRemoval_Pipeline_VITIS_LOOP_1101_2_fu_94_imgUnzip_din;

assign imgUnzip_write = grp_ZipperRemoval_Pipeline_VITIS_LOOP_1101_2_fu_94_imgUnzip_write;

assign loopWidth_fu_120_p2 = (zext_ln1085_fu_116_p1 + 17'd1);

assign start_out = real_start;

assign y_2_fu_179_p2 = (y_fu_46 + 16'd1);

assign zext_ln1085_fu_116_p1 = width_val;

endmodule //pcam_v_demosaic_0_0_ZipperRemoval
