// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* DowngradeIPIdentifiedWarnings="yes" *)
module pcam_v_demosaic_0_0_ZipperRemoval_Pipeline_VITIS_LOOP_1101_2 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        imgRgb_dout,
        imgRgb_empty_n,
        imgRgb_read,
        imgRgb_num_data_valid,
        imgRgb_fifo_cap,
        imgUnzip_din,
        imgUnzip_full_n,
        imgUnzip_write,
        imgUnzip_num_data_valid,
        imgUnzip_fifo_cap,
        p_0_0_0501690_lcssa705729,
        p_0_0_0502688_lcssa702727,
        p_0_0_0503692_lcssa699726,
        conv2_i_i_lcssa724,
        width_val,
        loopWidth,
        p_0_0_0504_1704_out,
        p_0_0_0504_1704_out_ap_vld,
        p_0_0_0505_1701_out,
        p_0_0_0505_1701_out_ap_vld,
        p_0_0_0506_1698_out,
        p_0_0_0506_1698_out_ap_vld,
        p_0_0_0504_1696_out_i,
        p_0_0_0504_1696_out_o,
        p_0_0_0504_1696_out_o_ap_vld,
        p_0_0_0505_1695_out_i,
        p_0_0_0505_1695_out_o,
        p_0_0_0505_1695_out_o_ap_vld,
        p_0_0_0506_1694_out_i,
        p_0_0_0506_1694_out_o,
        p_0_0_0506_1694_out_o_ap_vld,
        p_0_0_0507_1693_out_i,
        p_0_0_0507_1693_out_o,
        p_0_0_0507_1693_out_o_ap_vld,
        phi_ln1132_out,
        phi_ln1132_out_ap_vld
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [23:0] imgRgb_dout;
input   imgRgb_empty_n;
output   imgRgb_read;
input  [2:0] imgRgb_num_data_valid;
input  [2:0] imgRgb_fifo_cap;
output  [23:0] imgUnzip_din;
input   imgUnzip_full_n;
output   imgUnzip_write;
input  [31:0] imgUnzip_num_data_valid;
input  [31:0] imgUnzip_fifo_cap;
input  [7:0] p_0_0_0501690_lcssa705729;
input  [7:0] p_0_0_0502688_lcssa702727;
input  [7:0] p_0_0_0503692_lcssa699726;
input  [4:0] conv2_i_i_lcssa724;
input  [15:0] width_val;
input  [16:0] loopWidth;
output  [7:0] p_0_0_0504_1704_out;
output   p_0_0_0504_1704_out_ap_vld;
output  [7:0] p_0_0_0505_1701_out;
output   p_0_0_0505_1701_out_ap_vld;
output  [7:0] p_0_0_0506_1698_out;
output   p_0_0_0506_1698_out_ap_vld;
input  [7:0] p_0_0_0504_1696_out_i;
output  [7:0] p_0_0_0504_1696_out_o;
output   p_0_0_0504_1696_out_o_ap_vld;
input  [7:0] p_0_0_0505_1695_out_i;
output  [7:0] p_0_0_0505_1695_out_o;
output   p_0_0_0505_1695_out_o_ap_vld;
input  [7:0] p_0_0_0506_1694_out_i;
output  [7:0] p_0_0_0506_1694_out_o;
output   p_0_0_0506_1694_out_o_ap_vld;
input  [7:0] p_0_0_0507_1693_out_i;
output  [7:0] p_0_0_0507_1693_out_o;
output   p_0_0_0507_1693_out_o_ap_vld;
output  [4:0] phi_ln1132_out;
output   phi_ln1132_out_ap_vld;

reg ap_idle;
reg imgRgb_read;
reg imgUnzip_write;
reg p_0_0_0504_1704_out_ap_vld;
reg p_0_0_0505_1701_out_ap_vld;
reg p_0_0_0506_1698_out_ap_vld;
reg[7:0] p_0_0_0504_1696_out_o;
reg p_0_0_0504_1696_out_o_ap_vld;
reg[7:0] p_0_0_0505_1695_out_o;
reg p_0_0_0505_1695_out_o_ap_vld;
reg[7:0] p_0_0_0506_1694_out_o;
reg p_0_0_0506_1694_out_o_ap_vld;
reg[7:0] p_0_0_0507_1693_out_o;
reg p_0_0_0507_1693_out_o_ap_vld;
reg[4:0] phi_ln1132_out;
reg phi_ln1132_out_ap_vld;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_idle_pp0;
reg   [0:0] icmp_ln1101_reg_721;
reg   [0:0] icmp_ln1107_reg_725;
reg    ap_predicate_op40_read_state2;
reg    ap_block_state2_pp0_stage0_iter1_grp1;
reg   [0:0] icmp_ln1159_reg_729;
reg   [0:0] icmp_ln1159_reg_729_pp0_iter2_reg;
reg    ap_block_state4_pp0_stage0_iter3_grp1;
reg    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln1101_fu_217_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    imgRgb_blk_n;
wire    ap_block_pp0_stage0_grp1;
reg    imgUnzip_blk_n;
wire    ap_block_pp0_stage0_11001_grp0;
reg    ap_block_pp0_stage0_subdone_grp0_done_reg;
wire    ap_block_pp0_stage0_subdone_grp0;
reg    ap_block_pp0_stage0_11001;
reg   [0:0] icmp_ln1101_reg_721_pp0_iter1_reg;
wire   [0:0] icmp_ln1107_fu_229_p2;
wire   [0:0] icmp_ln1159_fu_235_p2;
reg   [0:0] icmp_ln1159_reg_729_pp0_iter1_reg;
reg   [7:0] p_0_0_0506_1698_load_reg_733;
reg    ap_block_pp0_stage0_11001_grp1;
reg   [7:0] p_0_0_0505_1701_load_reg_741;
reg   [7:0] p_0_0_0504_1704_load_reg_749;
wire   [7:0] conv3_i_i708_fu_606_p3;
reg   [7:0] conv3_i_i708_reg_757;
wire   [7:0] conv3_i_i79707_fu_613_p3;
reg   [7:0] conv3_i_i79707_reg_762;
wire   [7:0] conv3_i_i188706_fu_620_p3;
reg   [7:0] conv3_i_i188706_reg_767;
reg    ap_condition_exit_pp0_iter1_stage0;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
wire    ap_block_pp0_stage0_grp0;
wire   [7:0] zext_ln1101_fu_297_p1;
wire   [4:0] trunc_ln1_fu_407_p4;
wire    ap_loop_init;
reg   [16:0] x_fu_110;
wire   [16:0] x_2_fu_223_p2;
reg   [16:0] ap_sig_allocacmp_x_1;
wire    ap_block_pp0_stage0;
reg   [4:0] p_0_0_0507_1697_fu_114;
reg   [7:0] p_0_0_0506_1698_fu_118;
reg   [7:0] p_0_0_0505_1701_fu_122;
wire   [7:0] trunc_ln1109_fu_255_p1;
reg   [7:0] p_0_0_0504_1704_fu_126;
reg    ap_block_pp0_stage0_01001_grp1;
wire   [16:0] zext_ln1085_fu_179_p1;
wire   [5:0] tmp_fu_329_p4;
wire   [6:0] lshr_ln1129_1_fu_343_p4;
wire   [4:0] lshr_ln1129_2_fu_357_p4;
wire   [4:0] tmp_1_fu_371_p4;
wire   [6:0] zext_ln1129_4_fu_381_p1;
wire   [6:0] zext_ln1129_1_fu_339_p1;
wire   [6:0] add_ln1129_fu_385_p2;
wire   [7:0] zext_ln1129_fu_391_p1;
wire   [7:0] zext_ln1129_2_fu_353_p1;
wire   [7:0] add_ln1129_1_fu_395_p2;
wire   [7:0] zext_ln1129_3_fu_367_p1;
wire   [7:0] lum_fu_401_p2;
wire   [0:0] icmp_ln1144_1_fu_423_p2;
wire   [0:0] icmp_ln1144_fu_417_p2;
wire   [0:0] xor_ln1144_fu_429_p2;
wire   [0:0] icmp_ln1144_2_fu_441_p2;
wire   [0:0] xor_ln1144_1_fu_447_p2;
wire   [0:0] icmp_ln1144_3_fu_453_p2;
wire   [8:0] shl_ln_fu_465_p3;
wire   [8:0] zext_ln1147_fu_472_p1;
wire   [8:0] zext_ln1147_2_fu_480_p1;
wire   [8:0] add_ln1147_fu_484_p2;
wire   [9:0] zext_ln1147_3_fu_490_p1;
wire   [9:0] zext_ln1147_1_fu_476_p1;
wire   [9:0] add_ln1147_1_fu_494_p2;
wire   [8:0] shl_ln1_fu_510_p3;
wire   [8:0] zext_ln1148_fu_517_p1;
wire   [8:0] zext_ln1148_2_fu_525_p1;
wire   [8:0] add_ln1148_fu_529_p2;
wire   [9:0] zext_ln1148_3_fu_535_p1;
wire   [9:0] zext_ln1148_1_fu_521_p1;
wire   [9:0] add_ln1148_1_fu_539_p2;
wire   [8:0] shl_ln2_fu_555_p3;
wire   [8:0] zext_ln1149_fu_562_p1;
wire   [8:0] zext_ln1149_2_fu_570_p1;
wire   [8:0] add_ln1149_fu_574_p2;
wire   [9:0] zext_ln1149_3_fu_580_p1;
wire   [9:0] zext_ln1149_1_fu_566_p1;
wire   [9:0] add_ln1149_1_fu_584_p2;
wire   [0:0] and_ln1144_fu_435_p2;
wire   [0:0] and_ln1144_1_fu_459_p2;
wire   [0:0] or_ln1144_fu_600_p2;
wire   [7:0] b_s_fu_590_p4;
wire   [7:0] g_s_fu_545_p4;
wire   [7:0] r_s_fu_500_p4;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
reg    ap_condition_530;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_block_pp0_stage0_subdone_grp0_done_reg = 1'b0;
#0 x_fu_110 = 17'd0;
#0 p_0_0_0507_1697_fu_114 = 5'd0;
#0 p_0_0_0506_1698_fu_118 = 8'd0;
#0 p_0_0_0505_1701_fu_122 = 8'd0;
#0 p_0_0_0504_1704_fu_126 = 8'd0;
#0 ap_done_reg = 1'b0;
end

pcam_v_demosaic_0_0_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_block_pp0_stage0_subdone_grp0_done_reg <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_block_pp0_stage0_subdone_grp0_done_reg <= 1'b0;
        end else if ((1'b0 == ap_block_pp0_stage0_subdone_grp0)) begin
            ap_block_pp0_stage0_subdone_grp0_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter2_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter1_stage0)) begin
            ap_enable_reg_pp0_iter2 <= 1'b0;
        end else if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            p_0_0_0504_1704_fu_126 <= p_0_0_0501690_lcssa705729;
        end else if ((1'b1 == ap_condition_530)) begin
            p_0_0_0504_1704_fu_126 <= {{imgRgb_dout[15:8]}};
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            p_0_0_0505_1701_fu_122 <= p_0_0_0502688_lcssa702727;
        end else if ((1'b1 == ap_condition_530)) begin
            p_0_0_0505_1701_fu_122 <= trunc_ln1109_fu_255_p1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            p_0_0_0506_1698_fu_118 <= p_0_0_0503692_lcssa699726;
        end else if ((1'b1 == ap_condition_530)) begin
            p_0_0_0506_1698_fu_118 <= {{imgRgb_dout[23:16]}};
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001_grp1)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            p_0_0_0507_1697_fu_114 <= conv2_i_i_lcssa724;
        end else if ((ap_enable_reg_pp0_iter2 == 1'b1)) begin
            p_0_0_0507_1697_fu_114 <= {{lum_fu_401_p2[7:3]}};
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln1101_fu_217_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            x_fu_110 <= x_2_fu_223_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            x_fu_110 <= 17'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        icmp_ln1101_reg_721 <= icmp_ln1101_fu_217_p2;
        icmp_ln1101_reg_721_pp0_iter1_reg <= icmp_ln1101_reg_721;
        icmp_ln1107_reg_725 <= icmp_ln1107_fu_229_p2;
        icmp_ln1159_reg_729 <= icmp_ln1159_fu_235_p2;
        icmp_ln1159_reg_729_pp0_iter1_reg <= icmp_ln1159_reg_729;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001_grp1)) begin
        conv3_i_i188706_reg_767 <= conv3_i_i188706_fu_620_p3;
        conv3_i_i708_reg_757 <= conv3_i_i708_fu_606_p3;
        conv3_i_i79707_reg_762 <= conv3_i_i79707_fu_613_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        icmp_ln1159_reg_729_pp0_iter2_reg <= icmp_ln1159_reg_729_pp0_iter1_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_0_0_0504_1704_load_reg_749 <= p_0_0_0504_1704_fu_126;
        p_0_0_0505_1701_load_reg_741 <= p_0_0_0505_1701_fu_122;
        p_0_0_0506_1698_load_reg_733 <= p_0_0_0506_1698_fu_118;
    end
end

always @ (*) begin
    if (((icmp_ln1101_fu_217_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (icmp_ln1101_reg_721 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter2_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_x_1 = 17'd0;
    end else begin
        ap_sig_allocacmp_x_1 = x_fu_110;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_grp1) & (ap_predicate_op40_read_state2 == 1'b1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        imgRgb_blk_n = imgRgb_empty_n;
    end else begin
        imgRgb_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_predicate_op40_read_state2 == 1'b1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        imgRgb_read = 1'b1;
    end else begin
        imgRgb_read = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln1159_reg_729_pp0_iter2_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_grp1) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        imgUnzip_blk_n = imgUnzip_full_n;
    end else begin
        imgUnzip_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((icmp_ln1159_reg_729_pp0_iter2_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        imgUnzip_write = 1'b1;
    end else begin
        imgUnzip_write = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_grp1) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        p_0_0_0504_1696_out_o = p_0_0_0504_1704_load_reg_749;
    end else begin
        p_0_0_0504_1696_out_o = p_0_0_0504_1696_out_i;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        p_0_0_0504_1696_out_o_ap_vld = 1'b1;
    end else begin
        p_0_0_0504_1696_out_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (ap_loop_exit_ready_pp0_iter2_reg == 1'b1) & (icmp_ln1101_reg_721_pp0_iter1_reg == 1'd1))) begin
        p_0_0_0504_1704_out_ap_vld = 1'b1;
    end else begin
        p_0_0_0504_1704_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_grp1) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        p_0_0_0505_1695_out_o = p_0_0_0505_1701_load_reg_741;
    end else begin
        p_0_0_0505_1695_out_o = p_0_0_0505_1695_out_i;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        p_0_0_0505_1695_out_o_ap_vld = 1'b1;
    end else begin
        p_0_0_0505_1695_out_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (ap_loop_exit_ready_pp0_iter2_reg == 1'b1) & (icmp_ln1101_reg_721_pp0_iter1_reg == 1'd1))) begin
        p_0_0_0505_1701_out_ap_vld = 1'b1;
    end else begin
        p_0_0_0505_1701_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_grp1) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        p_0_0_0506_1694_out_o = p_0_0_0506_1698_load_reg_733;
    end else begin
        p_0_0_0506_1694_out_o = p_0_0_0506_1694_out_i;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        p_0_0_0506_1694_out_o_ap_vld = 1'b1;
    end else begin
        p_0_0_0506_1694_out_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (ap_loop_exit_ready_pp0_iter2_reg == 1'b1) & (icmp_ln1101_reg_721_pp0_iter1_reg == 1'd1))) begin
        p_0_0_0506_1698_out_ap_vld = 1'b1;
    end else begin
        p_0_0_0506_1698_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_grp1) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        p_0_0_0507_1693_out_o = zext_ln1101_fu_297_p1;
    end else begin
        p_0_0_0507_1693_out_o = p_0_0_0507_1693_out_i;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        p_0_0_0507_1693_out_o_ap_vld = 1'b1;
    end else begin
        p_0_0_0507_1693_out_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_grp0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        phi_ln1132_out = 5'd0;
    end else if (((1'b0 == ap_block_pp0_stage0_grp1) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        phi_ln1132_out = {{lum_fu_401_p2[7:3]}};
    end else begin
        phi_ln1132_out = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        phi_ln1132_out_ap_vld = 1'b1;
    end else begin
        phi_ln1132_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln1129_1_fu_395_p2 = (zext_ln1129_fu_391_p1 + zext_ln1129_2_fu_353_p1);

assign add_ln1129_fu_385_p2 = (zext_ln1129_4_fu_381_p1 + zext_ln1129_1_fu_339_p1);

assign add_ln1147_1_fu_494_p2 = (zext_ln1147_3_fu_490_p1 + zext_ln1147_1_fu_476_p1);

assign add_ln1147_fu_484_p2 = (zext_ln1147_fu_472_p1 + zext_ln1147_2_fu_480_p1);

assign add_ln1148_1_fu_539_p2 = (zext_ln1148_3_fu_535_p1 + zext_ln1148_1_fu_521_p1);

assign add_ln1148_fu_529_p2 = (zext_ln1148_fu_517_p1 + zext_ln1148_2_fu_525_p1);

assign add_ln1149_1_fu_584_p2 = (zext_ln1149_3_fu_580_p1 + zext_ln1149_1_fu_566_p1);

assign add_ln1149_fu_574_p2 = (zext_ln1149_fu_562_p1 + zext_ln1149_2_fu_570_p1);

assign and_ln1144_1_fu_459_p2 = (xor_ln1144_1_fu_447_p2 & icmp_ln1144_3_fu_453_p2);

assign and_ln1144_fu_435_p2 = (xor_ln1144_fu_429_p2 & icmp_ln1144_fu_417_p2);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001_grp1 = (((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_block_state4_pp0_stage0_iter3_grp1)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state2_pp0_stage0_iter1_grp1)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = (((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_block_state4_pp0_stage0_iter3_grp1)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state2_pp0_stage0_iter1_grp1)));
end

assign ap_block_pp0_stage0_11001_grp0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_11001_grp1 = (((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_block_state4_pp0_stage0_iter3_grp1)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state2_pp0_stage0_iter1_grp1)));
end

assign ap_block_pp0_stage0_grp0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_grp1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_subdone = (((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_block_state4_pp0_stage0_iter3_grp1)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state2_pp0_stage0_iter1_grp1)));
end

assign ap_block_pp0_stage0_subdone_grp0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state2_pp0_stage0_iter1_grp1 = ((ap_predicate_op40_read_state2 == 1'b1) & (imgRgb_empty_n == 1'b0));
end

always @ (*) begin
    ap_block_state4_pp0_stage0_iter3_grp1 = ((icmp_ln1159_reg_729_pp0_iter2_reg == 1'd0) & (imgUnzip_full_n == 1'b0));
end

always @ (*) begin
    ap_condition_530 = ((icmp_ln1107_reg_725 == 1'd1) & (icmp_ln1101_reg_721 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1));
end

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

always @ (*) begin
    ap_predicate_op40_read_state2 = ((icmp_ln1107_reg_725 == 1'd1) & (icmp_ln1101_reg_721 == 1'd0));
end

assign ap_ready = ap_ready_sig;

assign b_s_fu_590_p4 = {{add_ln1149_1_fu_584_p2[9:2]}};

assign conv3_i_i188706_fu_620_p3 = ((or_ln1144_fu_600_p2[0:0] == 1'b1) ? r_s_fu_500_p4 : p_0_0_0506_1698_load_reg_733);

assign conv3_i_i708_fu_606_p3 = ((or_ln1144_fu_600_p2[0:0] == 1'b1) ? b_s_fu_590_p4 : p_0_0_0504_1704_load_reg_749);

assign conv3_i_i79707_fu_613_p3 = ((or_ln1144_fu_600_p2[0:0] == 1'b1) ? g_s_fu_545_p4 : p_0_0_0505_1701_load_reg_741);

assign g_s_fu_545_p4 = {{add_ln1148_1_fu_539_p2[9:2]}};

assign icmp_ln1101_fu_217_p2 = ((ap_sig_allocacmp_x_1 == loopWidth) ? 1'b1 : 1'b0);

assign icmp_ln1107_fu_229_p2 = ((ap_sig_allocacmp_x_1 < zext_ln1085_fu_179_p1) ? 1'b1 : 1'b0);

assign icmp_ln1144_1_fu_423_p2 = ((p_0_0_0507_1697_fu_114 < trunc_ln1_fu_407_p4) ? 1'b1 : 1'b0);

assign icmp_ln1144_2_fu_441_p2 = ((p_0_0_0507_1693_out_i < zext_ln1101_fu_297_p1) ? 1'b1 : 1'b0);

assign icmp_ln1144_3_fu_453_p2 = ((p_0_0_0507_1697_fu_114 < trunc_ln1_fu_407_p4) ? 1'b1 : 1'b0);

assign icmp_ln1144_fu_417_p2 = ((p_0_0_0507_1693_out_i < zext_ln1101_fu_297_p1) ? 1'b1 : 1'b0);

assign icmp_ln1159_fu_235_p2 = ((ap_sig_allocacmp_x_1 == 17'd0) ? 1'b1 : 1'b0);

assign imgUnzip_din = {{{conv3_i_i188706_reg_767}, {conv3_i_i708_reg_757}}, {conv3_i_i79707_reg_762}};

assign lshr_ln1129_1_fu_343_p4 = {{p_0_0_0505_1701_fu_122[7:1]}};

assign lshr_ln1129_2_fu_357_p4 = {{p_0_0_0505_1701_fu_122[7:3]}};

assign lum_fu_401_p2 = (add_ln1129_1_fu_395_p2 + zext_ln1129_3_fu_367_p1);

assign or_ln1144_fu_600_p2 = (and_ln1144_fu_435_p2 | and_ln1144_1_fu_459_p2);

assign p_0_0_0504_1704_out = p_0_0_0504_1704_load_reg_749;

assign p_0_0_0505_1701_out = p_0_0_0505_1701_load_reg_741;

assign p_0_0_0506_1698_out = p_0_0_0506_1698_load_reg_733;

assign r_s_fu_500_p4 = {{add_ln1147_1_fu_494_p2[9:2]}};

assign shl_ln1_fu_510_p3 = {{p_0_0_0505_1701_load_reg_741}, {1'd0}};

assign shl_ln2_fu_555_p3 = {{p_0_0_0504_1704_load_reg_749}, {1'd0}};

assign shl_ln_fu_465_p3 = {{p_0_0_0506_1698_load_reg_733}, {1'd0}};

assign tmp_1_fu_371_p4 = {{p_0_0_0504_1704_fu_126[7:3]}};

assign tmp_fu_329_p4 = {{p_0_0_0506_1698_fu_118[7:2]}};

assign trunc_ln1109_fu_255_p1 = imgRgb_dout[7:0];

assign trunc_ln1_fu_407_p4 = {{lum_fu_401_p2[7:3]}};

assign x_2_fu_223_p2 = (ap_sig_allocacmp_x_1 + 17'd1);

assign xor_ln1144_1_fu_447_p2 = (icmp_ln1144_2_fu_441_p2 ^ 1'd1);

assign xor_ln1144_fu_429_p2 = (icmp_ln1144_1_fu_423_p2 ^ 1'd1);

assign zext_ln1085_fu_179_p1 = width_val;

assign zext_ln1101_fu_297_p1 = p_0_0_0507_1697_fu_114;

assign zext_ln1129_1_fu_339_p1 = tmp_fu_329_p4;

assign zext_ln1129_2_fu_353_p1 = lshr_ln1129_1_fu_343_p4;

assign zext_ln1129_3_fu_367_p1 = lshr_ln1129_2_fu_357_p4;

assign zext_ln1129_4_fu_381_p1 = tmp_1_fu_371_p4;

assign zext_ln1129_fu_391_p1 = add_ln1129_fu_385_p2;

assign zext_ln1147_1_fu_476_p1 = shl_ln_fu_465_p3;

assign zext_ln1147_2_fu_480_p1 = p_0_0_0506_1694_out_i;

assign zext_ln1147_3_fu_490_p1 = add_ln1147_fu_484_p2;

assign zext_ln1147_fu_472_p1 = p_0_0_0506_1698_fu_118;

assign zext_ln1148_1_fu_521_p1 = shl_ln1_fu_510_p3;

assign zext_ln1148_2_fu_525_p1 = p_0_0_0505_1695_out_i;

assign zext_ln1148_3_fu_535_p1 = add_ln1148_fu_529_p2;

assign zext_ln1148_fu_517_p1 = p_0_0_0505_1701_fu_122;

assign zext_ln1149_1_fu_566_p1 = shl_ln2_fu_555_p3;

assign zext_ln1149_2_fu_570_p1 = p_0_0_0504_1696_out_i;

assign zext_ln1149_3_fu_580_p1 = add_ln1149_fu_574_p2;

assign zext_ln1149_fu_562_p1 = p_0_0_0504_1704_fu_126;

endmodule //pcam_v_demosaic_0_0_ZipperRemoval_Pipeline_VITIS_LOOP_1101_2
