
# Written by F. Wysong w/ debugging and help from Gemini.
# This script is meant to be a simple demonstration of how to set up the PCAM with VDMA

# ACTUAL LOADING AND TESTING

## CHANGE FILE HERE FOR BITSTREAM. or don't. ##
overlay_file = "pcam.bit"

ol = _LOAD_OVERLAY(overlay_file)

# Initial var setup for functions later.
#VDMA
vdma_base = ol.ip_dict['axi_vdma_0']['phys_addr']
vdma = MMIO(vdma_base, 0x10000)
width_vdma, height_vdma = 1920, 1080 #could be 224
# stride = width_vdma * 3  # 3 bytes per pixel for RGB888


# Set up IIC (actually this one just is the setup)
iic = AxiIIC(ol.ip_dict['axi_iic_0']) 
CAM_I2C_ADDR = 0x3C  # Standard 7-bit I2C address for the OV5640


#Camera power pin (adjust accordingly)
cam_pwup = ol.axi_gpio_0.channel1[0]


#Demosaic assign
demosaic = ol.vdemo
#INIT BELOW

# Initialize camera for 1080 at 30fps but do NOT start
_PCAM_PC(cam_pwup)           # give it the GPIO pin corresponding to the power/en
_PCAM_CONFIGURE_BASE()
_PCAM_CONFIGURE_1080p30()
## PCAM SHOULD BE CONFIGURED BUT *NOT* RUNNING



# Configure demosaic
_DEMOSAIC_CONFIG_RES(demosaic, 1920, 1080)
_DEMOSAIC_SET_BAYER(demosaic, 0x00)       # 0 = RGGB, 1 = GRBG, 2 = GBRG, 3 = BGGR (this one but colors are reversed so its actuall RGGB)
_DEMOSAIC_SET_CTRL(demosaic, 0x81)

#create frame buffer
frame_buffer = _ALLOCATE_FRAME_BUFFER(width_vdma, height_vdma)

#configure the VDMA
_VDMA_CONFIG_WHOLISTIC(vdma, frame_buffer, width_vdma, height_vdma)

#quick check
# _RUN_PIPELINE_DIAGNOSTICS()


# Start the camera - set the pipeline is motion

#ok big time now
_PCAM_START_CAPTURE()   # AGAIN ALWAYS START THE CAMERA LAST. If you don't everything breaks.




# TEST PLOTTING (GENERATED BY GEMINI) - also note that this actually plots frames backwards as in Frame 2 is the most recent and Frame 0 is the oldest

fig, axes = plt.subplots(1, 3, figsize=(18, 6))

for i in range(3):
    # Wait 0.016666666666 blah blah blah seconds - it's about one frame
    time.sleep(0.02) # actually adding a little extra to make sure we don't grab the same frame twice
    

    #flush
    frame_buffer.invalidate()
    
    # We must make a copy() of the buffer, otherwise matplotlib will just 
    # plot three pointers to the exact same live memory space
    captured_frame = np.copy(frame_buffer)
    rgb_frame = captured_frame[:, :, ::-1]
    
    # Plot the frozen frames
    axes[i].imshow(rgb_frame)
    axes[i].set_title(f"Frame 0+{i}")
    axes[i].axis('off')

plt.tight_layout()
plt.show()